//  JesAI Company Law Knowledge Module 
// NLC validated  Nazmul, Advocate, Supreme Court of Bangladesh
// CURRENT LAWS ONLY:
//  Companies Act 1994 (current, with all amendments)
//  Partnership Act 1932
//  RJSC Online System 2024 (roc.gov.bd)
//  One Person Company Rules 2020
//  Foreign Company Registration Rules 2018
//  BIDA Act 2016 + Investment Policy 2021
//  Bangladesh Securities and Exchange Commission Rules
//  Societies Registration Act 1860 (for NPO)
// Last verified: 2025-03-09

import type { KnowledgeBank, LegalRule, QAEntry } from "../../shared/types";

const rules: LegalRule[] = [
  {
    id: "co-pvt-001",
    title: "Private Limited Company  Companies Act 1994",
    rule: "Minimum 2, maximum 50 shareholders. Minimum 2 directors. Shares cannot be offered to public. Name must include 'Limited' or 'Ltd'. Registered with RJSC. Separate legal entity with limited liability.",
    source: "Companies Act 1994, Sections 2, 9, 11",
    certainty: "confirmed",
  },
  {
    id: "co-opc-001",
    title: "One Person Company (OPC)  Rules 2020",
    rule: "Single Bangladeshi individual can incorporate OPC. Sole member is sole director. No share transfer or new members without converting. Limited liability applies. Cannot be used for banking business.",
    source: "Companies Act 1994 (amended); One Person Company Rules 2020",
    certainty: "confirmed",
  },
  {
    id: "co-partnership-001",
    title: "Partnership  Partnership Act 1932",
    rule: "Partnership registration with RJSC is optional but recommended. Unregistered firm cannot sue. Maximum 20 partners (10 in banking). Partners have unlimited personal liability.",
    source: "Partnership Act 1932, Sections 4, 69",
    certainty: "confirmed",
  },
  {
    id: "co-foreign-001",
    title: "Foreign Company Registration",
    rule: "Foreign companies must register with RJSC within 30 days of establishing Bangladesh presence. Options: Branch Office (full commerce), Liaison Office (promotion only), Subsidiary (new BD company). BIDA registration also required.",
    source: "Companies Act 1994, Sections 379-386; Foreign Company Rules 2018",
    certainty: "confirmed",
  },
  {
    id: "co-annual-001",
    title: "Annual Compliance  Companies Act 1994",
    rule: "AGM within 120 days of financial year end. Annual return filed with RJSC within 21 days of AGM. Audited financials required. Non-filing: penalty + possible strike-off.",
    source: "Companies Act 1994, Sections 81, 192",
    certainty: "confirmed",
  },
  {
    id: "co-pub-001",
    title: "Public Limited Company  Companies Act 1994",
    rule: "Minimum 7 shareholders, no maximum. Minimum 3 directors. Can offer shares to public. Name must include 'Public Limited Company' or 'PLC'. Must obtain prospectus or file statement in lieu. More stringent compliance including mandatory audit regardless of capital.",
    source: "Companies Act 1994, Sections 2, 10, 12",
    certainty: "confirmed",
  },
  {
    id: "co-director-001",
    title: "Director Duties and Liabilities  Companies Act 1994",
    rule: "Directors owe fiduciary duty to company. Must act in good faith, avoid conflict of interest, not make secret profits, disclose personal interest in contracts. Breach: liable to repay profits, compensate company, possible criminal liability under S.142-147.",
    source: "Companies Act 1994, Sections 140-147",
    certainty: "confirmed",
  },
  {
    id: "co-meeting-001",
    title: "Company Meetings  Companies Act 1994",
    rule: "Board meeting: at least once per quarter. AGM: within 120 days of financial year end (max 15 months gap). EGM: as needed. Notice period: Board 7 days, AGM 21 days, EGM 21 days (shorter if 95% consent). Quorum: Board = per AOA (usually majority), AGM = 5 members or 25% of total, whichever is less.",
    source: "Companies Act 1994, Sections 81, 84, 86, 87, 93",
    certainty: "confirmed",
  },
  {
    id: "co-charge-001",
    title: "Creation and Registration of Charges  Companies Act 1994",
    rule: "Company must register charges on property (mortgage, hypothecation) with RJSC within 30 days of creation. Form VIII for creation, Form IX for satisfaction. Unregistered charge is void against liquidator and any creditor. Applies to: property, uncalled share capital, book debts, goodwill.",
    source: "Companies Act 1994, Sections 148-155",
    certainty: "confirmed",
  },
  {
    id: "co-fdi-001",
    title: "Foreign Direct Investment  Sectors and Restrictions",
    rule: "BIDA Act 2016 + Investment Policy 2021: 100% FDI allowed in most manufacturing and service sectors. Reserved sectors: defense, nuclear energy, security printing, forestry. Restricted: banking (requires BB approval, max 62% foreign), insurance (requires IDRA approval, max 60% foreign), telecommunications (requires BTRC approval). Profit repatriation allowed for FDI companies.",
    source: "BIDA Act 2016; Investment Policy 2021; Bangladesh Bank FDI Guidelines",
    certainty: "confirmed",
  },
  {
    id: "co-windup-001",
    title: "Winding Up by Court  Companies Act 1994",
    rule: "Court can wind up company on petition by: company, creditor, contributory, or Registrar. Grounds: inability to pay debts, just and equitable, deadlock, persistent non-compliance. Official liquidator appointed. Preferential debts paid first: employee wages (4 months), government dues. Contributories liable to deficiency.",
    source: "Companies Act 1994, Sections 284-385",
    certainty: "confirmed",
  },
  {
    id: "co-convert-001",
    title: "Conversion of Company Type  Companies Act 1994",
    rule: "Private Ltd can convert to Public Ltd by special resolution (75%) + meeting minimum requirements (7 shareholders, 3 directors). Public Ltd can convert to Private Ltd by special resolution if it has not issued shares to public or has bought back all public shares. OPC converts to Pvt Ltd on adding member.",
    source: "Companies Act 1994, Sections 16-18",
    certainty: "confirmed",
  },
];

const qaBank: QAEntry[] = [
  //  COMPANY FORMATION 
  {
    id: "co-qa-001",
    triggerKeywords: ["register company", "form company", "incorporate", "start company"],
    question: "How do I register a private limited company in Bangladesh?",
    irac: {
      issue: "Step-by-step process for incorporating a private limited company with RJSC?",
      rule: "Companies Act 1994 + RJSC Online System (roc.gov.bd): Name clearance  prepare MOA/AOA  online submission  payment  Certificate of Incorporation. Fully online since 2020.",
      application: "Minimum: 2 shareholders, 2 directors (same persons allowed), registered office in Bangladesh. All TINs required. Physical appearance at RJSC not required.",
      conclusion: "**Private Ltd Company Registration:**\n\n1. **Name clearance**  roc.gov.bd  1-3 days\n2. **Prepare MOA & AOA**  define business, shares\n3. **Online application**  Form I, VI, XII\n4. **Pay RJSC fees**  based on authorized capital\n5. **Certificate of Incorporation**  7-15 working days\n\n**Minimum requirements:**\n 2 shareholders, 2 directors\n TIN for all directors/shareholders\n NID for Bangladeshi nationals\n Registered Bangladesh office address\n\n**Total time:** 15-20 working days\n\n Document list  299\n Full RJSC guide  2,999\n MOA + AOA drafting  4,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-002",
    triggerKeywords: ["company name clearance", "name approval rjsc", "name availability company", "rjsc name check"],
    question: "How do I get company name clearance from RJSC?",
    irac: {
      issue: "Process for obtaining company name clearance?",
      rule: "Companies Act 1994, Section 11 + RJSC Rules: Name clearance required before incorporation. Apply online with 3 name options. Clearance valid 90 days. Cannot use: Bank, Insurance, Government, National without permission.",
      application: "roc.gov.bd  Apply name clearance  Submit 3 options  RJSC checks existing names  Approval/rejection in 1-3 working days.",
      conclusion: "**Name clearance:**\n1. roc.gov.bd  Name clearance application\n2. Submit 3 names in preference order\n3. Fee: ~BDT 200\n4. Result: 1-3 working days\n5. **Valid for 90 days**  register within this period\n\n**Prohibited:**\n Identical to existing company\n Deceptively similar names\n 'Bank', 'Insurance', 'National', 'Government' without permission\n\n Name clearance guide  99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-003",
    triggerKeywords: ["one person company", "opc", "single person company", "single member company"],
    question: "Can one person form a company alone?",
    irac: {
      issue: "Can a single individual incorporate a company in Bangladesh?",
      rule: "One Person Company Rules 2020: Single Bangladeshi resident individual can form OPC. Limited liability applies. Cannot be incorporated by another company. Must name a nominee director.",
      application: "Solo entrepreneur wanting limited liability without a second partner  OPC is ideal. Owner's personal assets protected from company debts.",
      conclusion: "**OPC  One Person Company:**\n\n **Requirements:**\n Single Bangladeshi individual\n Must be resident in Bangladesh\n Cannot be another company\n Name a nominee director (in case of death/incapacity)\n\n **Benefits:** Limited liability, separate legal entity\n\n **Restrictions:**\n Cannot add new shareholders\n Cannot issue shares to public\n Cannot do banking business\n Must convert to Pvt Ltd if member added\n\n OPC registration guide  299\n Full OPC setup  2,999",
    },
    escalate: false,
    relatedRules: ["co-opc-001"],
  },
  {
    id: "co-qa-004",
    triggerKeywords: ["company vs partnership", "pvt ltd vs firm", "which is better company or firm", "difference company firm"],
    question: "What is the difference between a company and a partnership firm?",
    irac: {
      issue: "How does a private limited company differ from a registered partnership?",
      rule: "Companies Act 1994 vs Partnership Act 1932: Key difference is legal status and liability. Company = separate legal entity with limited liability. Partnership = not separate, partners personally liable.",
      application: "Company can own property, sue, be sued in its own name. Partners are personally liable for firm debts  their personal assets at risk.",
      conclusion: "**Company vs Partnership:**\n\n| Feature | Pvt Ltd | Partnership |\n|---|---|---|\n| Legal entity | Separate  | Not separate  |\n| Liability | Limited  | Unlimited  |\n| Min members | 2 | 2 |\n| Max members | 50 | 20 |\n| Registration | Mandatory | Optional |\n| Tax rate | 27.5% | Slab rates |\n| Continuity | Perpetual | Can dissolve |\n\n**Use company:** Investment risk, limited liability needed.\n**Use firm:** Simple business, low compliance cost.\n\n Business structure guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001", "co-partnership-001"],
  },
  {
    id: "co-qa-005",
    triggerKeywords: ["register partnership", "firm registration", "partnership deed registration", "register firm"],
    question: "How do I register a partnership firm?",
    irac: {
      issue: "Process for registering a partnership with RJSC?",
      rule: "Partnership Act 1932 + RJSC: Optional but strongly recommended  unregistered firm cannot file lawsuit. Apply at RJSC with partnership deed, Form I, NIDs of partners, TIN.",
      application: "Without registration, firm cannot sue third parties or partners in court. Registration cost is minimal  always worth registering.",
      conclusion: "**Partnership registration  RJSC:**\n\n**Documents:**\n Partnership deed (signed by all partners)\n Form I (application)\n NID of all partners\n Firm TIN + trade licence\n Passport photos\n\n**Process:**\n1. Prepare + sign partnership deed\n2. Apply at RJSC (online or physical)\n3. Pay fee\n4. Certificate issued in 7-10 days\n\n**Without registration:** Cannot sue in court.\n\n Partnership docs  199\n Partnership deed drafting  2,999",
    },
    escalate: false,
    relatedRules: ["co-partnership-001"],
  },
  {
    id: "co-qa-006",
    triggerKeywords: ["foreign company register", "branch office bangladesh", "liaison office", "foreign branch bd"],
    question: "How does a foreign company register in Bangladesh?",
    irac: {
      issue: "How can a foreign company establish legal presence in Bangladesh?",
      rule: "Companies Act 1994, S.379-386 + Foreign Company Rules 2018: Must register with RJSC within 30 days of establishing Bangladesh presence. Branch Office: full commerce. Liaison Office: promotion only. Subsidiary: new BD company with foreign ownership.",
      application: "UK company opening Dhaka office to sell products  Branch Office (RJSC + BIDA). Foreign company setting up marketing coordination only  Liaison Office. Most flexible: Subsidiary (new BD Pvt Ltd with foreign shareholder).",
      conclusion: "**Foreign company options:**\n\n**Branch Office:**\n Full commercial activity\n Register: RJSC + BIDA\n Tax: 37.5-40%\n\n**Liaison Office:**\n Promotion/coordination only\n No revenue allowed\n Register: RJSC + BIDA\n\n**Subsidiary (Pvt Ltd):**\n Most flexible\n Standard 27.5% tax\n Foreign shareholder up to 100% in most sectors\n\n Foreign company docs  399\n Full guide  4,999",
    },
    escalate: true,
    escalateReason: "Foreign company registration needs RJSC + BIDA + Bangladesh Bank coordination. WhatsApp NLC.",
    relatedRules: ["co-foreign-001"],
  },
  {
    id: "co-qa-007",
    triggerKeywords: ["add director", "change director", "remove director", "director appointment removal"],
    question: "How do I add or remove a director?",
    irac: {
      issue: "Process for appointing or removing a director?",
      rule: "Companies Act 1994, S.92-107: Director appointment by shareholders at general meeting. File Form XII with RJSC within 28 days of change. Removal: ordinary resolution with special notice to director.",
      application: "Add director: Board meeting  EGM approval if required  Form XII at RJSC within 28 days  Register updated. Late filing attracts penalty.",
      conclusion: "**Director change  process:**\n\n1. Board meeting  resolution\n2. EGM if shareholders' approval needed\n3. File **Form XII** at RJSC within **28 days**\n4. Pay filing fee\n\n**New director documents:**\n NID/Passport\n TIN\n Consent form (Form XII)\n Photograph\n\n**Late filing:** BDT 1,000 + daily penalty\n\n Director change docs  199\n Corporate change guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-008",
    triggerKeywords: ["change company address", "registered office change", "rjsc address", "company address update"],
    question: "How do I change my company's registered address?",
    irac: {
      issue: "Process for changing registered office address with RJSC?",
      rule: "Companies Act 1994, S.77: Same district: board resolution + Form VI within 30 days. Different district: special resolution (75% shareholders) + EGM + RJSC approval.",
      application: "Moving within Dhaka: Board resolution + Form VI + new utility bill  RJSC updates records. Moving Dhaka to Chattogram: more complex EGM + newspaper advertisement required.",
      conclusion: "**Address change:**\n\n**Within same district:**\n1. Board resolution\n2. File Form VI within 30 days\n3. Attach: new lease/utility bill\n4. Fee: BDT 500-2,000\n\n**Different district:**\n1. EGM  75% shareholder resolution\n2. Newspaper advertisement\n3. RJSC approval\n\n Address change docs  199\n Full guide  1,999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-009",
    triggerKeywords: ["annual return company", "agm rjsc", "annual compliance company", "company annual filing"],
    question: "What are the annual compliance requirements for a company?",
    irac: {
      issue: "What annual filings must a private limited company make?",
      rule: "Companies Act 1994, S.192: AGM within 120 days of financial year end. Annual return to RJSC within 21 days of AGM. Audited financials required. Income tax return separately to NBR by 15 July.",
      application: "FY ends 31 Dec  AGM by 30 April  Annual return by 21 May  Tax return by 15 July  VAT monthly throughout.",
      conclusion: "**Annual compliance calendar:**\n\n| Deadline | Obligation |\n|---|---|\n| 120 days after FY | Hold AGM |\n| 21 days after AGM | RJSC annual return |\n| 15 July | Income tax return (NBR) |\n| 15th monthly | VAT return (if registered) |\n| Annually | Renew trade licence |\n\n**AGM agenda:**\n Approve annual accounts\n Appoint/re-appoint auditor\n Declare dividend (if any)\n Director re-election\n\n**Non-compliance:** Penalty + possible strike-off\n\n Annual compliance guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-010",
    triggerKeywords: ["increase capital", "increase authorized capital", "capital increase", "authorized capital"],
    question: "How do I increase my company's share capital?",
    irac: {
      issue: "Process for increasing authorized and paid-up capital?",
      rule: "Companies Act 1994, S.54-56: Requires EGM special resolution (75% shareholders), MOA amendment (Clause V), filing Form V + amended MOA at RJSC, payment of incremental fees.",
      application: "Current authorized capital BDT 10 lakh, want BDT 50 lakh: EGM  special resolution  amend MOA  Form V at RJSC  pay incremental fees.",
      conclusion: "**Capital increase steps:**\n\n1. Check Articles (must permit increase)\n2. EGM  special resolution (75%)\n3. Amend MOA Clause V\n4. File at RJSC:\n    Form V (increase notice)\n    Amended MOA\n    EGM minutes\n5. Pay incremental RJSC fee\n\n**Then issue shares:** Pass allotment resolution + Form IV within 60 days\n\n Capital increase guide  2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-011",
    triggerKeywords: ["transfer shares", "sell shares", "share transfer procedure", "shares sell"],
    question: "How do I transfer shares in a private limited company?",
    irac: {
      issue: "Legal process for transferring shares in a Bangladesh Pvt Ltd?",
      rule: "Companies Act 1994, S.38: Private company shares restricted by Articles. Typically: right of pre-emption (existing shareholders first right), board approval required. Transfer instrument + share certificate needed. Stamp duty 1.5% of value.",
      application: "Shareholder A sells to outsider B: first offer to existing shareholders  if no takers in 30 days  offer to B  Board approval  execute transfer form  update register  new certificate.",
      conclusion: "**Share transfer:**\n\n1. Check Articles for restrictions\n2. Offer to existing shareholders first (pre-emption)\n3. If no takers  offer to outsider\n4. Board approval\n5. Execute share transfer form\n6. **Stamp duty:** 1.5% of share value\n7. Update share register\n8. Issue new certificate\n9. File Form IV at RJSC within 60 days\n\n Share transfer guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-012",
    triggerKeywords: ["dissolve company", "close company", "wind up company", "company dissolution"],
    question: "How do I close or dissolve a company?",
    irac: {
      issue: "Process for voluntarily winding up a company?",
      rule: "Companies Act 1994, S.234-283: Voluntary winding up requires 75% shareholder resolution, liquidator appointment, newspaper advertisement, debt settlement, asset distribution, final RJSC return. Tax clearance from NBR required.",
      application: "Dormant company with no assets/liabilities: apply to RJSC for strike-off (simpler route). Active company with creditors: full voluntary winding up process.",
      conclusion: "**Company dissolution options:**\n\n**Option 1  Voluntary Winding Up:**\n1. 75% shareholder special resolution\n2. Appoint liquidator\n3. Newspaper advertisement\n4. Settle all debts\n5. Distribute remaining assets\n6. RJSC final return\n\n**Option 2  Strike Off (dormant):**\n1. Apply to RJSC (no assets/liabilities)\n2. RJSC issues show cause\n3. Strike off completed\n\n**Must have:** Tax clearance from NBR first\n**Time:** 6 months  2 years\n\n Dissolution guide  3,999",
    },
    escalate: true,
    escalateReason: "Company dissolution requires specialist guidance. WhatsApp NLC.",
    relatedRules: [],
  },
  {
    id: "co-qa-013",
    triggerKeywords: ["shareholder dispute", "minority shareholder", "oppression mismanagement", "director conflict"],
    question: "What can a minority shareholder do against mismanagement?",
    irac: {
      issue: "Remedies for minority shareholder against oppression or mismanagement?",
      rule: "Companies Act 1994, S.233-234: Minority (min 10% shareholding or 100 members) can petition High Court for relief against oppression/mismanagement. Court can: regulate affairs, compel dividends, order buy-out at fair value, or wind up.",
      application: "Majority directors paying excessive salaries, excluding minority from dividends, hiding accounts = oppression. File petition in High Court Division.",
      conclusion: "**Minority shareholder remedies:**\n\n**Threshold:** 10% shareholding or 100 members\n\n**Court can order:**\n Regulate company affairs\n Compel dividend payment\n Buy out minority at fair value\n Change board\n Wind up (last resort)\n\n**Steps:**\n1. Send legal notice to majority/board\n2. Demand accounts inspection\n3. File petition  High Court Division\n\n Requires specialist advocate.\n\n Shareholder rights guide  2,999",
    },
    escalate: true,
    escalateReason: "Shareholder disputes need High Court petition. WhatsApp NLC.",
    relatedRules: [],
  },
  {
    id: "co-qa-014",
    triggerKeywords: ["trade licence", "business licence", "trade license renewal", "trade licence dhaka"],
    question: "How do I get and renew a trade licence?",
    irac: {
      issue: "Process for obtaining trade licence from city corporation or municipality?",
      rule: "Local Government (City Corporation) Act 2009: Trade licence mandatory for all businesses. Issued by local authority (city corporation/municipality/union parishad). TIN mandatory for city corporation licences. Annual renewal due by 30 June.",
      application: "Apply at ward office of city corporation where business is located. New licence: NID, TIN, lease agreement, photos. Inspector may visit. Renewal: previous year licence + fees.",
      conclusion: "**Trade licence:**\n\n**New application documents:**\n NID of owner/director\n TIN certificate\n Lease agreement\n Photograph\n MOA/incorporation cert (for company)\n\n**Process:** Apply  inspector visits  pay fee  licence in 7-30 days\n\n**Renewal deadline:** 30 June each year\n**Late renewal surcharge:** 25% extra\n\n Trade licence docs  99\n Trade licence guide  999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-015",
    triggerKeywords: ["rjsc certified copy", "company documents copy", "rjsc documents", "certificate copy"],
    question: "How do I get certified copies of company documents from RJSC?",
    irac: {
      issue: "How to obtain certified copies of RJSC company documents?",
      rule: "Companies Act 1994, S.200: RJSC maintains public register. Anyone can inspect or get certified copies. Available online at roc.gov.bd (digitised documents) or physically at RJSC Dhaka.",
      application: "roc.gov.bd  search company  download available documents (if digitised). Fee: BDT 100-500 per document. Physical: visit RJSC, pay counter fee, collect same/next day.",
      conclusion: "**Get RJSC documents:**\n\n**Online (roc.gov.bd):**\n Create account  search company  download\n Pay fee online\n\n**Physical (RJSC Dhaka):**\n Application letter + payment\n Collect same/next day\n\n**Available:** Certificate of Incorporation, MOA, AOA, annual returns, director list, address\n\n RJSC document guide  99",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-016",
    triggerKeywords: ["what is moa aoa", "memorandum articles", "memorandum association", "articles association"],
    question: "What are MOA and AOA and why are they important?",
    irac: {
      issue: "What are the Memorandum of Association and Articles of Association?",
      rule: "Companies Act 1994, S.6-11: MOA (Memorandum of Association) = company's constitution  defines name, objects, capital, liability. AOA (Articles of Association) = internal rules  governs directors, meetings, shares, dividends. Both filed at RJSC on incorporation.",
      application: "MOA defines what business the company can do. AOA defines how it governs itself internally. A company cannot act outside its MOA objects (ultra vires).",
      conclusion: "**MOA vs AOA:**\n\n**MOA (Memorandum):**\n Company name\n Registered office location\n Objects (what business it can do)\n Authorized capital\n Members' liability (limited)\n\n**AOA (Articles):**\n Share transfer rules\n Director powers and duties\n Meeting procedures\n Dividend rules\n Voting rights\n\n**Important:** Company cannot do business outside MOA objects. Amend MOA if expanding business.\n\n MOA + AOA drafting  4,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-017",
    triggerKeywords: ["bida registration", "foreign investment", "bida licence", "foreign investor"],
    question: "What is BIDA registration and when do I need it?",
    irac: {
      issue: "When is BIDA (Bangladesh Investment Development Authority) registration required?",
      rule: "BIDA Act 2016 + Investment Policy 2021: BIDA registration required for: foreign investment in Bangladesh, importing technology, bringing foreign experts, repatriating profits. One-Stop Service (OSS) provides integrated services for investors.",
      application: "Foreign investor forming a BD Pvt Ltd company: needs BIDA registration to legally bring in foreign capital, hire foreign employees, and repatriate profits. Domestic-only companies: BIDA not required (except for specific sectors).",
      conclusion: "**BIDA registration needed for:**\n Foreign investment in Bangladesh\n Foreign shareholder in BD company\n Bringing foreign experts/employees\n Profit repatriation abroad\n Branch/liaison office of foreign company\n\n**BIDA One-Stop Service (OSS):**\n Single window for multiple approvals\n Work permits, tax exemptions, utility connections\n Apply: bida.gov.bd\n\n BIDA registration docs  399\n Foreign investment guide  4,999",
    },
    escalate: true,
    escalateReason: "Foreign investment and BIDA registration complex. WhatsApp NLC.",
    relatedRules: ["co-foreign-001"],
  },
  {
    id: "co-qa-018",
    triggerKeywords: ["company bank account", "corporate bank account", "open company account", "business account"],
    question: "How do I open a bank account for my company?",
    irac: {
      issue: "What documents are required to open a corporate bank account in Bangladesh?",
      rule: "Bangladesh Bank KYC Guidelines + Bank-specific requirements: All directors must visit bank (or video KYC). Company account requires: Certificate of Incorporation, MOA/AOA, board resolution authorising account opening and signatories, TIN of company and directors, NID of all directors.",
      application: "After receiving Certificate of Incorporation from RJSC: prepare board resolution for account opening  all directors visit bank  submit documents  account opened in 3-7 working days.",
      conclusion: "**Company bank account  documents:**\n\n Certificate of Incorporation\n MOA and AOA\n Board resolution (account opening + signatories)\n TIN certificate (company)\n NID + TIN of all directors\n Trade licence\n Recent utility bill (registered office)\n\n**Process:**\n1. All directors visit bank (in-person KYC)\n2. Submit documents\n3. Account opened in 3-7 days\n\n Bank account opening docs  99",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-019",
    triggerKeywords: ["company not doing business", "dormant company", "dormant rjsc", "company no activity"],
    question: "What happens if my company is not doing any business?",
    irac: {
      issue: "What are the obligations for a dormant or inactive company?",
      rule: "Companies Act 1994: Even dormant companies must file annual returns with RJSC and income tax returns with NBR. Non-filing for multiple years  RJSC sends strike-off notice  company name removed from register if no response.",
      application: "Company formed but no business: still must file nil returns annually at RJSC and NBR. Failing to file = accumulating penalties + risk of strike-off. Better to formally close if not needed.",
      conclusion: "**Dormant company  still must:**\n File annual return at RJSC (even nil)\n File income tax return at NBR\n Pay minimum tax (BDT 3,000-5,000)\n Maintain registered office\n\n**Consequences of non-filing:**\n Penalty accumulation\n RJSC strike-off notice\n Company struck off register if no response\n\n**Better option:** Formally dissolve company if not needed.\n\n Dormant company guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-020",
    triggerKeywords: ["change company name", "rename company", "company name change rjsc"],
    question: "How do I change my company's name?",
    irac: {
      issue: "Process for changing a company's registered name?",
      rule: "Companies Act 1994, S.13: Name change requires: special resolution (75% shareholders at EGM), ROC approval/new name clearance, amended Certificate of Incorporation. File Form II + amended MOA at RJSC.",
      application: "Current name 'ABC Trading Ltd'  want 'XYZ Solutions Ltd': get new name clearance  EGM special resolution  file Form II + amended MOA  new Certificate of Incorporation issued.",
      conclusion: "**Company name change:**\n\n1. Get new name clearance from RJSC\n2. Hold EGM  75% special resolution\n3. File at RJSC:\n    Form II (change of name)\n    Amended MOA\n    EGM minutes\n4. Pay fee\n5. New Certificate of Incorporation issued\n\n**After name change:**\n Update all letterheads, seals\n Notify bank, NBR, trade licence authority\n Update TIN records\n\n Name change guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-021",
    triggerKeywords: ["company secretary", "company law compliant", "cs officer", "company secretary requirement"],
    question: "Does my company need a Company Secretary?",
    irac: {
      issue: "When is a Company Secretary mandatory under Bangladesh company law?",
      rule: "Companies Act 1994, S.161: Public limited companies with paid-up capital above BDT 2 crore must appoint a qualified Company Secretary. Private limited companies: no mandatory requirement, but good practice. Listed companies: Company Secretary mandatory (BSEC rules).",
      application: "Small private limited company: no legal requirement for Company Secretary. Large private company or listed company: mandatory. Company Secretary handles RJSC filings, board minutes, compliance calendar.",
      conclusion: "**Company Secretary requirement:**\n\n**Mandatory:**\n Public limited company (paid-up > BDT 2 crore)\n Listed companies (BSEC rule)\n\n**Not mandatory but recommended:**\n Large private limited companies\n Companies with complex compliance\n\n**What CS does:**\n RJSC filings and returns\n Board/AGM minutes\n Compliance calendar\n Shareholder communications\n\n Compliance officer guide  999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-022",
    triggerKeywords: ["dividend declaration", "declare dividend", "dividend pay company", "dividend procedure"],
    question: "How does a company declare and pay dividends?",
    irac: {
      issue: "What is the process for declaring and paying dividends in a Bangladesh company?",
      rule: "Companies Act 1994, S.137: Dividends declared by shareholders at AGM based on board recommendation. Board recommends dividend from distributable profits (after tax). Interim dividend can be declared by board between AGMs. WHT on dividend: 10% (listed), 20% (unlisted) deducted before payment.",
      application: "Company has BDT 50 lakh distributable profit. Board recommends 30% dividend on BDT 10 lakh paid-up capital = BDT 3 lakh total dividend. AGM approves. Deduct WHT 20% = BDT 60,000 to NBR. Pay net BDT 2,40,000 to shareholders.",
      conclusion: "**Dividend declaration process:**\n\n1. Board recommends dividend amount\n2. AGM approves (ordinary resolution)\n3. Set payment date (max 42 days after declaration)\n4. Deduct WHT (10% listed / 20% unlisted)\n5. Deposit WHT with NBR within 7 days\n6. Pay net dividend to shareholders\n7. Update dividend register\n\n**No dividends** if: accumulated losses, insufficient profits\n\n Dividend procedure guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-023",
    triggerKeywords: ["company audit", "auditor appointment", "company auditor", "audit requirement"],
    question: "When does a company need an auditor?",
    irac: {
      issue: "What are the audit requirements for companies under Companies Act 1994?",
      rule: "Companies Act 1994, S.210-213: Every company with paid-up capital above BDT 1 crore must have audited financial statements. Auditor appointed at AGM. Must be a Chartered Accountant (CA) registered with ICAB. Auditor files report with annual return.",
      application: "Small company with paid-up capital BDT 50,000: no mandatory audit. Company with BDT 50 lakh paid-up capital: mandatory annual audit by CA firm. Banks require audited accounts for loans regardless of audit requirement.",
      conclusion: "**Audit requirements:**\n\n**Mandatory audit:** Paid-up capital > BDT 1 crore\n**Auditor:** Chartered Accountant (CA) from ICAB\n**Appointment:** At AGM each year\n**Report:** Filed with RJSC annual return\n\n**Even if not mandatory:**\n Banks require for loans\n NBR may require for tax audit\n Foreign investors require for due diligence\n\n Audit requirements guide  999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-024",
    triggerKeywords: ["company loan", "company borrowing", "company bank loan", "business loan"],
    question: "Can a company take a bank loan and what documents are needed?",
    irac: {
      issue: "What documentation does a company need to take a bank loan?",
      rule: "Bank Company Act 1991 + Bangladesh Bank guidelines + Companies Act 1994: Companies can borrow from banks by executing security documents (mortgage, charge). Board resolution authorising borrowing and appointing authorised signatory required. Security: land mortgage, hypothecation of assets, personal guarantee of directors.",
      application: "Company wants BDT 1 crore loan: Board resolution  apply at bank  bank due diligence  execute security documents  loan disbursed. Directors' personal guarantee often required for small/medium companies.",
      conclusion: "**Company bank loan  documents:**\n\n Certificate of Incorporation\n MOA/AOA\n Board resolution (borrowing authority)\n Audited financial statements (2-3 years)\n TIN + trade licence\n NID of all directors\n Security documents (mortgage/hypothecation)\n Personal guarantee of directors\n Tax return acknowledgements\n\n**Types of security accepted:**\n Land/property mortgage\n Hypothecation of stock/equipment\n FDR pledge\n\n Company loan guide  1,999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-025",
    triggerKeywords: ["company penalty rjsc", "rjsc fine", "non-filing penalty", "company compliance penalty"],
    question: "What are the penalties for non-compliance with RJSC?",
    irac: {
      issue: "What penalties apply for failure to comply with RJSC filing requirements?",
      rule: "Companies Act 1994: Non-filing annual return: BDT 1,000 per month per director. Non-holding AGM: BDT 5,000 per director per day. Late filing of other forms: BDT 1,000 + additional per day. Continued defaults: RJSC can strike off company.",
      application: "Company fails to file annual return for 2 years with 2 directors: BDT 1,000  24 months  2 directors = BDT 48,000 penalty (just for annual return). Penalties accumulate quickly.",
      conclusion: "**RJSC non-compliance penalties:**\n\n| Default | Penalty |\n|---|---|\n| Annual return late | BDT 1,000/month/director |\n| AGM not held | BDT 5,000/day/director |\n| Late Form filing | BDT 1,000 + daily |\n| False statement | Up to BDT 50,000 |\n| Continued defaults | Strike-off |\n\n Penalties accumulate rapidly  file even if late.\n\n RJSC compliance guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-annual-001"],
  },
  {
    id: "co-qa-026",
    triggerKeywords: ["merger acquisition", "company merger", "amalgamation", "takeover bangladesh"],
    question: "How do companies merge or get acquired in Bangladesh?",
    irac: {
      issue: "What is the legal process for company mergers and acquisitions in Bangladesh?",
      rule: "Companies Act 1994, S.228-233: Merger (amalgamation) requires: scheme of arrangement approved by shareholders (75%), creditor approval, High Court sanction. Share acquisition: buy majority shares from existing shareholders  simpler, no court approval needed.",
      application: "Full merger: complex court process (6-18 months). Share acquisition (takeover): buy shares from shareholders  much faster  practical for most M&A in Bangladesh.",
      conclusion: "**M&A options:**\n\n**Share acquisition (faster):**\n Buy majority shares from shareholders\n No court approval needed\n Share transfer process + RJSC Form IV\n Time: 1-3 months\n\n**Merger/Amalgamation (formal):**\n Scheme of arrangement\n 75% shareholder + creditor approval\n High Court sanction\n Time: 6-18 months\n\n Engage M&A specialist for due diligence.\n\n M&A guide  4,999",
    },
    escalate: true,
    escalateReason: "Mergers and acquisitions require specialist legal guidance. WhatsApp NLC.",
    relatedRules: [],
  },
  {
    id: "co-qa-027",
    triggerKeywords: ["epz company", "sez", "export processing zone", "beza"],
    question: "Can I register a company in EPZ or SEZ?",
    irac: {
      issue: "What are the benefits and process for registering a company in Bangladesh EPZ or SEZ?",
      rule: "Bangladesh Export Processing Zones Authority (BEPZA) Act 1980 + Bangladesh Economic Zones Act 2010: Companies in EPZ and SEZ receive special tax exemptions, duty-free imports, and regulatory facilitation. BEPZA/BEZA approvals required instead of standard RJSC in some cases.",
      application: "Manufacturing company wanting to export 100%: EPZ company gets 100% duty-free import of raw materials, 10-year tax holiday, no work permit fee for foreign employees.",
      conclusion: "**EPZ/SEZ company benefits:**\n\n **Tax holiday:** 10 years (Type A  100% export)\n **Duty-free imports:** Raw materials, machinery\n **No work permit fee:** Foreign workers\n **VAT/customs exemption**\n **100% foreign ownership allowed**\n\n**Apply to:**\n EPZ: BEPZA (bepza.gov.bd)\n SEZ: BEZA (beza.gov.bd)\n\n EPZ/SEZ registration guide  4,999",
    },
    escalate: true,
    escalateReason: "EPZ/SEZ registration is complex. WhatsApp NLC for specialist guidance.",
    relatedRules: [],
  },
  {
    id: "co-qa-028",
    triggerKeywords: ["company striking off", "struck off company", "restore struck company", "company removed register"],
    question: "My company was struck off by RJSC  can I restore it?",
    irac: {
      issue: "Can a company struck off the RJSC register be restored?",
      rule: "Companies Act 1994, S.396: A company struck off the register can be restored within 20 years by applying to High Court. Court orders restoration if: company was carrying on business at time of strike-off, or it is just and equitable to restore. All outstanding returns and penalties must be paid.",
      application: "Company struck off for non-filing: apply to High Court Division  pay all outstanding filing fees and penalties  court orders RJSC to restore  company back on register.",
      conclusion: "**Restore struck-off company:**\n\n1. Apply to High Court Division\n2. Show company was active OR just/equitable to restore\n3. Pay ALL outstanding RJSC fees + penalties\n4. File all overdue annual returns\n5. Court order  RJSC restores company\n\n**Time limit:** 20 years from strike-off\n\n All penalties and back-filings must be cleared.\n\n Restoration guide  2,999",
    },
    escalate: true,
    escalateReason: "Company restoration requires High Court application. WhatsApp NLC.",
    relatedRules: [],
  },
  {
    id: "co-qa-029",
    triggerKeywords: ["ngo registration", "society registration", "society act", "nonprofit registration"],
    question: "How do I register an NGO or society in Bangladesh?",
    irac: {
      issue: "What are the options for registering a non-profit organization in Bangladesh?",
      rule: "Societies Registration Act 1860 + NGO Affairs Bureau Rules + Voluntary Social Welfare Agencies Ordinance 1961: NGO options: (1) Society under Societies Registration Act at District Commissioner's office, (2) Trust under Trust Act 1882, (3) Company limited by guarantee under Companies Act 1994, (4) Registration with NGO Affairs Bureau for foreign-funded NGOs.",
      application: "Local community NGO: register as Society with DC office. NGO receiving foreign grants: mandatory registration with NGO Affairs Bureau (Prime Minister's Office) for foreign funding permission.",
      conclusion: "**NGO/Society registration options:**\n\n**Society (Societies Act 1860):**\n Register at DC office (district)\n Min 7 members\n General/charitable purposes\n\n**Trust (Trust Act 1882):**\n Register at Sub-Registry office\n Specific charitable purpose\n\n**NGO Bureau (foreign-funded):**\n Mandatory for foreign grants\n Apply: ngoab.gov.bd\n Annual activity report required\n\n NGO registration docs  299\n NGO setup guide  2,999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-030",
    triggerKeywords: ["startup registration", "startup company", "startup bangladesh", "new business register"],
    question: "What is the easiest way to legally register a startup in Bangladesh?",
    irac: {
      issue: "What is the fastest and simplest legal structure for a startup in Bangladesh?",
      rule: "Companies Act 1994 + OPC Rules 2020 + Bangladesh Startup Policy 2021: Options for startups: OPC (solo founder, limited liability), Private Limited (2+ founders), Proprietorship (sole trader, no RJSC needed). Bangladesh Startup Policy 2021 provides startup ecosystem support through ICT Division and startup.gov.bd.",
      application: "Solo tech founder: OPC is fastest (2 weeks, full online, limited liability). Two co-founders: Private Limited (3 weeks). Solo with no need for limited liability and minimal compliance: Proprietorship (trade licence only, no RJSC needed).",
      conclusion: "**Startup registration options:**\n\n**Fastest (solo):** OPC\n 2 weeks, full online at roc.gov.bd\n Limited liability\n Single TIN + NID needed\n\n**Two+ founders:** Private Limited\n 3 weeks at roc.gov.bd\n Industry standard for investor funding\n\n**No RJSC needed:** Sole Proprietorship\n Just trade licence\n No limited liability\n Simplest but least protection\n\n**Startup support:** startup.gov.bd (ICT Division)\n\n Startup registration guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001", "co-opc-001"],
  },
  {
    id: "co-qa-031",
    triggerKeywords: ["company resolution", "board resolution", "board minutes", "resolution pass"],
    question: "What is a board resolution and when is it needed?",
    irac: {
      issue: "When must a company pass a board resolution and what are the requirements?",
      rule: "Companies Act 1994 + Articles of Association: Board resolutions are formal decisions by directors at a board meeting. Required for: opening bank accounts, authorising signatories, taking loans, major contracts, appointing staff, RJSC filings. Quorum requirement in AOA (usually majority of directors).",
      application: "Company wants to open bank account: Board resolution must authorise which directors can sign cheques. Company takes loan: Board resolution authorises the borrowing and security creation.",
      conclusion: "**Board resolution needed for:**\n\n Opening/changing bank account\n Authorising signatories\n Taking loans or creating security\n Major contracts above a threshold\n RJSC form filings\n Appointing key staff\n Dividend recommendation\n\n**Format:** Date, attendance, resolution text, signatures\n**Quorum:** Usually majority directors (per AOA)\n**Must be:** Recorded in Board Minutes Book\n\n Board resolution templates  999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-032",
    triggerKeywords: ["company seal", "common seal", "company stamp", "seal requirement"],
    question: "Does my company need a common seal?",
    irac: {
      issue: "Is a common seal mandatory for a Bangladesh company?",
      rule: "Companies Act 1994, S.40: Every company must have a common seal with its name engraved on it. The seal must be affixed to share certificates, debentures, powers of attorney, and certain formal documents. Seal affixed in presence of at least one director and countersigned.",
      application: "Company must get a metal seal made with company name. Affix on share certificates, property deed powers of attorney. Modern practice: many documents now use authorised signatures instead of seal for routine matters.",
      conclusion: "**Company common seal:**\n\n**Mandatory:** Yes  must have company name engraved\n\n**Required on:**\n Share certificates\n Debentures\n Powers of attorney\n Formal property documents\n\n**Affixing:** In presence of 1+ director, countersigned\n\n**Get made at:** Any rubber/metal stamp maker\n**Cost:** BDT 500-2,000\n\n Company formation checklist  199",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-033",
    triggerKeywords: ["company contract", "director contract", "director service agreement", "managing director"],
    question: "Can a director be an employee of the company?",
    irac: {
      issue: "Can directors also be employed by the company and receive salary?",
      rule: "Companies Act 1994, S.93-95: A director can also serve as Managing Director (MD) or executive director under a service contract. Service contract must be approved by shareholders if over 5 years. Salary of executive directors is an allowable expense for the company (deductible for tax). Non-executive directors can receive only fees approved at AGM.",
      application: "Company has 2 directors. Both also work full-time for the company as CEO and CFO. Both receive salary under service contracts. Salary = deductible expense for company. Must be approved by board and disclosed to shareholders.",
      conclusion: "**Director as employee:**\n\n **Allowed:** Director can be employed (executive director/MD)\n **Salary:** Deductible company expense\n **Service contract:** Up to 5 years (shareholder approval for longer)\n\n**Non-executive director:**\n Receives sitting fees only (not salary)\n Fees approved at AGM\n\n**Disclosure:** Salary of directors disclosed in annual report/accounts\n\n Director service contract  2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-034",
    triggerKeywords: ["intellectual property company", "patent trademark", "trademark registration", "copyright company"],
    question: "How does a company protect its brand and intellectual property?",
    irac: {
      issue: "What IP protections are available for companies in Bangladesh?",
      rule: "Trademarks Act 2009: Register trademark with Department of Patents, Designs and Trademarks (DPDT). Patents and Designs Act 2022: Register patents and industrial designs with DPDT. Copyright Act 2000: Automatic on creation, optional registration with Copyright Office. Company name registration at RJSC does NOT protect the brand  separate trademark registration needed.",
      application: "Company 'TechBD Ltd' incorporated at RJSC: company name registered. But brand name 'TechBD' is not protected until trademark registered separately at DPDT. Another company could use the same brand name.",
      conclusion: "**IP protection for companies:**\n\n**Trademark (brand name/logo):**\n Register at DPDT (dpdt.gov.bd)\n Class-based registration (45 classes)\n Valid for 10 years, renewable\n Cost: BDT 3,000-10,000 per class\n Time: 12-18 months\n\n**Patent (invention):**\n Register at DPDT\n Valid 20 years\n Must be novel, inventive, useful\n\n**Copyright (software, content):**\n Automatic on creation\n Optional registration at Copyright Office\n Valid: author's life + 60 years\n\n** CRITICAL:** RJSC company name  trademark protection. Register trademark separately!\n\n IP protection guide  2,999\n Trademark filing  4,999",
    },
    escalate: false,
    relatedRules: [],
  },
  //  ENRICHED SECTION: QA 035-050 
  {
    id: "co-qa-035",
    triggerKeywords: ["public limited company", "plc registration", "public company", "ipo company"],
    question: "How do I register a public limited company in Bangladesh?",
    irac: {
      issue: "What is the process and requirements for incorporating a public limited company?",
      rule: "Companies Act 1994, S.10-12: Minimum 7 shareholders, minimum 3 directors, no maximum shareholders. Name must include 'Public Limited Company' or 'PLC'. Cannot commence business without Certificate of Commencement of Business (after minimum subscription). Must file prospectus or statement in lieu of prospectus with RJSC.",
      application: "Entrepreneur planning to raise capital from public through IPO: must first incorporate as PLC  meet BSEC requirements  file prospectus  get BSEC approval  IPO  list on stock exchange. Cannot start business until minimum subscription received.",
      conclusion: "**Public Limited Company (PLC) registration:**\n\n**Requirements:**\n Minimum 7 shareholders (no max)\n Minimum 3 directors\n Name: 'PLC' or 'Public Limited Company'\n\n**Steps:**\n1. Name clearance (roc.gov.bd)\n2. Prepare MOA + AOA\n3. Online application with Forms I, VI, XII\n4. Certificate of Incorporation\n5. **Certificate of Commencement**  must obtain before starting business\n\n**Additional requirements:**\n Prospectus or statement in lieu\n Minimum subscription of shares\n BSEC approval for IPO\n\n**Why PLC:** To raise capital from public, list on stock exchange\n\n Public company compliance is significantly more complex and expensive.\n\n PLC registration guide  4,999",
    },
    escalate: true,
    escalateReason: "Public company and IPO requirements need BSEC coordination. WhatsApp NLC.",
    relatedRules: ["co-pub-001"],
  },
  {
    id: "co-qa-036",
    triggerKeywords: ["director duties", "fiduciary duty", "director responsibility", "director breach duty"],
    question: "What are the legal duties of a company director in Bangladesh?",
    irac: {
      issue: "What fiduciary and statutory duties do directors owe to the company?",
      rule: "Companies Act 1994, S.140-147: Directors owe fiduciary duties: act in good faith, exercise care and skill, avoid conflict of interest, not make secret profit, not misuse company information, disclose interest in contracts. Breach: liable to account for profits, compensate company, criminal penalty up to BDT 50,000 and/or 2 years imprisonment for fraud.",
      application: "Director starts a competing business using company's supplier contacts: this is a clear breach of fiduciary duty  misappropriation of business opportunity. Company can sue for all profits earned by the competing business.",
      conclusion: "**Director duties:**\n\n**Fiduciary duties:**\n Act in good faith for company's benefit\n Exercise reasonable care, skill, diligence\n Avoid conflict of interest\n Not make secret profits\n Not misuse confidential information\n Disclose personal interest in contracts\n\n**Statutory duties:**\n Ensure proper accounts maintained\n File returns on time\n Not fraudulently incur debt\n Call meetings as required\n\n**Breach consequences:**\n Account for all profits made\n Compensate company for losses\n Criminal: up to BDT 50,000 fine + 2 years imprisonment\n Disqualification from directorship\n\n Director duties guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-director-001"],
  },
  {
    id: "co-qa-037",
    triggerKeywords: ["board meeting", "board meeting notice", "board meeting quorum", "board minutes"],
    question: "How do I conduct a valid board meeting?",
    irac: {
      issue: "What are the legal requirements for a valid board meeting under Bangladesh company law?",
      rule: "Companies Act 1994, S.93 + AOA: Minimum one board meeting per quarter (4 per year). Notice: 7 days (unless AOA allows shorter). Quorum: as per AOA, typically 2 directors or 1/3rd of total directors, whichever is higher. Minutes must be recorded in Minutes Book within 30 days. Resolutions signed by chair of that meeting.",
      application: "Company has 5 directors, AOA requires quorum of 2. Notice sent 7 days before  3 directors attend  quorum met  meeting valid. Resolution passed 3-0. Minutes recorded and signed.",
      conclusion: "**Board meeting requirements:**\n\n**Frequency:** Minimum 4 per year (one per quarter)\n**Notice:** 7 days (or as per AOA)\n**Quorum:** Per AOA (usually 2 or 1/3rd directors)\n\n**Valid meeting checklist:**\n1.  Proper notice sent to all directors\n2.  Quorum present\n3.  Agenda items discussed\n4.  Resolutions passed by majority\n5.  Minutes recorded in Minutes Book\n6.  Minutes signed by meeting chair within 30 days\n\n**Circulating resolution:**\n If all directors consent in writing = valid resolution\n No meeting needed\n Must be recorded in Minutes Book\n\n Board meeting templates  999",
    },
    escalate: false,
    relatedRules: ["co-meeting-001"],
  },
  {
    id: "co-qa-038",
    triggerKeywords: ["company mortgage", "charge registration", "property mortgage company", "form viii rjsc"],
    question: "How does a company register a mortgage or charge on its property?",
    irac: {
      issue: "What is the process for registering a charge created by a company?",
      rule: "Companies Act 1994, S.148-155: Any charge on company property (mortgage, hypothecation, pledge) must be registered with RJSC within 30 days of creation using Form VIII. Modification: Form VIII-A. Satisfaction (after repayment): Form IX. Unregistered charge is VOID against liquidator and any secured creditor  the lender loses priority in winding up.",
      application: "Company mortgages its factory land to bank for BDT 5 crore loan: must file Form VIII at RJSC within 30 days of executing the mortgage deed. If not filed and company goes into liquidation, bank's mortgage is void against liquidator  bank becomes unsecured creditor.",
      conclusion: "**Charge registration process:**\n\n**What needs registration:**\n Mortgage on immovable property\n Hypothecation of movable property/stock\n Pledge of book debts\n Charge on uncalled share capital\n Floating charge on assets\n\n**Forms:**\n **Form VIII**  Creation of charge (within 30 days)\n **Form VIII-A**  Modification of charge\n **Form IX**  Satisfaction of charge (after repayment)\n\n**CRITICAL WARNING:**\n Unregistered charge = VOID against liquidator and secured creditors\n Bank/lender loses security interest in winding up\n\n**Fee:** BDT 500-2,000\n\n Charge registration guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-charge-001"],
  },
  {
    id: "co-qa-039",
    triggerKeywords: ["fdi bangladesh", "foreign investment sectors", "100% foreign ownership", "restricted sectors bangladesh"],
    question: "In which sectors can foreigners invest 100% in Bangladesh?",
    irac: {
      issue: "What are the FDI rules regarding sector-wise foreign ownership in Bangladesh?",
      rule: "BIDA Act 2016 + Investment Policy 2021: 100% FDI allowed in most manufacturing and service sectors. Reserved (no FDI): defense, nuclear energy, security printing, reserved forestry. Restricted: banking (max 62%, needs BB approval), insurance (max 60%, needs IDRA approval), telecommunications (needs BTRC approval), airlines (needs CAAB approval). Profit and dividend repatriation permitted for FDI companies.",
      application: "Foreign investor wants to open a restaurant: 100% FDI allowed  form BD Pvt Ltd with 100% foreign shares, register with BIDA. Foreign investor wants to open a bank: max 62% foreign  needs Bangladesh Bank prior approval, local partners required for remaining 38%.",
      conclusion: "**FDI sector guide:**\n\n** 100% FDI allowed:**\n Manufacturing (garments, pharma, electronics)\n IT/software services\n Trading, import-export\n Real estate development\n Hospitality (hotels, restaurants)\n Healthcare (hospitals, clinics)\n Education (private institutions)\n Agro-processing\n Most service sectors\n\n** Restricted (needs regulator approval):**\n Banking  max 62% foreign (BB approval)\n Insurance  max 60% foreign (IDRA approval)\n Telecommunications  BTRC approval\n Airlines  CAAB approval\n Media/broadcasting  limited FDI\n\n** Reserved (no FDI):**\n Defense and arms\n Nuclear energy\n Security printing (currency, stamps)\n Reserved forest operations\n\n**Profit repatriation:** Allowed for all FDI companies via authorized dealer bank\n\n FDI sector guide  3,999",
    },
    escalate: true,
    escalateReason: "FDI sector rules are complex and sector-specific. WhatsApp NLC.",
    relatedRules: ["co-fdi-001"],
  },
  {
    id: "co-qa-040",
    triggerKeywords: ["convert private to public", "private to public conversion", "convert company type", "opc to private"],
    question: "Can I convert my private limited company to a public limited company?",
    irac: {
      issue: "What is the process for converting a private company to public company?",
      rule: "Companies Act 1994, S.16-18: Private Ltd can convert to Public Ltd by special resolution (75% shareholders). Must increase directors to minimum 3, increase shareholders to minimum 7, alter AOA to remove private company restrictions, change name to include 'PLC'. File amended documents with RJSC. If issuing shares to public, BSEC prospectus approval needed.",
      application: "Pvt Ltd with 3 shareholders and 2 directors wants to go public: increase to 7 shareholders, add 1 more director (total 3), pass special resolution, amend MOA/AOA, change name, file with RJSC. Then approach BSEC for IPO approval.",
      conclusion: "**Private to Public conversion:**\n\n**Steps:**\n1. Board meeting  propose conversion\n2. EGM  75% special resolution\n3. Increase directors to minimum 3\n4. Increase shareholders to minimum 7\n5. Amend MOA  change name to 'PLC'\n6. Amend AOA  remove private company restrictions\n7. File with RJSC:\n    Amended MOA/AOA\n    Special resolution\n    List of new shareholders/directors\n8. New Certificate of Incorporation issued\n\n**For IPO (additional):**\n BSEC prospectus approval\n Underwriter appointment\n Share listing on stock exchange\n\n**Time:** 2-4 weeks (without IPO)\n\n Company conversion guide  3,999",
    },
    escalate: false,
    relatedRules: ["co-convert-001"],
  },
  {
    id: "co-qa-041",
    triggerKeywords: ["director disqualification", "disqualified director", "who cannot be director", "director barred"],
    question: "Who cannot be a director of a company in Bangladesh?",
    irac: {
      issue: "What are the grounds for disqualification of a director under Companies Act 1994?",
      rule: "Companies Act 1994, S.105-107: Person cannot be director if: insolvent, convicted of offence involving moral turpitude with imprisonment 6+ months (within last 5 years), failed to file returns for 3 consecutive years as director of another company, of unsound mind, under 18 years (unless AOA permits), not a natural person (companies/firms cannot be directors in Bangladesh).",
      application: "Person who was director of a struck-off company that failed to file returns for 3 years: disqualified from being director of any other company until the default is remedied and 5 years have passed.",
      conclusion: "**Director disqualification grounds:**\n\n **Cannot be director if:**\n Undischarged insolvent\n Convicted of offence (6+ months imprisonment, within 5 years)\n Failed to file returns for 3 consecutive years (as director elsewhere)\n Of unsound mind (declared by court)\n Under 18 (unless AOA allows)\n Not a natural person (no corporate directors)\n\n**Consequence of acting while disqualified:**\n Fine up to BDT 50,000\n All acts as director remain valid\n Company may also face penalty\n\n**Removal of disqualification:**\n Insolvent: obtain discharge certificate\n Conviction: wait 5 years from release\n Non-filing: file all pending returns + wait 5 years\n\n Director eligibility guide  999",
    },
    escalate: false,
    relatedRules: ["co-director-001"],
  },
  {
    id: "co-qa-042",
    triggerKeywords: ["company books inspection", "inspect company records", "shareholder inspection rights", "company accounts access"],
    question: "Can shareholders inspect company books and records?",
    irac: {
      issue: "What rights do shareholders have to inspect company documents?",
      rule: "Companies Act 1994, S.163-165: Shareholder can inspect: register of members, register of directors, minutes of general meetings, annual returns, balance sheet and profit/loss account  during business hours at registered office. Must give 5 days written notice. Director can inspect: all books of account, minutes of board meetings. Court can order inspection of additional documents.",
      application: "Shareholder suspects directors are misusing funds: can inspect balance sheet, minutes of AGM, register of members. If more detail needed (e.g., bank statements, contracts), must apply to court under S.165.",
      conclusion: "**Shareholder inspection rights:**\n\n**Without court order (5 days notice):**\n Register of members\n Register of directors and officers\n Minutes of general meetings (AGM/EGM)\n Annual returns\n Balance sheet and P&L account\n\n**Directors can additionally inspect:**\n All books of account\n Minutes of board meetings\n All statutory registers\n\n**Requires court order:**\n Bank statements\n Contracts and agreements\n Detailed transaction records\n Vouchers and invoices\n\n**Process:** Written notice to company secretary  inspect at registered office during business hours  can take copies (pay copying fee)\n\n**Refusal:** Company must give written reasons. Apply to court if unreasonably refused.\n\n Shareholder rights guide  1,999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-043",
    triggerKeywords: ["company tax rate", "corporate tax bangladesh", "company income tax", "tax rate company"],
    question: "What is the corporate tax rate for companies in Bangladesh?",
    irac: {
      issue: "What are the applicable income tax rates for different types of companies?",
      rule: "Income Tax Act 2023 (applicable from FY 2023-24): Non-listed company: 27.5%. Listed company: 22.5% (if more than 10% shares listed: 20%). Bank/financial institution: 37.5-40%. Merchant bank/insurance: 37.5%. EPZ company: 10% (during tax holiday) or 12% after. Foreign company (branch): 37.5-40%. Minimum tax: BDT 3,000 for non-listed, BDT 2,000 for listed.",
      application: "Private limited trading company: 27.5% corporate tax on taxable income. If taxable income is zero, still pay minimum tax BDT 3,000. Listed manufacturing company: 20% if 10%+ shares listed on stock exchange.",
      conclusion: "**Corporate tax rates (FY 2023-24 onwards):**\n\n| Company Type | Tax Rate |\n|---|---|\n| Non-listed company | 27.5% |\n| Listed company (>10% shares) | 20% |\n| Listed company (<10% shares) | 22.5% |\n| Bank/financial institution | 37.5-40% |\n| Insurance company | 37.5% |\n| Merchant bank | 37.5% |\n| EPZ company (tax holiday) | 10% |\n| EPZ company (post-holiday) | 12% |\n| Foreign company (branch) | 37.5-40% |\n| Company with 80%+ export | 12% |\n\n**Minimum tax:** BDT 3,000 (non-listed) / BDT 2,000 (listed)\n\n**Tax return deadline:** 15 July (following FY end)\n\n Tax rates change annually  verify current rates with NBR.\n\n Corporate tax guide  1,999",
    },
    escalate: false,
    relatedRules: [],
  },
  {
    id: "co-qa-044",
    triggerKeywords: ["related party transaction", "director personal interest", "director conflict interest", "interest disclosure"],
    question: "What are the rules for related party transactions in a company?",
    irac: {
      issue: "How must a company handle transactions where a director has personal interest?",
      rule: "Companies Act 1994, S.144: Director must disclose his interest (direct or indirect) in any contract/arrangement with the company at the first board meeting after becoming interested. General notice of interest can be given to board. Director with interest cannot participate in voting on that matter (but can be counted for quorum). Contract with interested director is not void but can be set aside by company if prejudicial.",
      application: "Director A owns 30% of a supplier company. Director A's company sells goods to the employer company: Director A must disclose this interest at board meeting. Cannot vote on the transaction. If price is unfair and prejudicial to company, shareholders can set aside the contract.",
      conclusion: "**Related party transaction rules:**\n\n**Director MUST:**\n Disclose interest at first board meeting after becoming aware\n Give general notice to board (covers future transactions)\n Not vote on the matter (but counts for quorum)\n\n**Types of interest to disclose:**\n Ownership in contracting party\n Directorship in contracting party\n Family member's interest\n Indirect financial benefit\n\n**Consequences of non-disclosure:**\n Contract not automatically void\n Company can set aside if prejudicial\n Director liable to account for profits\n Fine up to BDT 50,000\n\n**Best practice:**\n Always disclose in writing\n Record in board minutes\n Get independent valuation for major transactions\n Related party transactions disclosed in audited accounts\n\n Related party transaction guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-director-001"],
  },
  {
    id: "co-qa-045",
    triggerKeywords: ["reduce share capital", "capital reduction", "decrease authorized capital", "return capital shareholders"],
    question: "Can a company reduce its share capital?",
    irac: {
      issue: "What is the legal process for reducing a company's share capital?",
      rule: "Companies Act 1994, S.59-63: Capital reduction requires special resolution (75% shareholders) + High Court confirmation. Court will confirm only if: every creditor is paid or their consent obtained, court is satisfied it is just and equitable. Court may order company to publish advertisement calling for creditor objections.",
      application: "Company has BDT 50 lakh authorized capital but only needs BDT 10 lakh: apply to High Court  advertise for creditor objections  settle or secure all creditors  court confirms  file court order with RJSC  capital reduced.",
      conclusion: "**Share capital reduction:**\n\n**Requirements:**\n Special resolution (75% shareholders)\n High Court confirmation\n Every creditor must be paid OR consent\n\n**Process:**\n1. Board meeting  propose reduction\n2. EGM  75% special resolution\n3. Petition to High Court\n4. Court may order newspaper advertisement\n5. Creditors given opportunity to object\n6. All creditors paid or secured or consent obtained\n7. Court confirms reduction\n8. File court order + amended MOA at RJSC\n\n**Why reduce capital:**\n Return excess capital to shareholders\n Eliminate accumulated losses\n Write off unissued capital\n\n**Time:** 3-6 months (court process)\n\n High Court involvement mandatory  cannot be done by resolution alone.\n\n Capital reduction guide  4,999",
    },
    escalate: true,
    escalateReason: "Capital reduction requires High Court petition. WhatsApp NLC.",
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-046",
    triggerKeywords: ["proxy voting", "proxy shareholder meeting", "attend agm by proxy", "proxy form"],
    question: "Can a shareholder attend and vote at a meeting through a proxy?",
    irac: {
      issue: "What are the rules for proxy voting at company meetings?",
      rule: "Companies Act 1994, S.111-113: Member of company can appoint a proxy to attend and vote at any general meeting (AGM/EGM). Proxy need not be a member. Proxy form must be deposited at registered office at least 48 hours before meeting. Proxy has same speaking and voting rights as member. A member can appoint maximum 1 proxy per meeting. OPD (One Person Company) exempted.",
      application: "Shareholder lives abroad and cannot attend AGM: appoints colleague as proxy  sends signed proxy form 3 days before AGM  proxy attends, speaks, and votes on shareholder's behalf.",
      conclusion: "**Proxy voting rules:**\n\n**Who can appoint proxy:** Any member (shareholder)\n**Who can be proxy:** Any person (need not be a member)\n**Limit:** 1 proxy per member per meeting\n\n**Process:**\n1. Member fills proxy form (Form XX or as per AOA)\n2. Signs the form\n3. Deposits at registered office **48 hours before meeting**\n4. Proxy attends meeting with proof of identity\n5. Proxy speaks and votes as instructed\n\n**Important:**\n Member can still attend even after appointing proxy\n If both attend, member's vote prevails\n Proxy valid for ONE meeting only\n OPC exempted from proxy rules\n\n Proxy form template  199\n AGM compliance guide  1,999",
    },
    escalate: false,
    relatedRules: ["co-meeting-001"],
  },
  {
    id: "co-qa-047",
    triggerKeywords: ["company fraud", "director fraud", "fraudulent company", "punishment company fraud"],
    question: "What is the punishment for company fraud in Bangladesh?",
    irac: {
      issue: "What are the criminal penalties for fraud under the Companies Act 1994?",
      rule: "Companies Act 1994, S.447 (as amended): Fraud by any person associated with company (director, officer, employee)  imprisonment 6 months to 10 years + fine. Fraudulent incorporation (false documents): up to 3 years imprisonment + fine. False statement in return: up to 2 years + fine up to BDT 50,000. Fraudulent inducement to invest: up to 10 years imprisonment.",
      application: "Director submits false financial statements to RJSC showing inflated profits to attract investors: this is fraud under S.447  punishable with 6 months to 10 years imprisonment plus fine. Victims (investors) can also file separate civil suit for damages.",
      conclusion: "**Company fraud punishments:**\n\n| Fraud Type | Imprisonment | Fine |\n|---|---|---|\n| General fraud (S.447) | 6 months - 10 years | As per court |\n| Fraudulent incorporation | Up to 3 years | As per court |\n| False statement in returns | Up to 2 years | Up to BDT 50,000 |\n| Fraudulent inducement to invest | Up to 10 years | As per court |\n| Forgery of documents | Under Penal Code | Under Penal Code |\n\n**Who can be prosecuted:**\n Directors\n Officers of the company\n Employees who participated\n Auditors (for false reports)\n Professional advisors (if knowingly aided)\n\n**Reporting:**\n File criminal complaint with Magistrate Court\n RJSC can refer to law enforcement\n Bangladesh Bank (for banking fraud)\n ACC (for corruption component)\n\n Fraud is both criminal and civil  separate proceedings possible.\n\n Fraud reporting guide  2,999",
    },
    escalate: true,
    escalateReason: "Company fraud requires criminal complaint and police/law enforcement coordination. WhatsApp NLC.",
    relatedRules: [],
  },
  {
    id: "co-qa-048",
    triggerKeywords: ["sole proprietorship", "single business", "proprietorship registration", "individual business"],
    question: "How do I register a sole proprietorship business in Bangladesh?",
    irac: {
      issue: "What is the legal structure and registration process for a sole proprietorship?",
      rule: "No specific law governs sole proprietorship  it is not a separate legal entity. Owner and business are the same. Registration: trade licence from local authority + TIN from NBR. No RJSC registration needed. Unlimited personal liability. Cannot have 'Limited' or 'Ltd' in business name. Simplest business form with lowest compliance.",
      application: "Individual wants to open a small shop: no need for RJSC, no MOA/AOA. Just get trade licence from city corporation/municipality, TIN from NBR, and start business. Owner personally liable for all business debts  personal assets at risk.",
      conclusion: "**Sole Proprietorship:**\n\n**What it is:** Business owned and run by one individual\n**Legal status:** NOT a separate legal entity  owner = business\n\n**Registration needed:**\n Trade licence (city corporation/municipality)\n TIN (NBR)\n That's it  no RJSC, no MOA/AOA\n\n**Advantages:**\n Simplest to start\n Lowest cost\n Minimal compliance\n Full control\n\n**Disadvantages:**\n  Unlimited personal liability\n  Cannot raise equity capital\n  Business dies with owner\n  Cannot transfer ownership easily\n  Less credible for large contracts\n\n**Tax:** Owner files personal income tax return (not corporate)\n\n**When to upgrade:** When business grows, needs investment, or liability risk increases  convert to OPC or Pvt Ltd\n\n Business structure comparison  999",
    },
    escalate: false,
    relatedRules: ["co-opc-001"],
  },
  {
    id: "co-qa-049",
    triggerKeywords: ["subsidary company", "holding company", "subsidiary rules", "parent company"],
    question: "What defines a subsidiary and holding company in Bangladesh?",
    irac: {
      issue: "What are the legal definitions and implications of subsidiary and holding company relationships?",
      rule: "Companies Act 1994, S.2: Holding company = company that controls another company. Subsidiary = company controlled by another. Control means: owns 50%+ of nominal value of equity share capital, OR controls majority of board composition (by agreement or otherwise), OR controls more than half the voting power. Subsidiary's financials must be presented in holding company's group accounts.",
      application: "Company A owns 60% shares of Company B: Company A = holding company, Company B = subsidiary. Company A must prepare consolidated/group financial statements. Company B's losses affect Company A's group financials.",
      conclusion: "**Subsidiary & Holding Company:**\n\n**When is X a subsidiary of Y (Y = holding company):**\n Y owns 50%+ of X's equity share capital (nominal value), OR\n Y controls majority of X's board of directors, OR\n Y controls more than half of X's total voting power\n\n**Implications:**\n Holding company must prepare **group/consolidated accounts**\n Holding company discloses subsidiary list in annual return\n Inter-company transactions must be at arm's length\n Loans between holding and subsidiary have restrictions\n\n**Benefits:**\n Separate legal entities  liability ring-fenced\n Tax planning opportunities\n Business segmentation\n\n**Risks:**\n Group accounts may show subsidiary losses\n Holding company may be seen as 'shadow director' of subsidiary\n\n Group structure guide  2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001"],
  },
  {
    id: "co-qa-050",
    triggerKeywords: ["rjsc online", "roc.gov.bd guide", "rjsc portal", "online company registration"],
    question: "How do I use the RJSC online portal (roc.gov.bd) for company filings?",
    irac: {
      issue: "What are the key features and processes available on the RJSC online system?",
      rule: "RJSC Online System 2024 (roc.gov.bd): Fully digital company registration and filing system. Features: name clearance, new company incorporation, annual return filing, director/address/capital changes, certified copy downloads, charge registration, strike-off application. Payment via bKash/Nagad/bank. Digital signature required for submissions. Physical visit to RJSC not required for most processes.",
      application: "User wants to file annual return: login to roc.gov.bd  select company  annual return form  fill details  upload audited accounts  pay fee online  submission confirmed  RJSC processes and updates records.",
      conclusion: "**RJSC Online Portal (roc.gov.bd) guide:**\n\n**Registration:**\n1. Create account with email + phone\n2. Verify email\n3. Login credentials sent\n\n**Available services online:**\n  Name clearance (BDT 200)\n  New company incorporation\n  Annual return filing\n  Director change (Form XII)\n  Address change (Form VI)\n  Capital change (Form V)\n  Name change (Form II)\n  Charge registration (Form VIII/IX)\n  Certified copy download\n  Company search\n\n**Payment methods:**\n bKash\n Nagad\n Bank payment (Sonali, Janata, Agrani)\n\n**Requirements:**\n Digital signature (for company representative)\n NID + TIN of directors/shareholders\n Scanned documents\n\n**Processing time:**\n Name clearance: 1-3 working days\n Incorporation: 7-15 working days\n Changes: 3-7 working days\n\n**Support:** RJSC helpline + online chat on portal\n\n RJSC portal guide  999\n Full filing service  2,999",
    },
    escalate: false,
    relatedRules: ["co-pvt-001", "co-annual-001"],
  },
];

const companyLawModule: KnowledgeBank = {
  area: "company",
  label: "Company Law",
  description: "Knowledge module for company law in Bangladesh.",
  rules,
  qaBank,
};

export default companyLawModule;