// ─── JesAI Contract Law Knowledge Module ─────────────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: Contract Act 1872, Specific Relief Act 1877,
// Sale of Goods Act 1930, Limitation Act 1908
// Audience: Businesses, individuals, law students
// Last verified: 2025-04-01

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "con-formation-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Valid Contract — Section 10, Contract Act 1872",
    rule: "A contract is valid if: (1) there is an offer and acceptance, (2) lawful consideration, (3) free consent (not obtained by coercion, undue influence, fraud, misrepresentation or mistake), (4) parties are competent (age 18+, sound mind), and (5) the object is lawful. Contracts against public policy or law are void.",
    source: "Contract Act 1872, Section 10",
    certainty: "confirmed",
    tags: ["valid contract", "offer", "acceptance", "consideration", "free consent", "agreement"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-breach-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Breach of Contract — Sections 73–74, Contract Act 1872",
    rule: "When a party breaches a contract, the aggrieved party is entitled to: (1) compensation for losses naturally arising from the breach (Section 73), (2) liquidated damages if pre-agreed in the contract (Section 74), and (3) specific performance or injunction if damages are inadequate (Specific Relief Act 1877).",
    source: "Contract Act 1872, Sections 73–74; Specific Relief Act 1877",
    certainty: "confirmed",
    tags: ["breach of contract", "breach", "damages", "compensation", "liquidated damages", "specific performance"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-void-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Void and Voidable Contracts — Sections 2(g), 2(i), 19–23",
    rule: "A void contract has no legal effect from the beginning (e.g., contracts for illegal purposes, by incompetent parties, without consideration). A voidable contract is valid until rescinded by the aggrieved party (e.g., contracts made under coercion, undue influence, fraud, or misrepresentation). On rescission of a voidable contract, the parties are restored to original position.",
    source: "Contract Act 1872, Sections 2(g), 2(i), 19–23",
    certainty: "confirmed",
    tags: ["void contract", "voidable contract", "illegal contract", "fraud", "misrepresentation", "coercion"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-indemnity-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Indemnity — Section 124, Contract Act 1872",
    rule: "A contract of indemnity is a contract by which one party promises to save the other from loss caused by the promisor's conduct or by the conduct of any other person. The indemnity-holder can recover all damages, costs, and sums paid in any suit that the promisor was compelled to pay.",
    source: "Contract Act 1872, Section 124",
    certainty: "confirmed",
    tags: ["indemnity", "indemnify", "hold harmless", "indemnification clause", "loss protection"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-guarantee-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Contract of Guarantee — Section 126, Contract Act 1872",
    rule: "A contract of guarantee is a contract to perform the promise or discharge the liability of a third person in case of their default. Three parties: principal debtor, creditor, and surety. The surety's liability is co-extensive with that of the principal debtor unless the contract otherwise provides.",
    source: "Contract Act 1872, Section 126",
    certainty: "confirmed",
    tags: ["guarantee", "guarantor", "surety", "personal guarantee", "co-extensive liability"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-limitation-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Limitation Period for Contract Claims — Limitation Act 1908",
    rule: "The limitation period for a suit based on breach of contract is 3 years from when the breach occurred or was discovered. For money recovery on a written contract: 3 years. For specific performance of contract: 3 years from when the plaintiff was refused performance. Courts cannot entertain time-barred suits even if the claim is valid.",
    source: "Limitation Act 1908, First Schedule",
    certainty: "confirmed",
    tags: ["limitation", "3 years", "time limit", "limitation period", "time bar", "deadline to sue"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-specific-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Specific Performance — Specific Relief Act 1877",
    rule: "Courts can order specific performance of a contract where monetary compensation is inadequate to remedy the breach — typically contracts for sale of unique property, rare goods, or irreplaceable items. Courts will refuse specific performance where: the contract is not certain, the plaintiff cannot perform their side, or constant court supervision would be needed.",
    source: "Specific Relief Act 1877, Sections 12–25",
    certainty: "confirmed",
    tags: ["specific performance", "force contract", "compel performance", "property contract", "irreplaceable"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-stamp-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Stamp Duty on Contracts — Stamp Act 1899",
    rule: "Most commercial agreements (lease, sale, mortgage, partnership deed, power of attorney, loan agreements above BDT 20,000) require stamping under the Stamp Act 1899. An unstamped agreement is inadmissible as evidence in court until the deficiency plus 10× penalty is paid. Stamping can be done at the time of filing in court.",
    source: "Stamp Act 1899; Registration Act 1908",
    certainty: "confirmed",
    tags: ["stamp duty", "stamp", "unstamped", "agreement stamp", "admissibility", "court"],
    lastVerified: "2025-04-01",
  },
];

const qaBank: QAEntry[] = [
  {
    id: "con-qa-001",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["breach of contract", "supplier not delivering", "party not performing", "agreement broken", "default on contract", "contract violated"],
    question: "Someone breached a contract with me — what can I do to recover my loss?",
    irac: {
      issue: "A party has failed to perform their obligations under a contract, causing financial loss. The question is what legal remedies are available under Bangladesh contract law.",
      rule: "Under the Contract Act 1872, Section 73, the aggrieved party is entitled to compensation for losses that naturally flow from the breach. Under Section 74, if a liquidated damages clause exists, that sum is recoverable. The Specific Relief Act 1877 allows courts to order specific performance where money alone cannot compensate (e.g., unique property). Limitation: 3 years from breach.",
      application: "You must show: (1) a valid contract existed, (2) the other party did not perform, (3) you suffered loss as a direct result. Damages are calculated by putting you in the position you would have been if the contract was performed. You cannot recover remote or speculative losses.",
      conclusion: "Step 1: Send a formal legal demand notice specifying the breach and amount claimed (this is also a pre-litigation requirement). Step 2: Attempt negotiation/mediation. Step 3: If unresolved, file in the Civil Court (Munsiff/Joint District Judge depending on amount) within 3 years. Keep all written communications, the contract, and proof of your loss.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-limitation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-002",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["verbal agreement", "oral agreement", "no written contract", "handshake deal", "oral contract valid"],
    question: "Is a verbal agreement legally binding in Bangladesh?",
    irac: {
      issue: "A party wants to enforce a verbal agreement. The question is whether oral contracts are valid and enforceable under Bangladesh law.",
      rule: "Under Section 10 of the Contract Act 1872, a contract need not be in writing to be valid — an oral agreement with offer, acceptance, consideration, and free consent is legally binding. However, the Registration Act 1908 requires certain contracts to be in writing and registered (e.g., sales of immovable property above BDT 100). The practical problem with oral contracts is proving their existence and terms in court.",
      application: "An oral contract for sale of goods, services, or loans is enforceable. But proving an oral contract in court requires: witness testimony, part-performance (delivery, payment), written follow-up messages (WhatsApp, SMS, email), bank transfers, or any contemporaneous documentation that shows the agreement existed.",
      conclusion: "Oral contracts are valid but very hard to enforce without evidence. To strengthen your case: gather all digital communications (WhatsApp, email, SMS), evidence of payment, witnesses, delivery records. For important transactions — always get it in writing. Consult a lawyer if the dispute value is significant.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-003",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["advance payment", "advance not returned", "refund advance", "security deposit", "deposit not returned", "advance money"],
    question: "I paid an advance/deposit and the other party is refusing to refund it after not performing — what can I do?",
    irac: {
      issue: "A party received an advance payment but failed to perform their contractual obligation and refuses to return the money. The question is the payer's right to recovery.",
      rule: "Under Section 65 of the Contract Act 1872, when a contract is void or is rescinded, the party who received any advantage must restore it (restitution). Under Section 73, the payer can claim compensation for all losses from the non-performance including the advance. If the payee had no lawful right to retain the advance, it may constitute unjust enrichment.",
      application: "The advance payment creates an obligation: either perform the contract or return the money. If the payee voluntarily refuses to perform and keeps the advance, you have a clean claim for recovery plus damages. Send a demand notice first. If the advance was paid for an illegal purpose, recovery may be barred under Section 65.",
      conclusion: "Document the payment (bank transfer, receipt, cheque). Send a legal demand notice specifying the advance amount, date, and demanding refund within 15 days. If refused, file a money suit in Civil Court within 3 years. For smaller amounts, the Small Causes Court is faster. For advance above BDT 1 lakh, consider filing a money decree suit.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-004",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["personal guarantee", "guarantor liability", "bank guarantee", "signed guarantee", "liable as guarantor"],
    question: "I signed a personal guarantee for someone's loan — am I liable if they default?",
    irac: {
      issue: "A person signed a personal guarantee for another's bank loan or commercial debt. The question is the guarantor's liability if the principal debtor defaults.",
      rule: "Under Section 128 of the Contract Act 1872, the surety's liability is co-extensive with that of the principal debtor unless the guarantee contract says otherwise. The creditor (bank) can proceed directly against the guarantor without first exhausting remedies against the principal debtor. The guarantor can recover any amounts paid from the principal debtor under Section 145.",
      application: "Upon the principal debtor's default, the bank can immediately sue the guarantor for the full outstanding amount plus interest and costs. There is no requirement to first sue the principal debtor. If the guarantor pays, they acquire a right of subrogation to sue the principal debtor for recovery.",
      conclusion: "If you are being pursued as guarantor: check the guarantee document for any limitations on your liability, check if the bank has given proper notice of default, and assess whether the principal debt is disputed. You can challenge the guarantee if it was obtained by misrepresentation or fraud. Consult a lawyer immediately — guarantee claims move fast.",
    },
    escalate: true,
    escalateReason: "Personal guarantee claims often involve large sums and move to execution quickly. Seek urgent legal advice.",
    relatedRules: ["con-guarantee-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-005",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["contract fraud", "signed under pressure", "cheated into contract", "misrepresentation contract", "coercion contract"],
    question: "I was deceived or pressured into signing a contract — can I cancel it?",
    irac: {
      issue: "A party signed a contract under fraud, misrepresentation, coercion, or undue influence. The question is whether the contract can be rescinded.",
      rule: "Under Sections 14–19 of the Contract Act 1872, consent obtained by coercion, undue influence, fraud, or misrepresentation makes the contract voidable. The aggrieved party may either rescind the contract (cancel it entirely and seek restitution) or affirm it and claim damages for misrepresentation. Time is important: delay in rescinding may amount to affirmation.",
      application: "To rescind: (1) you must act promptly after discovering the fraud/misrepresentation, (2) restore any benefit you received under the contract, (3) file a suit for rescission and restitution. If third-party rights have arisen in the interim, full rescission may not be possible but damages may still be recoverable.",
      conclusion: "Do not continue to perform the contract once you discover the fraud. Immediately document the deception (evidence, witnesses). Consult a lawyer to prepare a rescission suit. File within 3 years of discovering the fraud. Courts are generally sympathetic to fraud victims if you act promptly.",
    },
    escalate: true,
    escalateReason: "Contract fraud may also carry criminal implications (cheating under Penal Code). A lawyer can advise on both civil and criminal options.",
    relatedRules: ["con-void-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
];

const contractModule: KnowledgeModule = {
  area: "contract",
  label: "Contract Law",
  description: "Contract formation, breach, remedies, guarantee, and limitation under the Contract Act 1872",
  rules,
  qaBank,
};

export default contractModule;
