//  JesAI Contract Law Knowledge Module 
// NLC validated  Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: Contract Act 1872, Specific Relief Act 1877,
// Sale of Goods Act 1930, Limitation Act 1908, Stamp Act 1899
// Audience: Businesses, individuals, law students
// Last verified: 2025-04-01

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "con-formation-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Valid Contract  Section 10, Contract Act 1872",
    rule: "A contract is valid if: (1) there is an offer and acceptance, (2) lawful consideration, (3) free consent (not obtained by coercion, undue influence, fraud, misrepresentation or mistake), (4) parties are competent (age 18+, sound mind), and (5) the object is lawful. Contracts against public policy or law are void.",
    source: "Contract Act 1872, Section 10",
    certainty: "confirmed",
    tags: ["valid contract", "offer", "acceptance", "consideration", "free consent", "agreement"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-breach-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Breach of Contract  Sections 7374, Contract Act 1872",
    rule: "When a party breaches a contract, the aggrieved party is entitled to: (1) compensation for losses naturally arising from the breach (Section 73), (2) liquidated damages if pre-agreed in the contract (Section 74), and (3) specific performance or injunction if damages are inadequate (Specific Relief Act 1877).",
    source: "Contract Act 1872, Sections 7374; Specific Relief Act 1877",
    certainty: "confirmed",
    tags: ["breach of contract", "breach", "damages", "compensation", "liquidated damages", "specific performance"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-void-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Void and Voidable Contracts  Sections 2(g), 2(i), 1923",
    rule: "A void contract has no legal effect from the beginning (e.g., contracts for illegal purposes, by incompetent parties, without consideration). A voidable contract is valid until rescinded by the aggrieved party (e.g., contracts made under coercion, undue influence, fraud, or misrepresentation). On rescission of a voidable contract, the parties are restored to original position.",
    source: "Contract Act 1872, Sections 2(g), 2(i), 1923",
    certainty: "confirmed",
    tags: ["void contract", "voidable contract", "illegal contract", "fraud", "misrepresentation", "coercion"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-indemnity-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Indemnity  Section 124, Contract Act 1872",
    rule: "A contract of indemnity is a contract by which one party promises to save the other from loss caused by the promisor's conduct or by the conduct of any other person. The indemnity-holder can recover all damages, costs, and sums paid in any suit that the promisor was compelled to pay.",
    source: "Contract Act 1872, Section 124",
    certainty: "confirmed",
    tags: ["indemnity", "indemnify", "hold harmless", "indemnification clause", "loss protection"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-guarantee-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Contract of Guarantee  Section 126, Contract Act 1872",
    rule: "A contract of guarantee is a contract to perform the promise or discharge the liability of a third person in case of their default. Three parties: principal debtor, creditor, and surety. The surety's liability is co-extensive with that of the principal debtor unless the contract otherwise provides.",
    source: "Contract Act 1872, Section 126",
    certainty: "confirmed",
    tags: ["guarantee", "guarantor", "surety", "personal guarantee", "co-extensive liability"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-limitation-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Limitation Period for Contract Claims  Limitation Act 1908",
    rule: "The limitation period for a suit based on breach of contract is 3 years from when the breach occurred or was discovered. For money recovery on a written contract: 3 years. For specific performance of contract: 3 years from when the plaintiff was refused performance. Courts cannot entertain time-barred suits even if the claim is valid.",
    source: "Limitation Act 1908, First Schedule",
    certainty: "confirmed",
    tags: ["limitation", "3 years", "time limit", "limitation period", "time bar", "deadline to sue"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-specific-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Specific Performance  Specific Relief Act 1877",
    rule: "Courts can order specific performance of a contract where monetary compensation is inadequate to remedy the breach  typically contracts for sale of unique property, rare goods, or irreplaceable items. Courts will refuse specific performance where: the contract is not certain, the plaintiff cannot perform their side, or constant court supervision would be needed.",
    source: "Specific Relief Act 1877, Sections 1225",
    certainty: "confirmed",
    tags: ["specific performance", "force contract", "compel performance", "property contract", "irreplaceable"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-stamp-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Stamp Duty on Contracts  Stamp Act 1899",
    rule: "Most commercial agreements (lease, sale, mortgage, partnership deed, power of attorney, loan agreements above BDT 20,000) require stamping under the Stamp Act 1899. An unstamped agreement is inadmissible as evidence in court until the deficiency plus 10 penalty is paid. Stamping can be done at the time of filing in court.",
    source: "Stamp Act 1899; Registration Act 1908",
    certainty: "confirmed",
    tags: ["stamp duty", "stamp", "unstamped", "agreement stamp", "admissibility", "court"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-offer-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Offer and Acceptance  Sections 2(a), 39, Contract Act 1872",
    rule: "An offer is a proposal by one party to another indicating willingness to do or abstain from doing something to obtain their assent. It must be certain and communicated. Acceptance must be absolute and unqualified (mirror image rule). A counter-offer kills the original offer. Acceptance is complete when communicated to the offeror.",
    source: "Contract Act 1872, Sections 2(a), 39",
    certainty: "confirmed",
    tags: ["offer", "acceptance", "proposal", "counter-offer", "mirror image rule", "communication"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-consideration-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Lawful Consideration  Sections 2(d), 2325, Contract Act 1872",
    rule: "Consideration means something in return (act, abstinence, or promise). It must move at the desire of the promisor, can be from the promisee or a third party, may be past, present, or future, but must be lawful and have some value (not necessarily adequate). A promise without consideration is generally void unless it's a written and registered gift or falls under specific exceptions.",
    source: "Contract Act 1872, Sections 2(d), 2325",
    certainty: "confirmed",
    tags: ["consideration", "something in return", "past consideration", "adequacy", "nudum pactum"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-minor-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Minor's Contract  Section 11, Contract Act 1872",
    rule: "A person under 18 years is a minor. Agreements by minors are void ab initio (completely void from the start, per Mohori Bibee v. Dharmodas Ghose). A minor cannot be sued for breach, nor can they ratify the contract upon reaching majority. However, a minor can be a beneficiary (e.g., receiving a gift or property via trust).",
    source: "Contract Act 1872, Section 11; Privy Council precedent",
    certainty: "confirmed",
    tags: ["minor", "under 18", "void ab initio", "incompetent", "minor contract"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-restraint-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Restraint of Trade  Section 27, Contract Act 1872",
    rule: "Every agreement that restrains a person from exercising a lawful profession, trade, or business is void to that extent. Exceptions: sale of goodwill (reasonable restriction in time/space allowed), partnership deeds (restrictions during partnership), and non-compete during employment (only if strictly necessary to protect trade secrets, not general post-employment bans).",
    source: "Contract Act 1872, Section 27",
    certainty: "confirmed",
    tags: ["restraint of trade", "non-compete", "void agreement", "competition", "goodwill"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-soga-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Sale of Goods  Conditions vs Warranties, SOGA 1930",
    rule: "A condition is a stipulation essential to the main purpose of the contract (breach gives right to reject goods). A warranty is subsidiary to the main purpose (breach gives right to damages only). Implied conditions: title, description, fitness for purpose (if buyer relies on seller), merchantable quality, sale by sample.",
    source: "Sale of Goods Act 1930, Sections 1216",
    certainty: "confirmed",
    tags: ["sale of goods", "condition", "warranty", "merchantable quality", "fitness for purpose", "soga"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-frustration-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Frustration of Contract (Force Majeure)  Section 56, Contract Act 1872",
    rule: "A contract to do an act that becomes impossible or unlawful after it is made becomes void. This applies to objective impossibility (e.g., property destroyed by act of God, war making performance illegal), not subjective inability (e.g., seller can't find a cheaper supplier). Parties are discharged from future obligations but liable for what was already performed.",
    source: "Contract Act 1872, Section 56",
    certainty: "confirmed",
    tags: ["frustration", "force majeure", "impossible performance", "void contract", "act of god"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-quasi-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Quasi-Contracts  Sections 6872, Contract Act 1872",
    rule: "Quasi-contracts are not actual agreements but obligations imposed by law to prevent unjust enrichment. Examples: supply of necessities to a person incapable of contracting (S.68), payment by an interested person (S.69), non-gratuitous acts (S.70), finder of goods (S.71), and money paid by mistake or under coercion (S.72).",
    source: "Contract Act 1872, Sections 6872",
    certainty: "confirmed",
    tags: ["quasi contract", "unjust enrichment", "mistaken payment", "necessities", "finder of goods"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-bailment-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Bailment  Sections 148171, Contract Act 1872",
    rule: "Bailment is the delivery of goods by one person to another for some purpose, to be returned or disposed of as directed. The bailee must take reasonable care of goods, not mix them with their own, not make unauthorized use, and return them when the purpose is achieved. A bailee is strictly liable if they fail to return goods on demand.",
    source: "Contract Act 1872, Sections 148171",
    certainty: "confirmed",
    tags: ["bailment", "bailee", "bailor", "safekeeping", "delivery of goods", "repair"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-penalty-001",
    area: "contract",
    jurisdiction: "BD",
    title: "Liquidated Damages vs Penalty  Section 74, Contract Act 1872",
    rule: "Section 74 treats a stipulation for liquidated damages or penalty as a genuine pre-estimate of loss. Courts can only interfere if the stipulated amount is so extravagant that it shows no genuine attempt to estimate loss. If it's a genuine pre-estimate, it's enforceable; if punitive, courts may grant only actual proven damages.",
    source: "Contract Act 1872, Section 74",
    certainty: "confirmed",
    tags: ["liquidated damages", "penalty", "pre-estimate", "stipulated damages", "forfeiture"],
    lastVerified: "2025-04-01",
  },
];

const qaBank: QAEntry[] = [
  {
    id: "con-qa-001",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["breach of contract", "supplier not delivering", "party not performing", "agreement broken", "default on contract", "contract violated"],
    question: "Someone breached a contract with me  what can I do to recover my loss?",
    irac: {
      issue: "A party has failed to perform their obligations under a contract, causing financial loss. The question is what legal remedies are available under Bangladesh contract law.",
      rule: "Under the Contract Act 1872, Section 73, the aggrieved party is entitled to compensation for losses that naturally flow from the breach. Under Section 74, if a liquidated damages clause exists, that sum is recoverable. The Specific Relief Act 1877 allows courts to order specific performance where money alone cannot compensate (e.g., unique property). Limitation: 3 years from breach.",
      application: "You must show: (1) a valid contract existed, (2) the other party did not perform, (3) you suffered loss as a direct result. Damages are calculated by putting you in the position you would have been if the contract was performed. You cannot recover remote or speculative losses.",
      conclusion: "Step 1: Send a formal legal demand notice specifying the breach and amount claimed (this is also a pre-litigation requirement). Step 2: Attempt negotiation/mediation. Step 3: If unresolved, file a money suit or suit for specific performance in the Civil Court (Munsiff/Joint District Judge depending on amount) within 3 years. Keep all written communications, the contract, and proof of your loss.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-limitation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-002",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["verbal agreement", "oral agreement", "no written contract", "handshake deal", "oral contract valid"],
    question: "Is a verbal agreement legally binding in Bangladesh?",
    irac: {
      issue: "A party wants to enforce a verbal agreement. The question is whether oral contracts are valid and enforceable under Bangladesh law.",
      rule: "Under Section 10 of the Contract Act 1872, a contract need not be in writing to be valid  an oral agreement with offer, acceptance, consideration, and free consent is legally binding. However, the Registration Act 1908 requires certain contracts to be in writing and registered (e.g., sales of immovable property above BDT 100). The practical problem with oral contracts is proving their existence and terms in court.",
      application: "An oral contract for sale of goods, services, or loans is enforceable. But proving an oral contract in court requires: witness testimony, part-performance (delivery, payment), written follow-up messages (WhatsApp, SMS, email), bank transfers, or any contemporaneous documentation that shows the agreement existed.",
      conclusion: "Oral contracts are valid but very hard to enforce without evidence. To strengthen your case: gather all digital communications (WhatsApp, email, SMS), evidence of payment, witnesses, delivery records. For important transactions  always get it in writing. Consult a lawyer if the dispute value is significant.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-003",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["advance payment", "advance not returned", "refund advance", "security deposit", "deposit not returned", "advance money"],
    question: "I paid an advance/deposit and the other party is refusing to refund it after not performing  what can I do?",
    irac: {
      issue: "A party received an advance payment but failed to perform their contractual obligation and refuses to return the money. The question is the payer's right to recovery.",
      rule: "Under Section 65 of the Contract Act 1872, when a contract is void or is rescinded, the party who received any advantage must restore it (restitution). Under Section 73, the payer can claim compensation for all losses from the non-performance including the advance. If the payee had no lawful right to retain the advance, it may constitute unjust enrichment.",
      application: "The advance payment creates an obligation: either perform the contract or return the money. If the payee voluntarily refuses to perform and keeps the advance, you have a clean claim for recovery plus damages. Send a demand notice first. If the advance was paid for an illegal purpose, recovery may be barred under Section 65.",
      conclusion: "Document the payment (bank transfer, receipt, cheque). Send a legal demand notice specifying the advance amount, date, and demanding refund within 15 days. If refused, file a money suit in Civil Court within 3 years. For smaller amounts, the Small Causes Court is faster. For advance above BDT 1 lakh, consider filing a money decree suit.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-004",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["personal guarantee", "guarantor liability", "bank guarantee", "signed guarantee", "liable as guarantor"],
    question: "I signed a personal guarantee for someone's loan  am I liable if they default?",
    irac: {
      issue: "A person signed a personal guarantee for another's bank loan or commercial debt. The question is the guarantor's liability if the principal debtor defaults.",
      rule: "Under Section 128 of the Contract Act 1872, the surety's liability is co-extensive with that of the principal debtor unless the guarantee contract says otherwise. The creditor (bank) can proceed directly against the guarantor without first exhausting remedies against the principal debtor. The guarantor can recover any amounts paid from the principal debtor under Section 145.",
      application: "Upon the principal debtor's default, the bank can immediately sue the guarantor for the full outstanding amount plus interest and costs. There is no requirement to first sue the principal debtor. If the guarantor pays, they acquire a right of subrogation to sue the principal debtor for recovery.",
      conclusion: "If you are being pursued as guarantor: check the guarantee document for any limitations on your liability, check if the bank has given proper notice of default, and assess whether the principal debt is disputed. You can challenge the guarantee if it was obtained by misrepresentation or fraud. Consult a lawyer immediately  guarantee claims move fast.",
    },
    escalate: true,
    escalateReason: "Personal guarantee claims often involve large sums and move to execution quickly. Seek urgent legal advice.",
    relatedRules: ["con-guarantee-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-005",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["contract fraud", "signed under pressure", "cheated into contract", "misrepresentation contract", "coercion contract"],
    question: "I was deceived or pressured into signing a contract  can I cancel it?",
    irac: {
      issue: "A party signed a contract under fraud, misrepresentation, coercion, or undue influence. The question is whether the contract can be rescinded.",
      rule: "Under Sections 1419 of the Contract Act 1872, consent obtained by coercion, undue influence, fraud, or misrepresentation makes the contract voidable. The aggrieved party may either rescind the contract (cancel it entirely and seek restitution) or affirm it and claim damages for misrepresentation. Time is important: delay in rescinding may amount to affirmation.",
      application: "To rescind: (1) you must act promptly after discovering the fraud/misrepresentation, (2) restore any benefit you received under the contract, (3) file a suit for rescission and restitution. If third-party rights have arisen in the interim, full rescission may not be possible but damages may still be recoverable.",
      conclusion: "Do not continue to perform the contract once you discover the fraud. Immediately document the deception (evidence, witnesses). Consult a lawyer to prepare a rescission suit. File within 3 years of discovering the fraud. Courts are generally sympathetic to fraud victims if you act promptly.",
    },
    escalate: true,
    escalateReason: "Contract fraud may also carry criminal implications (cheating under Penal Code). A lawyer can advise on both civil and criminal options.",
    relatedRules: ["con-void-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
  //  ENRICHED SECTION: QA 006-050 
  {
    id: "con-qa-006",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["what is an offer", "proposal contract", "", "offer vs invitation", "catalogue price offer", "counter offer"],
    question: "What is a valid legal offer, and how is it different from an invitation to treat?",
    irac: {
      issue: "Distinguishing between a legally binding offer and a mere invitation to treat (which does not create legal obligations upon acceptance).",
      rule: "Under Section 2(a) of the Contract Act 1872, an offer is a proposal indicating willingness to do or abstain from doing something to obtain the assent of the other party. An invitation to treat (e.g., shop display, catalogue, advertisement, tender invitation) is merely an invitation to make an offer. A counter-offer kills the original offer entirely.",
      application: "A shop displaying a TV with a price tag is an invitation to treat. The customer going to the counter and saying 'I will buy this for BDT 50,000' is making the offer. The shopkeeper accepting the payment is the acceptance. If the shopkeeper says 'I will sell it for BDT 55,000', this is a counter-offer that kills the customer's BDT 50,000 offer.",
      conclusion: "An offer must be: (1) clear and certain, (2) communicated to the offeree, (3) show intention to be legally bound. Advertisements, price lists, and display of goods are generally NOT offers  they are invitations to treat. A counter-offer destroys the original offer. If you are drafting an offer, use words like 'I am willing to...' to show clear intention.",
    },
    escalate: false,
    relatedRules: ["con-offer-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-007",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["acceptance by email", "whatsapp acceptance", "acceptance rules", "  ", "when is contract formed"],
    question: "Does accepting a contract via WhatsApp or email create a valid binding agreement?",
    irac: {
      issue: "Whether digital or electronic communications constitute valid acceptance under Bangladesh law.",
      rule: "Under the Information and Communication Technology (ICT) Act 2006, electronic contracts are valid. Under Contract Act 1872, acceptance must be communicated. An email or WhatsApp message saying 'I agree' or 'Accepted' is a valid communication of acceptance. The contract is formed at the time and place the acceptance message is sent (not when it is read), per the 'postal rule' applied to instantaneous electronic communication in modern practice.",
      application: "Supplier sends a quotation via email. Buyer replies 'Accepted, proceed' via WhatsApp. A legally binding contract is formed the moment the buyer hits send on WhatsApp. Neither party can back out after this point without consequences.",
      conclusion: "Yes, WhatsApp, email, and SMS are legally valid modes of acceptance in Bangladesh. The contract forms when the message of acceptance is sent/received depending on the communication method. To avoid disputes: (1) clearly state 'I accept your offer dated [X]', (2) save chat logs and email threads, (3) follow up with a formal PDF agreement if the value is high.",
    },
    escalate: false,
    relatedRules: ["con-offer-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-008",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["what is consideration", "contract without payment", "", "free promise", "adequacy of consideration", "past consideration"],
    question: "What counts as valid 'consideration' in a contract? Can I enforce a free promise?",
    irac: {
      issue: "Understanding the requirement of 'something in return' to make a promise legally enforceable.",
      rule: "Under Section 2(d) of the Contract Act 1872, consideration means doing, abstaining from doing, or promising to do something at the desire of the promisor. Under Section 25, an agreement without consideration is void, except if it's a written and registered gift, a promise to pay a time-barred debt, or past consideration made at the promisor's request. Consideration need not be adequate (a car can be sold for BDT 10 if consent is free), but it must have some value in the eyes of the law.",
      application: "A promises to give B BDT 1 lakh as a gift out of love. B cannot enforce this because there is no consideration (it's not a registered written gift). However, if A says 'I will pay you BDT 1 lakh if you clean my house', the cleaning is the consideration. If A says 'I already cleaned your house last week, so pay me now'  this is past consideration and generally unenforceable unless done at A's request.",
      conclusion: "A free promise (no consideration) is NOT enforceable. Consideration must: (1) move at the desire of the promisor, (2) have some legal value, (3) be possible and lawful. It does NOT need to be economically fair (adequacy is irrelevant). If someone promises you something for free, get it as a registered gift deed, otherwise it is legally unenforceable.",
    },
    escalate: false,
    relatedRules: ["con-consideration-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-009",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["contract with minor", "under 18 agreement", " ", "minor bought phone", "can minor sign"],
    question: "Is a contract with a person under 18 years old legally valid?",
    irac: {
      issue: "Determining the legal standing of a contract entered into by a minor (person under 18).",
      rule: "Under Section 11 of the Contract Act 1872, a person under 18 is incompetent to contract. The landmark Privy Council case Mohori Bibee v. Dharmodas Ghose established that a minor's agreement is void ab initio (void from the very beginning). It cannot be ratified upon reaching majority. The minor can be restored to their original position (get their money/goods back), but the adult party cannot enforce the contract against the minor.",
      application: "A 17-year-old buys a laptop on installment from a shop. After 3 months, the minor stops paying. The shop cannot sue the minor to enforce the installments because the contract is void. The minor (or their guardian) can return the laptop and demand a refund of the installments already paid.",
      conclusion: "A contract with a minor is completely VOID from the start. The minor cannot be held liable for breach. The adult party must return any benefits/money received from the minor if the contract is cancelled. Exception: A minor can receive benefits under a contract (e.g., life insurance policy, trust property) without it being void. Always verify age via NID before major transactions.",
    },
    escalate: false,
    relatedRules: ["con-minor-001", "con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-010",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["non-compete clause", "restraint of trade", " ", "cannot work for competitor", "non-compete agreement"],
    question: "Are non-compete clauses in employment or business contracts enforceable in Bangladesh?",
    irac: {
      issue: "Whether a clause preventing a party from working for a competitor or starting a competing business is legally binding.",
      rule: "Section 27 of the Contract Act 1872 declares all agreements in restraint of trade as void. You cannot stop someone from practicing a lawful profession. Exception: Reasonable restrictions in time and geography are allowed ONLY in the context of the sale of business goodwill. Post-employment non-compete clauses are generally void unless strictly limited to protecting trade secrets during the employment period.",
      application: "An employment contract says 'You cannot work in the IT sector in Dhaka for 2 years after leaving.' This is void under S.27. The employee can leave and immediately join a competitor. However, a business sale agreement says 'Seller won't open a similar shop within 1 km for 1 year'  this is likely valid as it protects the goodwill sold.",
      conclusion: "General non-compete clauses in employment contracts are VOID in Bangladesh. An employer cannot legally stop a former employee from joining a competitor. However, you CAN enforce: (1) confidentiality clauses (protecting trade secrets/data), (2) non-solicitation clauses (stopping employee from poaching clients), and (3) reasonable restrictions during active employment.",
    },
    escalate: false,
    relatedRules: ["con-restraint-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-011",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["condition vs warranty", "defective goods", "  ", "breach of condition", "reject goods"],
    question: "What is the difference between a 'condition' and a 'warranty' in a sale of goods contract?",
    irac: {
      issue: "Understanding the distinction because it determines whether a buyer can reject goods or only claim damages.",
      rule: "Under Section 12 of the Sale of Goods Act 1930, a condition is a stipulation essential to the main purpose of the contract. A warranty is a stipulation collateral to the main purpose. Breach of condition gives the buyer the right to reject the goods and get a full refund. Breach of warranty only gives the right to claim damages, but the buyer must keep the goods.",
      application: "You order a 'Brand New iPhone 15' but receive a refurbished one. 'Brand new' is a condition  you can reject it. You buy a car and the AC doesn't work. The AC might only be a warranty  you can claim repair costs but probably can't reject the whole car (unless the court treats it as a condition).",
      conclusion: "Breach of CONDITION: Right to REJECT goods + full refund. Breach of WARRANTY: Right to DAMAGES only (must keep goods). Note: A buyer can also treat a breach of condition as a breach of warranty (i.e., choose to keep the goods and claim damages instead of rejecting them). Always specify in your purchase orders what are 'conditions' (essential features) vs 'warranties' (extras).",
    },
    escalate: false,
    relatedRules: ["con-soga-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-012",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["ownership transfer", "when does property pass", " ", "risk passes", "goods ownership"],
    question: "When does ownership (property) of goods pass from seller to buyer?",
    irac: {
      issue: "Determining when the legal title and risk of loss transfer to the buyer in a sale of goods contract.",
      rule: "Under Sections 18-26 of the Sale of Goods Act 1930, the general rule is that property passes when the parties intend it to pass. For specific or ascertained goods in a deliverable state, property passes when the contract is made. For unascertained or future goods, property passes only when goods are unconditionally appropriated to the contract (e.g., set aside and labeled for the buyer). Risk generally passes with property.",
      application: "You buy a specific branded TV from a shop. The moment you pay and the contract is finalized, you own the TV  even before you take it home. If the shop burns down before you pick it up, YOU bear the loss, not the shop. If you order '10 tons of rice' from a warehouse of 100 tons, ownership passes only when 10 tons are separated and earmarked for you.",
      conclusion: "Ownership passes when parties intend it to. For specific goods: passes when contract is made. For unascertained goods: passes when goods are set aside for you. Risk of damage/loss passes WITH ownership. To protect yourself: include a 'Retention of Title' clause in your contract stating ownership passes only upon full payment.",
    },
    escalate: false,
    relatedRules: ["con-soga-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-013",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["bought defective product", "seller lied about product", " ", "fake product", "not as described"],
    question: "I bought goods that are defective or not as described  what are my legal rights?",
    irac: {
      issue: "Remedies available to a buyer when the seller delivers non-conforming or defective goods.",
      rule: "Under the Sale of Goods Act 1930, the seller has implied duties: goods must correspond with description (S.15), be of merchantable quality (S.16), and be fit for the buyer's purpose if the buyer relied on the seller's skill (S.16). Under S.57-59, buyer remedies for breach include: rejecting goods (if breach of condition), claiming damages, suing for specific performance, or demanding a price reduction.",
      application: "You ordered 100% cotton t-shirts but received polyester. This breaches the implied condition of description (S.15). You can reject the whole batch and demand a refund. If you bought a fridge and it makes a noise but still cools (merchantable quality issue), you can claim repair costs but might not be able to reject it.",
      conclusion: "Your rights as a buyer: (1) Reject goods and claim full refund (if condition breached), (2) Keep goods and claim damages for the defect, (3) Ask for repair/replacement, (4) Sue for specific delivery. Action steps: Send a written notice to the seller immediately specifying the defect and your demand. Do NOT use or alter the goods if you plan to reject them. File a consumer case or civil suit if ignored.",
    },
    escalate: false,
    relatedRules: ["con-soga-001", "con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-014",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["contract impossible", "force majeure", "  ", "cannot perform contract", "war pandemic contract"],
    question: "What happens if a contract becomes impossible to perform due to war, flood, or pandemic?",
    irac: {
      issue: "Whether parties are excused from liability when an unforeseen event makes performance objectively impossible.",
      rule: "Under Section 56 of the Contract Act 1872, a contract to do an act that becomes impossible or unlawful after the contract is made becomes void. This is the doctrine of frustration. It applies to objective impossibility (e.g., concert hall burns down before the show, government bans export of the contracted goods). It does NOT apply to subjective impossibility (e.g., supplier's factory burned down but they could buy from another supplier).",
      application: "You booked a venue for a wedding. The government imposes a COVID-19 lockdown prohibiting public gatherings. The contract is frustrated  void from the date of the lockdown. You get a refund of your advance. However, if the price of raw materials goes up 500%, making the contract unprofitable, this is NOT frustration  you must still perform.",
      conclusion: "Frustration applies only when performance is OBJECTIVELY impossible or unlawful. Financial hardship or increased cost is NOT frustration. When a contract is frustrated: (1) Future obligations are cancelled, (2) Money paid before frustration must be returned, (3) Money due before frustration can be claimed. Always include a 'Force Majeure' clause in contracts to explicitly define these scenarios.",
    },
    escalate: false,
    relatedRules: ["con-frustration-001", "con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-015",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["transfer contract rights", "assign contract", " ", "can I transfer my agreement", "assignment"],
    question: "Can I transfer my rights or obligations under a contract to someone else?",
    irac: {
      issue: "The rules regarding assigning (transferring) contractual benefits and delegating contractual duties.",
      rule: "Under Section 130 of the Contract Act 1872, the benefits of a contract (the right to receive money/goods) can be transferred by assignment, unless it is personal in nature (e.g., right to paint a portrait, right to receive future royalties). However, obligations (the burden of a contract) generally CANNOT be transferred without the other party's consent (novation). If you try to delegate your duty, you remain liable if the delegate fails to perform.",
      application: "A supplier owes you BDT 10 lakh. You can assign this right to your friend, and the friend can sue the supplier directly. However, if you have a contract to build a house for someone, you cannot simply tell them 'My friend will build it instead' unless they agree. If the friend builds it badly, the client can still sue you.",
      conclusion: "You CAN transfer your RIGHTS (receiving money, property) by assignment  no consent needed from the other party (just written notice). You CANNOT transfer your OBLIGATIONS (doing work, paying money) without the other party's written consent (this is called Novation). If you assign rights, always send a formal legal notice of assignment to the other party.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-016",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["penalty clause", "liquidated damages clause", " ", "late fee contract", "forfeiture clause"],
    question: "Is a penalty clause or late fee clause in a contract enforceable?",
    irac: {
      issue: "Whether a stipulated sum for breach of contract (penalty/late fee) will be fully enforced by courts or reduced.",
      rule: "Under Section 74 of the Contract Act 1872, courts treat a stipulation for damages or penalty as a genuine pre-estimate of loss. If the amount is a genuine pre-estimate of the likely loss from breach, it is fully enforceable. If it is extravagant and unconscionable (purely punitive), the court may award only the actual proven loss, ignoring the penalty.",
      application: "A construction contract says 'If delayed, pay BDT 10,000 per day.' If actual delay cost is proven to be BDT 10,000/day, the clause is fully enforceable. If the contract says 'If you cancel, pay 200% of the order value,' a court will likely strike this down as a punitive penalty and only award the actual loss suffered.",
      conclusion: "A genuine pre-estimate of loss (Liquidated Damages) is ENFORCEABLE. A punitive punishment (Penalty) is NOT fully enforceable. To make your late fee/penalty clause bulletproof: (1) Base it on a calculable formula (e.g., actual extra rent you pay, actual interest cost), (2) Keep it reasonable (e.g., 1-2% per month, not 50%), (3) State in the contract *why* this amount represents your actual loss.",
    },
    escalate: false,
    relatedRules: ["con-penalty-001", "con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-017",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["force someone to sell", "specific performance suit", "  ", "buyer won't transfer property", "compel performance"],
    question: "Can I force someone to complete a sale of land or property if they back out?",
    irac: {
      issue: "Whether a buyer can obtain a court order forcing the seller to transfer property instead of just claiming damages.",
      rule: "Under the Specific Relief Act 1877, Section 12, specific performance (forcing the party to perform exactly as promised) is granted when monetary compensation is inadequate. This is almost always the case for immovable property (land, flats) because every piece of land is considered unique. Courts will refuse if the contract is uncertain, the plaintiff has unclean hands, or constant supervision is needed.",
      application: "You signed an agreement to buy a flat. The seller receives the money but refuses to register the deed because the market price went up. You can file a suit for specific performance. The court will order the seller to sign the sale deed and register the property in your name. If they still refuse, the court can execute the deed on their behalf.",
      conclusion: "Yes, for land/flat sales, you CAN force the seller to complete the registration. File a 'Suit for Specific Performance of Contract' in the Civil Court. Ensure you have: (1) a written and signed agreement, (2) proof of payment/earnest money, (3) that you are ready and willing to pay the remaining balance. Time limit: 3 years from the date the seller refused to perform.",
    },
    escalate: true,
    escalateReason: "Specific performance suits for property are complex and require precise drafting of pleadings. Consult a lawyer immediately.",
    relatedRules: ["con-specific-001", "con-limitation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-018",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["stop someone from breaching", "injunction contract", "", "court order stop", "temporary injunction"],
    question: "Can I get a court order to stop someone from violating our contract before they actually do it?",
    irac: {
      issue: "Whether a party can obtain preventive relief (injunction) to prevent an anticipated breach of contract.",
      rule: "Under the Specific Relief Act 1877, Sections 54-57, a temporary injunction can be granted to prevent a party from breaching a contract where the breach would cause irreparable harm that cannot be compensated by money. It is usually granted pending the final trial to preserve the status quo. The applicant must show: a prima facie case, balance of convenience in their favor, and irreparable injury if not granted.",
      application: "You have an exclusive distribution agreement. You discover your supplier is secretly shipping goods to another distributor in your territory. You can file for a temporary injunction to immediately stop the shipments while the main breach of contract suit is ongoing.",
      conclusion: "Yes, you can get a Temporary Injunction to freeze the situation. File an application under Order 39 Rules 1 & 2 of the Civil Procedure Code along with your main suit. You must prove: (1) You have a strong case, (2) You will suffer harm that money can't fix, (3) It's fair to stop the other party. Injunctions are powerful but require strong evidence and swift legal action.",
    },
    escalate: true,
    escalateReason: "Injunction applications require immediate court representation and detailed affidavit drafting.",
    relatedRules: ["con-specific-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-019",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["paid by mistake", "double payment", "  ", "wrong transfer", "recover mistaken payment"],
    question: "I accidentally transferred money to the wrong person/account  can I legally get it back?",
    irac: {
      issue: "The right to recover money paid under a mistake of fact when there is no actual contract.",
      rule: "Under Section 72 of the Contract Act 1872, a person to whom money has been paid, or anything delivered by mistake or under coercion, is obliged to repay or return it. This is a quasi-contract imposed by law to prevent unjust enrichment. The mistake must be of fact (e.g., wrong account number), not of law.",
      application: "You type the wrong bKash number and send BDT 50,000 to a stranger. The receiver has no legal right to keep it. You send a legal notice demanding return. If they refuse, you can file a 'Money Suit for Recovery' based on Section 72. The bank/bKash can also be formally notified to freeze the recipient's account temporarily.",
      conclusion: "Yes, money paid by mistake MUST be returned. Steps: (1) Immediately contact your bank/mobile money provider to freeze or reverse if possible. (2) Send a formal legal notice to the recipient under Section 72. (3) If they don't return it within the deadline (usually 7-15 days), file a civil money recovery suit. (4) In extreme cases of refusal, it can also be treated as criminal misappropriation under the Penal Code.",
    },
    escalate: false,
    relatedRules: ["con-quasi-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-020",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["betting agreement", "gambling contract", " ", "wagering contract", "fantasy cricket legal"],
    question: "Are betting or gambling agreements legally enforceable in Bangladesh?",
    irac: {
      issue: "The legal status of wagering agreements and whether prize money from betting can be recovered in court.",
      rule: "Under Section 30 of the Contract Act 1872, agreements by way of wager are void. A wager is a promise to pay money on the determination of an uncertain event, where neither party has any interest other than the winning/losing of money. Exceptions: games of skill (like puzzle competitions where success depends on knowledge), horse racing (under specific local club rules), and forward contracts in commodities (regulated exchanges).",
      application: "Two people bet BDT 10,000 on a cricket match. This is a wagering agreement  void. If the loser refuses to pay, the winner cannot sue to recover the money. Similarly, online betting apps are illegal and their 'contracts' are unenforceable. However, a trading competition on a stock exchange based on analytical skill might not be a wager.",
      conclusion: "Betting and gambling agreements are completely VOID. You cannot sue to recover gambling debts or winnings. Furthermore, participating in or operating gambling is a criminal offense under the Penal Code. Exception: Prizes from games of SKILL (not pure chance) may be enforceable. Do not enter into financial agreements based on uncertain sports/event outcomes.",
    },
    escalate: false,
    relatedRules: ["con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-021",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["gave goods for repair", "goods damaged at shop", "  ", "bailee damaged goods", "tailor ruined cloth"],
    question: "I gave my goods to someone for repair/safekeeping and they were damaged or lost  what can I do?",
    irac: {
      issue: "The liability of a person who receives goods for a specific purpose (bailment) if the goods are damaged or lost.",
      rule: "Under Sections 148-154 of the Contract Act 1872, this is a contract of bailment. The bailee (person holding the goods) must take reasonable care of the goods. If they are negligent and the goods are damaged, the bailee is liable to compensate the bailor (owner) for the full market value. If the bailee mixes the goods with their own without consent, they are absolutely liable for the whole mixture.",
      application: "You give your laptop to a repair shop. The shop leaves it on the counter and it is stolen. The shop is liable because they failed to take reasonable care. You can claim the full market value of the laptop. If you gave a gold chain to a friend for safekeeping and they lost it, they must compensate you.",
      conclusion: "The person holding your goods (bailee) MUST take reasonable care. If damaged/lost due to their negligence: (1) Send a legal notice demanding compensation for the full market value, (2) If they refuse, file a civil suit for damages. To protect yourself: always get a written receipt when handing over goods (it proves the bailment and the condition of the goods).",
    },
    escalate: false,
    relatedRules: ["con-bailment-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-022",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["end a contract", "terminate agreement", " ", "how to cancel contract", "discharge of contract"],
    question: "How can a contract be legally terminated without going to court?",
    irac: {
      issue: "The legal methods for discharging (ending) a contract by the parties themselves.",
      rule: "Under Sections 62-75 of the Contract Act 1872, a contract can be discharged without court intervention by: (1) Performance  both parties do what they promised, (2) Mutual Agreement  both parties agree to cancel it (novation or rescission), (3) Impossibility  frustration (S.56), (4) Lapse of Time  if there is a time limit and it expires, (5) Occurrence of an event specified in the contract.",
      application: "You have a 1-year service contract. After 6 months, both you and the client agree the project isn't working out. You both sign a 'Mutual Termination Agreement' stating that from today, no party owes the other anything. The contract is legally discharged by mutual agreement.",
      conclusion: "To end a contract cleanly without court: (1) Check if there is a termination clause (usually requires 30/60 days written notice), (2) If not, negotiate a 'Mutual Rescission'  both parties sign a new document cancelling the old one, (3) Ensure all pending obligations (payments, returns) are settled in the termination document. A properly signed mutual termination prevents future lawsuits.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-023",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["digital signature", "e-contract valid", " ", "electronic agreement", "sign pdf contract"],
    question: "Is a contract signed via digital signature or PDF e-signature legally valid?",
    irac: {
      issue: "The legal validity of electronic signatures and digital contracts under Bangladesh law.",
      rule: "Under the Information and Communication Technology (ICT) Act 2006, electronic records and digital signatures have the same legal weight as physical documents and handwritten signatures, provided they are verified by a licensed Certifying Authority. However, certain documents under the Registration Act 1908 (e.g., sale of immovable property, leases over 1 year) MUST still be physically registered on non-judicial stamp paper.",
      application: "You sign an NDA or a service agreement using Adobe Sign or DocuSign. This is legally valid and enforceable for commercial contracts. However, you CANNOT digitally sign a deed of sale for a plot of land  that must be physically signed on stamp paper and registered with the Sub-Registrar.",
      conclusion: "Yes, digital contracts are legally valid for most commercial agreements (services, supply, NDA, employment). They are NOT valid for: (1) Sale of land/property, (2) Leases over 1 year, (3) Mortgages, (4) Wills. These must be physical, stamped, and registered. For high-value digital contracts, use a Certifying Authority-verified digital signature for maximum security.",
    },
    escalate: false,
    relatedRules: ["con-formation-001", "con-stamp-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-024",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["unstamped agreement", "agreement not stamped", " ", "can i use unstamped paper", "stamp deficiency"],
    question: "What happens if my agreement is not properly stamped? Is it completely useless?",
    irac: {
      issue: "The legal consequence of presenting an unstamped or under-stamped document in court.",
      rule: "Under Section 35 of the Stamp Act 1899, an instrument not properly stamped is inadmissible in evidence. No court will allow it to be used to prove any matter. However, Section 61 allows the court to impound the document and give the party an opportunity to pay the proper stamp duty plus a penalty (up to 10 times the deficiency) to cure the defect.",
      application: "You have an unsigned but agreed upon term sheet printed on plain A4 paper. You sue for breach. The court will refuse to look at the A4 paper because it has no stamp. You must pay the required stamp duty (e.g., BDT 300 for an agreement) plus penalty (e.g., BDT 3,000) to the government to make it admissible.",
      conclusion: "An unstamped agreement is NOT necessarily void, but it is INADMISSIBLE in court until you pay the stamp duty + penalty (up to 10x). Always stamp agreements properly before signing: (1) Buy the correct non-judicial stamp paper or use e-stamping ( treasury.gov.bd ), (2) Print/write the agreement on it, (3) Sign it. It is much cheaper to stamp upfront than to pay the 10x penalty later.",
    },
    escalate: false,
    relatedRules: ["con-stamp-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-025",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["both parties mistaken", "mistake in contract", " ", "mutual mistake", "error in agreement"],
    question: "Both parties made a mistake about a fundamental fact in our contract  is it valid?",
    irac: {
      issue: "The effect of a bilateral mistake regarding a fundamental fact essential to the agreement.",
      rule: "Under Section 20 of the Contract Act 1872, an agreement is void if both parties are under a mistake as to a matter of fact essential to the agreement. (Note: Mistake of law is generally not an excuse under S.21, unless it's a mistake of Bangladeshi law). Unilateral mistake (only one party is mistaken) does not make a contract void unless the other party knew of the mistake.",
      application: "A agrees to buy a specific cow from B. Both believe the cow is fertile, but it is actually sterile. The contract is void because both were mistaken about an essential fact. However, if A thought the cow was sterile and B thought it was fertile, A cannot back out (unilateral mistake).",
      conclusion: "If BOTH parties were mistaken about a core fact (e.g., subject matter doesn't exist, quantity is fundamentally wrong), the contract is VOID. You can simply walk away and claim refunds. If only YOU were mistaken, the contract is generally binding. To avoid this: include a 'Representations and Warranties' clause where the other party guarantees the facts are true.",
    },
    escalate: false,
    relatedRules: ["con-void-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-026",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["silence as acceptance", "no reply means yes", "   ", "didn't reply to offer"],
    question: "If I send an offer and the other person doesn't reply, does their silence mean they accepted?",
    irac: {
      issue: "Whether silence or inaction can constitute valid acceptance of an offer.",
      rule: "Under the general principles of the Contract Act 1872, silence does not amount to acceptance. The offeree is not obligated to respond. Exception: If the offeree has a duty to speak (e.g., prior course of dealing where silence meant acceptance, or they intentionally let the offeror believe silence means acceptance and the offeror acted on that belief), silence may be treated as acceptance.",
      application: "A supplier sends a quote. The buyer never replies but receives the goods and starts using them. The buyer's initial silence was NOT acceptance, but their ACT of using the goods implies acceptance. However, if the supplier just sends a quote and the buyer ignores it, no contract is formed.",
      conclusion: "Generally, NO  silence is not acceptance. A contract is NOT formed just because someone didn't say 'no'. Acceptance must be positive communication (words or conduct). To protect yourself as a sender: add a clause like 'If we do not hear from you by [Date], we will assume this offer is accepted and proceed with delivery'  though even this is legally weak, it creates a strong commercial argument.",
    },
    escalate: false,
    relatedRules: ["con-offer-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-027",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["indemnity clause", "hold harmless", " ", "indemnify me", "who pays if sued"],
    question: "What does an 'indemnity clause' in a contract actually do?",
    irac: {
      issue: "Understanding the legal effect and scope of an indemnity clause in commercial agreements.",
      rule: "Under Section 124 of the Contract Act 1872, an indemnity is a promise to save the other party from harm caused by the promisor's conduct or a third party. In commercial contracts, an indemnity clause shifts the financial risk of specific losses or lawsuits from one party to the other. The indemnified party can recover all damages, costs, and sums they are compelled to pay in a lawsuit.",
      application: "A landlord puts a clause in the lease: 'Tenant shall indemnify the landlord against all claims arising from the tenant's use of the premises.' If a customer sues the landlord because they slipped in the tenant's shop, the tenant must pay the landlord's legal fees and any damages awarded to the customer.",
      conclusion: "An indemnity clause says: 'If X happens, I will pay the costs, not you.' It covers: legal defense costs, court-ordered damages, and settlement amounts. To draft a strong one: (1) Specify exactly what events trigger the indemnity, (2) Say 'including attorney's fees', (3) Make it 'survive termination' (lasts even after the contract ends). Note: Courts may not enforce indemnity clauses for the other party's own gross negligence.",
    },
    escalate: false,
    relatedRules: ["con-indemnity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-028",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["seller didn't deliver", "late delivery goods", "  ", "non-delivery", "buyer rights late delivery"],
    question: "A supplier failed to deliver goods on the agreed date  what are my rights as a buyer?",
    irac: {
      issue: "Remedies available to a buyer when a seller fails to deliver goods on time or at all.",
      rule: "Under the Sale of Goods Act 1930, Sections 55-56, if the seller fails to deliver, the buyer can: (1) sue for damages for non-delivery, (2) sue for specific performance (force delivery), or (3) buy from a third party and claim the difference in price from the defaulting seller. If time is 'of the essence' (explicitly stated), the buyer can reject the goods even if delivered late.",
      application: "You ordered raw materials for your factory arriving on the 1st. The contract says 'Time is of the essence.' They arrive on the 15th, causing your factory to shut down. You can reject the goods, cancel the contract, buy from the market at a higher price, and sue the original supplier for the price difference + factory shutdown losses.",
      conclusion: "Your rights: (1) Cancel the contract and claim refund, (2) Buy elsewhere and sue for the extra cost, (3) Sue for specific delivery, (4) Claim damages for business losses caused by the delay (if 'time is of the essence' was in the contract). Immediately send a notice of breach to the supplier documenting your losses.",
    },
    escalate: false,
    relatedRules: ["con-soga-001", "con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-029",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["buyer not paying", "refusing to pay", "   ", "buyer default", "seller rights unpaid goods"],
    question: "I delivered goods but the buyer is refusing to pay  what can I do?",
    irac: {
      issue: "A seller's remedies when the buyer takes possession of goods but fails to make payment.",
      rule: "Under the Sale of Goods Act 1930, when the buyer is in possession of goods and defaults on payment, the seller has a 'seller's lien' (right to retain goods if still in possession), right of stoppage in transit (stop the goods if they are in transit), and right of resale (resell the goods and sue for the difference). Under S.55, the seller can also simply sue for the price of the goods.",
      application: "You send goods via courier. The buyer receives them but doesn't pay. Since they already have possession, your lien is gone. You must sue for the price (a money suit). If you find out they went bankrupt BEFORE delivery, you can stop the courier (stoppage in transit) and take the goods back.",
      conclusion: "If the buyer has the goods and won't pay: (1) Send a formal demand notice, (2) File a 'Suit for Recovery of Price' in Civil Court, (3) You can claim interest on the overdue amount. To protect yourself in the future: use a 'Retention of Title' clause (ownership passes only on full payment) or a 'Right of Resale' clause (if they don't pay in 7 days, you can take goods back).",
    },
    escalate: false,
    relatedRules: ["con-soga-001", "con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-030",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["time limit to sue", "3 years over", " ", "limitation expired", "can i still sue"],
    question: "It has been more than 3 years since the contract breach  can I still file a case?",
    irac: {
      issue: "The effect of the Limitation Act 1908 on a contract claim that has passed the 3-year statutory deadline.",
      rule: "Under Article 113 of the First Schedule of the Limitation Act 1908, a suit for breach of contract or specific performance must be filed within 3 years from the date the cause of action arises (usually the date of breach or the date the breach was discovered). If the 3 years expire, the suit is 'time-barred'. Courts will dismiss time-barred suits at the threshold, regardless of how valid the claim is.",
      application: "A supplier was supposed to deliver on Jan 1, 2020. They breached on Jan 2, 2020. You have until Jan 1, 2023, to file a suit. If you file on Jan 5, 2023, the defendant will file a 'Limitation Objection', and the court will dismiss your case without hearing the merits.",
      conclusion: "If 3 years have passed since the breach, your case is highly likely to be DISMISSED as time-barred. Exceptions: (1) If you can prove you couldn't have discovered the breach earlier (e.g., hidden fraud), the clock might start later. (2) If you sent a written acknowledgment of debt and the other party signed it, the 3-year clock RESETS from that signature date. Do NOT delay legal action on contract disputes.",
    },
    escalate: true,
    escalateReason: "If the limitation period is near expiry or slightly crossed, only a lawyer can evaluate if exceptions (like acknowledgment of debt) apply.",
    relatedRules: ["con-limitation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-031",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["no termination clause", "how to end without clause", "    ", "reasonable notice contract"],
    question: "Our contract doesn't have a termination clause  how can we end it?",
    irac: {
      issue: "How to terminate a contract that is silent on the procedure, duration, or notice period for termination.",
      rule: "Under the Contract Act 1872, if a contract is silent on termination and is of a recurring nature (like a service or lease), the law implies a 'reasonable notice' period. What is 'reasonable' depends on the nature of the contract, industry practice, and time needed to wind down. For a specific one-time task, it ends upon performance or breach. If it's an 'at-will' style contract, it can be terminated by either party giving reasonable notice.",
      application: "A digital marketing agency is hired without a written contract specifying duration. After 2 years, the client wants to stop. The agency cannot force the client to stay forever. The client must give 'reasonable notice'  for marketing, usually 30 to 60 days  to allow the agency to wind down campaigns and handover assets.",
      conclusion: "Without a termination clause, you can still end the contract by giving 'Reasonable Notice'. What is reasonable? (1) Monthly services: usually 30 days. (2) Executive employment: 90 days. (3) Complex projects: time to find a replacement. Send a formal written notice stating the date of termination. To avoid this ambiguity, ALWAYS include a termination clause specifying the exact notice period.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-032",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["undue influence", "elderly pressured", " ", "doctor patient contract", "trusted person contract"],
    question: "What is 'undue influence' and how does it make a contract voidable?",
    irac: {
      issue: "Understanding when a contract is voidable due to one party exploiting a position of trust or dominance over the other.",
      rule: "Under Section 16 of the Contract Act 1872, a contract is voidable if the consent of one party was obtained by undue influence. This occurs when one party is in a position to dominate the will of the other (e.g., doctor-patient, parent-child, employer-employee, landlord-tenant) and uses that position to obtain an unfair advantage. The burden of proof shifts to the dominant party to show the transaction was fair.",
      application: "An elderly person, heavily reliant on their nephew for care, transfers their house to the nephew for BDT 1 lakh when the house is worth BDT 1 crore. The nephew was in a dominant position. The contract is voidable for undue influence. The elderly person (or their heirs) can cancel the transfer.",
      conclusion: "Undue influence applies when there is a TRUST relationship and an UNFAIR transaction. If you are accused of undue influence, you must prove the deal was fair, fully understood, and independently advised. If you are a victim of undue influence, file a suit to set aside the contract within 3 years of the transaction. Always ensure vulnerable parties get independent legal advice before signing.",
    },
    escalate: true,
    escalateReason: "Undue influence cases require strong evidence of the power dynamic and often involve property disputes requiring swift legal action.",
    relatedRules: ["con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-033",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["as is where is", "caveat emptor", " ", "bought as is", "no warranty"],
    question: "I bought something 'As Is Where Is'  can I still complain if it's defective?",
    irac: {
      issue: "Whether an 'As Is Where Is' clause completely protects the seller from all liability for defects.",
      rule: "Under Section 16 of the Sale of Goods Act 1930, there is an implied condition that goods are of merchantable quality, unless the defect is specifically brought to the buyer's attention before the contract is made, or the buyer examines the goods and the defect *should* have been found. An 'As Is' clause overrides implied warranties if it clearly puts the buyer on notice that they are accepting all risks.",
      application: "You buy a used generator 'As Is Where Is' at an auction. It breaks after 2 days. You cannot sue the seller because 'As Is' means you accepted it with all faults. However, if the seller actively lied and said 'This generator works perfectly' when they knew it was broken, that is active fraud  the 'As Is' clause does not protect against fraud.",
      conclusion: "An 'As Is Where Is' clause generally means BUYER BEWARE  you accept the goods with all visible and hidden defects. You CANNOT claim breach of warranty. Exception: You CAN still sue if: (1) The seller committed active fraud (lied about the defect), (2) The seller has no title to sell the goods (stolen goods), (3) The goods don't match their basic description (e.g., bought a Honda, got a Yamaha).",
    },
    escalate: false,
    relatedRules: ["con-soga-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-034",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["contingent contract", "conditional agreement", " ", "contract depends on future event", "if then contract"],
    question: "What is a contingent contract and when does it become binding?",
    irac: {
      issue: "The legal nature of contracts that depend on a future uncertain event happening (or not happening).",
      rule: "Under Sections 31-36 of the Contract Act 1872, a contingent contract is to do or not do something if some event, collateral to the contract, does or does not happen. It becomes enforceable only when the contingent event happens. It is void if the event becomes impossible, or is of an immoral/illegal nature.",
      application: "A contracts to pay B BDT 1 lakh if B's house burns down (this is an insurance contract). The contract is contingent on the house burning down. If the house never burns down, A never pays. If the house burns down, the contract becomes enforceable immediately. If the house burns down due to B's arson, the contract is void (illegal event).",
      conclusion: "A contingent contract is an 'If X happens, then Y happens' agreement. It is NOT enforceable until the 'If X' occurs. Rules: (1) If the event becomes impossible, the contract is void. (2) If the event is made impossible by the person who would benefit, they cannot claim the benefit. (3) Contingent on an uncertain future date: enforceable when that date arrives.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-035",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["terrible service", "service not up to standard", " ", "refuse to pay for bad service", "breach of implied condition"],
    question: "I paid for a service but it was extremely poor quality  can I refuse to pay the full amount?",
    irac: {
      issue: "Whether a client can withhold payment or claim a reduction for services that do not meet expected standards.",
      rule: "Under the Contract Act 1872, there is an implied condition in service contracts that the service will be performed with reasonable skill and care. If the service is fundamentally defective or incomplete, the provider is in breach of contract. The client can claim damages proportional to the defect, or in cases of total failure, refuse payment entirely.",
      application: "You hire a plumber to fix a leak. He charges BDT 5,000 but does a terrible job and the leak persists. This is a breach of the implied condition of skill/care. You can refuse to pay the BDT 5,000, or if you already paid, demand a refund. You cannot, however, claim BDT 50,000 in emotional distress  only actual financial loss.",
      conclusion: "If the service is sub-standard: (1) Document the poor quality (photos, emails, expert opinion if needed), (2) Send a notice stating the service breached the contract, (3) Refuse final payment OR demand a proportional refund (e.g., if half the work was good, pay half), (4) Hire someone else to fix it and deduct the cost from the original payment. Do NOT just silently withhold payment  communicate your reasons clearly in writing.",
    },
    escalate: false,
    relatedRules: ["con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-036",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["mental agony damages", "emotional distress contract", "  ", "pain and suffering contract"],
    question: "Can I claim compensation for mental agony or emotional distress caused by a contract breach?",
    irac: {
      issue: "Whether non-physical, emotional damages are recoverable in a breach of contract suit.",
      rule: "Under Section 73 of the Contract Act 1872, compensation is restricted to losses that naturally arise from the breach or are in the contemplation of the parties at the time of making the contract. Generally, mental agony, emotional distress, or pain and suffering are NOT compensable in contract law (unlike tort law). Exception: If the whole purpose of the contract was to provide peace of mind, enjoyment, or emotional comfort (e.g., booking a honeymoon suite, hiring a wedding photographer).",
      application: "A supplier fails to deliver raw materials. Your factory stops and you suffer stress. You CANNOT claim 'mental agony' damages. You can only claim the actual financial loss (loss of profit, cost of buying from another supplier). However, if you booked a premium wedding photography package and they didn't show up, you CAN claim damages for the loss of joy/emotional distress because that was the sole purpose of the contract.",
      conclusion: "Generally, NO  contract law only compensates financial losses, not emotional distress. Exception: Contracts for pleasure, comfort, or peace of mind. If you want to claim mental agony, you must file a civil suit under Tort law (e.g., nuisance, defamation, negligence) rather than breach of contract. Always quantify your financial losses precisely in contract disputes.",
    },
    escalate: false,
    relatedRules: ["con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-037",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["agreement vs contract", "is every agreement a contract", "  ", "legally binding difference"],
    question: "What is the exact difference between an 'Agreement' and a 'Contract'?",
    irac: {
      issue: "Distinguishing between an agreement (a wider concept) and a contract (a legally enforceable subset).",
      rule: "Under Section 2(h) of the Contract Act 1872, 'An agreement enforceable by law is a contract.' Section 2(e) defines an agreement as 'every promise and every set of promises forming the consideration for each other.' Therefore, all contracts are agreements, but NOT all agreements are contracts. An agreement becomes a contract only when it meets the requirements of Section 10: free consent, competency, lawful consideration, and lawful object.",
      application: "You and a friend agree to go to the cinema on Friday. This is an agreement (a promise), but it is NOT a contract because there is no intention to create legal relations and no consideration. You agree to buy a car for BDT 10 lakh. This IS a contract (offer, acceptance, consideration, intention to be bound).",
      conclusion: "Agreement = Offer + Acceptance (Enforceable OR Unenforceable). Contract = Agreement + Enforceability (meets all S.10 conditions). If an agreement lacks consideration, involves a minor, or is for an illegal purpose, it is an agreement but NOT a contract. In business, always assume your agreements need to meet all contract criteria to be safe.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-038",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["promissory estoppel", "promise without consideration", "  ", "broke a free promise", "detrimental reliance"],
    question: "Someone made a free promise, I relied on it to my loss  can I enforce it?",
    irac: {
      issue: "Whether a promise made without consideration can be enforced if the other party relied on it to their detriment.",
      rule: "Promissory Estoppel is an equitable doctrine recognized in Bangladesh (Central Inland Water Transport v. Brojo Nath Ganguly). If a person makes a clear promise, knowing it will be relied upon, and the other party does rely on it to their financial detriment, the promisor is 'estopped' (prevented) from going back on their promise, even if there was no formal consideration.",
      application: "A landlord promises a tenant they won't increase rent for 3 years. The tenant spends BDT 5 lakh renovating the shop based on this promise. After 1 year, the landlord doubles the rent. The tenant can use promissory estoppel to prevent the rent increase because they suffered a financial detriment relying on the promise.",
      conclusion: "Yes, under Promissory Estoppel, a promise without consideration CAN be enforced if: (1) The promise was clear and unambiguous, (2) You relied on it, (3) You suffered an actual financial loss/detriment because of that reliance, (4) It would be unjust to allow the promisor to back out. This is an 'equitable defense'  you use it in court to stop someone from breaking their word, rather than filing a standard breach of contract suit.",
    },
    escalate: true,
    escalateReason: "Promissory estoppel requires strong evidence of detrimental reliance and is a complex equitable argument.",
    relatedRules: ["con-consideration-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-039",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["landlord forfeit lease", "evict for non-payment", "   ", "lease breach", "arrear of rent"],
    question: "Can a landlord cancel a lease agreement and evict a tenant for not paying rent?",
    irac: {
      issue: "The landlord's right to forfeit a lease and recover possession due to non-payment of rent or breach of lease terms.",
      rule: "Under the Specific Relief Act 1877 (and standard lease covenants), if a lease contains a clause allowing forfeiture for non-payment of rent, the landlord can forfeit the lease. However, under the Section 114 of the Transfer of Property Act 1882 and the Premises Tenancy (Eviction Control) laws in Bangladesh (e.g., in Dhaka/Chattogram), a landlord cannot simply lock out a tenant. They must file an eviction suit in court.",
      application: "Tenant hasn't paid rent for 6 months. The lease says 'Non-payment for 2 months allows landlord to re-enter.' The landlord CANNOT just change the locks or cut off utilities. They must send a formal notice demanding rent and stating intent to forfeit. If unpaid, file an eviction suit (Ejectment Suit) in the Rent Controller or Civil Court.",
      conclusion: "Yes, non-payment allows lease cancellation, BUT you MUST follow legal procedure: (1) Send a formal demand notice for arrears, (2) If the lease has a forfeiture clause, invoke it, (3) File an Ejectment/Eviction suit in the appropriate court. Self-help (changing locks, forceful eviction) is illegal and can result in criminal charges against the landlord. The process takes 6-18 months in court.",
    },
    escalate: true,
    escalateReason: "Eviction and lease forfeiture are heavily regulated by rent control laws. Wrongful eviction attempts lead to criminal liability.",
    relatedRules: ["con-specific-001", "con-breach-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-040",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["implied terms", "custom and usage", " ", "unwritten contract terms", "trade practice contract"],
    question: "Can a contract have terms that were never actually written down or spoken?",
    irac: {
      issue: "Whether unwritten, implied terms based on custom, usage of trade, or prior dealings are legally binding.",
      rule: "Yes. Under the Contract Act 1872 and Sale of Goods Act 1930, terms can be implied by: (1) Custom/Usage of trade  what is standard in that specific industry, (2) Course of dealing  how the parties have behaved in the past, (3) Implied by law  statutory protections (e.g., merchantable quality). These implied terms carry the same weight as written terms unless explicitly excluded by a written clause.",
      application: "You order '1 ton of rice' from a wholesaler without specifying packaging. The trade custom in Bangladesh is to pack it in 50kg jute bags. The seller delivers it loose in a truck. You can enforce the '50kg jute bag' term because it's an implied term by trade custom, even though it wasn't written in the purchase order.",
      conclusion: "Yes, unwritten terms ARE binding if they are: (1) Standard industry customs, (2) Established by your past dealings with this supplier, (3) Required by law (SOGA implied conditions). To EXCLUDE implied terms, you must explicitly state in your written contract: 'All implied terms, conditions, and warranties are hereby excluded.' This is common in B2B contracts to strip away legal protections.",
    },
    escalate: false,
    relatedRules: ["con-soga-001", "con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-041",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["minor return goods", "minor bought phone", "  ", "minor restitution", "restore minor"],
    question: "A minor bought an expensive item from my shop  can I force them to keep it or lose the money?",
    irac: {
      issue: "The rights of an adult seller when a minor tries to return goods and claim a refund under the void contract rule.",
      rule: "Under Section 65 of the Contract Act 1872 and the doctrine from Mohori Bibee v. Dharmodas Ghose, a minor's agreement is void. When a contract is void, any advantage received must be restored. However, courts have held that a minor can only return goods if they still have them and haven't disposed of them. The minor cannot be forced to 'perform' the contract, but they must return what they have.",
      application: "A 17-year-old buys a BDT 80,000 laptop using his own savings. He uses it for 3 months, drops it, and then demands a full refund claiming he is a minor. The shop can argue that the minor cannot get a refund because: (1) The laptop is now used/damaged, (2) The minor has benefited from it, (3) Restoring the minor to original position doesn't mean giving a brand-new refund for a used item.",
      conclusion: "If a minor wants to return goods: (1) They must return the actual goods, (2) The goods must be in reasonably good condition, (3) The seller can deduct depreciation for usage. The seller CANNOT sue the minor for the balance, but they don't have to give a 100% brand-new refund if the goods are used. Always check NID for high-value purchases to avoid this trap entirely.",
    },
    escalate: false,
    relatedRules: ["con-minor-001", "con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-042",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["arbitration clause", "go to court or arbitrator", " ", "dispute resolution clause", "arbitration act"],
    question: "Our contract has an 'Arbitration Clause'  does this mean I cannot go to civil court?",
    irac: {
      issue: "The effect of an arbitration clause on the parties' right to approach the regular civil courts.",
      rule: "Under the Arbitration Act 2001, if a contract contains a valid arbitration clause, the parties must resolve their dispute through arbitration rather than civil court. If a party ignores the clause and files a civil suit directly, the other party can file an application under Section 8 of the Arbitration Act to refer the matter to arbitration. Exceptions: matters involving criminal offenses, injunctions for preservation of subject matter, or interim relief can still go to court.",
      application: "Your IT service agreement says 'All disputes shall be resolved by arbitration in Dhaka.' The developer breaches the contract. If you file a money suit directly in the Joint District Judge Court, the developer's lawyer will immediately file a Section 8 application, and the court will likely send you to arbitration, wasting your time and court fees.",
      conclusion: "Yes, an Arbitration Clause generally BLOCKS you from going to civil court. You must appoint an arbitrator (or apply to the court to appoint one if the other party refuses). Pros of arbitration: faster, private, flexible. Cons: expensive arbitrator fees, limited grounds to appeal. Always read the dispute resolution clause carefully before suing.",
    },
    escalate: true,
    escalateReason: "Navigating between civil courts and arbitration requires precise procedural steps under the Arbitration Act 2001.",
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-043",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["drafting breach notice", "legal notice format", " ", "demand letter", "pre-litigation notice"],
    question: "How do I draft an effective legal demand notice for breach of contract?",
    irac: {
      issue: "The essential elements that must be included in a pre-litigation legal notice to make it effective and legally sound.",
      rule: "While not always legally mandatory for all contract suits, a legal notice is crucial for: (1) Clearly communicating the breach, (2) Demanding specific relief within a timeframe (usually 15-30 days), (3) Acting as evidence of the demand, and (4) In some cases (e.g., Section 80 of the Code of Civil Procedure for government contracts), it is mandatory before filing suit.",
      application: "You are drafting a notice because a supplier didn't deliver. The notice must state: Date of contract, exact clause breached, loss suffered, exact amount demanded, and a deadline. If you just write an angry letter without legal facts, it holds no weight in court.",
      conclusion: "An effective legal notice must include: (1) Sender & Recipient details, (2) Date and reference to the contract, (3) Specific facts of the breach, (4) The legal right you are invoking (e.g., S.73 of Contract Act), (5) Exact financial demand, (6) Clear deadline (e.g., '15 days from receipt'), (7) Consequence of failure ('Otherwise legal action will be initiated'). Always send it via legal courier with acknowledgment (AD) and keep a copy.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-limitation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-044",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["escrow agreement", "holding money until condition met", "", "conditional payment", "third party holding funds"],
    question: "What is an Escrow Agreement and when should I use one?",
    irac: {
      issue: "Understanding the purpose and legal mechanics of an escrow arrangement in contract law.",
      rule: "An escrow is an arrangement where a neutral third party (the escrow agent) holds money or property on behalf of two other parties until a specific condition is met. Under the Contract Act, it operates as a conditional delivery. Once the condition is fulfilled, the escrow agent releases the funds to the designated party. If the condition fails, the funds are returned.",
      application: "You are buying a company. You don't want to pay the full BDT 50 lakh upfront because the seller might have hidden liabilities. You put BDT 50 lakh in an escrow account. The condition is 'Completion of due diligence in 30 days.' If due diligence is clear, the bank releases money to the seller. If red flags are found, the money returns to you.",
      conclusion: "Use Escrow when: (1) High-value transactions (real estate, M&A), (2) You don't fully trust the other party yet, (3) Performance depends on a future condition. Who can be an escrow agent? A bank, a trusted law firm, or a specialized escrow company. Cost is usually 0.5% - 1% of the escrow amount. It prevents both payment fraud and delivery fraud.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-045",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["amend contract after signing", "change contract terms", " ", "variation of contract", "add clause later"],
    question: "Can we change or add terms to a contract after it has been signed?",
    irac: {
      issue: "The legal process for modifying an existing, valid contract.",
      rule: "Under Section 62 of the Contract Act 1872, parties to a contract can alter or rescind the contract by mutual consent. This is called a 'variation of contract' or 'addendum'. The variation must be supported by new consideration (unless it is a written variation as required by the original contract) and must follow the same formalities as the original contract (e.g., if the original was stamped and registered, the variation should ideally be too).",
      application: "You signed a 1-year lease for BDT 20,000/month. After 6 months, you and the landlord orally agree to reduce it to BDT 18,000/month. This oral variation is legally valid under S.62, but impossible to prove in court. If the landlord later demands BDT 20,000, they will win because you have no written proof of the variation.",
      conclusion: "Yes, you can amend a signed contract by mutual agreement (Variation/Addendum). CRITICAL RULES: (1) Put EVERY change in writing, (2) Both parties must sign the amendment, (3) If the original contract required stamping/registration, the amendment might need it too, (4) State clearly which clause is being replaced. Never rely on oral variations for important contracts.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-046",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["rescission vs termination", "cancel contract completely", "  ", "void ab initio vs future"],
    question: "What is the difference between 'Rescission' and 'Termination' of a contract?",
    irac: {
      issue: "Understanding the legal distinction because they have completely different effects on the parties' rights and obligations.",
      rule: "Termination ends the contract FROM THE DATE OF TERMINATION moving forward. Past obligations remain enforceable (e.g., you still have to pay for goods received before termination). Rescission (under the Specific Relief Act) cancels the contract AB INITIO  as if it never existed. Both parties must be restored to their original pre-contract positions (restitution).",
      application: "You have a 2-year supply contract. After 1 year, you terminate it due to a minor breach. You still have to pay for the 1 year of goods you received. If you RESCIND the contract (e.g., due to fraud in the initial agreement), you return all goods received, they return all your money  it's as if the 2 years never happened.",
      conclusion: "Termination = 'We stop now, but we settle what already happened.' Rescission = 'We pretend this contract never existed at all.' Use Termination for: late delivery, minor breaches, end of term. Use Rescission for: fraud, misrepresentation, fundamental mistake. Rescission is much harder to get from a court because it requires unwinding everything.",
    },
    escalate: false,
    relatedRules: ["con-void-001", "con-specific-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-047",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["party dies", "contract after death", "  ", "inherit contract", "personal service contract death"],
    question: "What happens to a contract if one of the parties dies?",
    irac: {
      issue: "Whether a contract survives the death of a party or is automatically terminated.",
      rule: "Under Section 37 and related principles of the Contract Act 1872, it depends on the nature of the contract. If the contract involves personal skill, taste, or trust (e.g., painting a portrait, personal coaching, employment), it is discharged by the death of the promisor. If it is a commercial contract not dependent on personal skill (e.g., sale of goods, repayment of a loan, lease of property), the contract does NOT die  it passes to the deceased's legal heirs/estate.",
      application: "You hired a famous artist to paint your portrait. The artist dies. The contract is terminated  you cannot force the artist's son to paint it. However, if A owed B BDT 10 lakh on a loan agreement and A dies, B can sue A's legal heirs (wife/children) to recover the BDT 10 lakh from A's estate/assets.",
      conclusion: "Death of a party does NOT automatically end all contracts. Personal service/skill contracts = TERMINATED on death. Commercial/property/debt contracts = SURVIVE death, and the deceased's estate/heirs are liable. If you are dealing with an elderly individual or someone with health issues, ensure your contract includes an assignment/novation clause to handle this scenario.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-048",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["third party beneficiary", "can third person sue", "  ", "stranger to contract", "privity of contract"],
    question: "Can a person who is not a party to the contract sue if the contract benefits them?",
    irac: {
      issue: "Whether a third party (stranger to the contract) has legal standing to enforce the contract.",
      rule: "Under the common law doctrine of 'Privity of Contract', which applies in Bangladesh, only parties to a contract can sue or be sued on it. A stranger to the contract (even if the contract was made for their benefit) generally cannot enforce it. Exception: Trusts (beneficiary can enforce), and if the third party provides the consideration.",
      application: "A buys a life insurance policy from B, naming C (his wife) as the nominee/beneficiary. If B (the insurance company) refuses to pay after A's death, C (the wife) CAN sue B, even though C didn't sign the contract. This is a recognized exception to privity. But if A contracts with a builder to build a house for C's birthday, C cannot sue the builder if the builder fails  only A can.",
      conclusion: "General Rule: 'Stranger to a contract' CANNOT sue (Doctrine of Privity). Exceptions: (1) Life insurance/Trust beneficiaries, (2) If the third party paid the consideration, (3) If there is an assignment of the contract rights. To protect third parties, always include an express clause allowing them to enforce their rights, or formally assign your contractual rights to them.",
    },
    escalate: false,
    relatedRules: ["con-formation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-049",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["illegal contract", "against public policy", " ", "contract to commit crime", "immoral agreement"],
    question: "If a contract is for an illegal purpose, can I still sue to get my money back?",
    irac: {
      issue: "Whether a party can recover money or benefits paid under a contract that is illegal or against public policy.",
      rule: "Under Section 23 and Section 65 of the Contract Act 1872, agreements whose object or consideration is forbidden by law, or is immoral/opposed to public policy, are void. Under the principle of *ex turpi causa non oritur actio* (from a dishonorable cause an action does not arise), courts will leave the parties where they are. Generally, you CANNOT recover money paid under an illegal contract.",
      application: "A pays B BDT 5 lakh to bribe a government official for a tender. B takes the money but doesn't bribe the official. A cannot sue B to recover the BDT 5 lakh because the object of the agreement was illegal (bribery). The court will refuse to help either party.",
      conclusion: "If the contract is illegal (e.g., bribery, smuggling, gambling, violating government regulations), you CANNOT sue to recover your money. The court will dismiss the case immediately. Exception: If you were tricked into an illegal contract and you withdraw BEFORE the illegal act is committed, you might recover your money. Never sign contracts with illegal clauses  you lose all legal protection.",
    },
    escalate: true,
    escalateReason: "Illegal contracts may expose the parties to criminal liability. Do not admit to illegal acts without a lawyer.",
    relatedRules: ["con-void-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "con-qa-050",
    area: "contract",
    jurisdiction: "BD",
    triggerKeywords: ["liquidated damages vs actual damages", "how much compensation", " ", "measure of damages", "remote damages"],
    question: "How does a court calculate the compensation amount for a breach of contract?",
    irac: {
      issue: "The principles courts use to quantify monetary damages under Section 73 of the Contract Act 1872.",
      rule: "Under Section 73, damages are meant to put the injured party in the position they would have been in if the contract was performed. The measure includes: (1) Direct/General damages (natural consequence of breach), (2) Special damages (consequences communicated to the breaching party at the time of contract). Excluded: (1) Remote/Indirect damages (unforeseeable), (2) Speculative damages, (3) Vexatious or punitive damages (usually). The injured party has a duty to mitigate (minimize) their losses.",
      application: "A supplier fails to deliver fabric. You had a contract to sell shirts made from that fabric. You can claim the profit you lost on the shirt contract (this was in the contemplation of the parties). You CANNOT claim the cost of a totally unrelated business opportunity you missed because you were stressed about the fabric shortage (remote).",
      conclusion: "Court calculation rules: (1) Only DIRECT and FORESEEABLE losses are awarded, (2) You MUST try to minimize your losses (buy from another supplier if possible)  if you sit idle and let losses pile up, court will cut the damages, (3) You must prove the loss with documents (invoices, bank statements), (4) Damages are compensatory, not punitive. Always keep detailed financial records to prove your exact loss amount.",
    },
    escalate: false,
    relatedRules: ["con-breach-001", "con-penalty-001"],
    lastVerified: "2025-04-01",
  },
];

const contractModule: KnowledgeModule = {
  area: "contract",
  label: "Contract Law",
  description: "Contract formation, breach, remedies, guarantee, sale of goods, quasi-contracts, and limitation under the Contract Act 1872",
  rules,
  qaBank,
};

export default contractModule;