// ─── JesAI Labour Law Knowledge Module ───────────────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: Labour Act 2006, Bangladesh Labour Rules 2015,
// EPZ Labour Act 2019, Minimum Wage Board Orders
// Audience: Employees, employers, HR professionals, law students
// Last verified: 2025-04-01

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "lab-termination-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Termination of Permanent Worker — Section 26, Labour Act 2006",
    rule: "An employer may terminate a permanent worker without cause by giving 120 days' notice (or pay in lieu) for a monthly-rated worker, or 60 days' notice for others. The worker is entitled to gratuity at the rate of 30 days' wages for every completed year of service.",
    source: "Labour Act 2006, Section 26",
    certainty: "confirmed",
    tags: ["termination", "notice", "120 days", "gratuity", "permanent worker", "dismissed"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-gratuity-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Gratuity Entitlement — Section 27, Labour Act 2006",
    rule: "A worker who has completed at least 1 year of continuous service is entitled to gratuity on termination, retrenchment or voluntary retirement. Rate: 30 days' last wage per completed year of service (or 45 days if employer has no provident fund scheme).",
    source: "Labour Act 2006, Section 27",
    certainty: "confirmed",
    tags: ["gratuity", "30 days", "1 year", "retirement", "termination", "provident fund"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-retrenchment-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Retrenchment — Section 20, Labour Act 2006",
    rule: "An employer may retrench workers due to redundancy. LIFO principle applies (last in, first out). Worker must get 30 days' notice or wages in lieu, plus gratuity (30 days per year of service). Notice to Chief Inspector required if 15+ workers retrenched.",
    source: "Labour Act 2006, Section 20",
    certainty: "confirmed",
    tags: ["retrenchment", "redundancy", "LIFO", "30 days", "layoff"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-leave-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Annual Leave & Festival Leave — Sections 117–118, Labour Act 2006",
    rule: "Workers in industrial establishments earn 1 day's annual leave for every 18 days worked (adult workers). Workers in shops/commercial establishments earn 1 day for every 22 days. In addition, workers are entitled to 11 days' festival leave per year with full wages.",
    source: "Labour Act 2006, Sections 117–118",
    certainty: "confirmed",
    tags: ["annual leave", "festival leave", "sick leave", "leave", "holiday"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-overtime-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Overtime — Section 108, Labour Act 2006",
    rule: "Normal working hours are 8 hours per day and 48 hours per week. Overtime must be paid at double the ordinary rate. Total working hours including overtime must not exceed 60 hours per week or 10 hours per day. Overtime must be voluntary (except in emergency).",
    source: "Labour Act 2006, Section 108",
    certainty: "confirmed",
    tags: ["overtime", "double rate", "8 hours", "48 hours", "60 hours", "working hours"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-maternity-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Maternity Benefit — Sections 45–50, Labour Act 2006",
    rule: "Female workers are entitled to 16 weeks maternity leave (8 weeks before, 8 weeks after delivery) with full wages, provided the worker has been employed for at least 6 months. Maternity benefit is denied for a third or subsequent child.",
    source: "Labour Act 2006, Sections 45–50",
    certainty: "confirmed",
    tags: ["maternity", "maternity leave", "16 weeks", "pregnant", "female worker", "child birth"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-dismissal-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Dismissal for Misconduct — Section 23, Labour Act 2006",
    rule: "An employer may dismiss a worker without notice for proven misconduct. Misconduct includes theft, fraud, dishonesty, habitual absence, damage to property, conviction for a criminal offence, and fighting. Mandatory show-cause notice and domestic enquiry required before dismissal. Worker receives no gratuity if dismissed for misconduct.",
    source: "Labour Act 2006, Section 23",
    certainty: "confirmed",
    tags: ["dismissal", "misconduct", "show cause", "domestic enquiry", "fired", "no gratuity"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-wages-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Wages Payment — Sections 120–123, Labour Act 2006",
    rule: "Wages must be paid within 7 days of the end of the wage period (if fewer than 1,000 workers) or within 10 days (if 1,000 or more workers). Deductions from wages are only permitted for specific reasons such as absence, damage, fine, housing, advance repayment, provident fund and income tax.",
    source: "Labour Act 2006, Sections 120–123",
    certainty: "confirmed",
    tags: ["wages", "salary", "unpaid salary", "7 days", "deductions", "non-payment"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-pf-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Provident Fund — Labour Act 2006 & EPF Ordinance 1961",
    rule: "Where a provident fund scheme exists, both employer and employee typically contribute equally (commonly 8–10% each). Employer contribution vests progressively: 50% after 3 years, 75% after 5 years, 100% after 10 years. On termination without cause after 10 years, the worker gets 100% of employer's contribution.",
    source: "Labour Act 2006 & Employees Provident Fund Ordinance 1961",
    certainty: "confirmed",
    tags: ["provident fund", "PF", "contribution", "employer contribution", "vesting"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-trade-union-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Trade Union Rights — Section 176, Labour Act 2006",
    rule: "Every worker has the right to form and join a trade union. At least 30% of total workers in an establishment must be members for registration. Unfair labour practices by employers (e.g., dismissing union members for union activity) are prohibited and actionable.",
    source: "Labour Act 2006, Section 176",
    certainty: "confirmed",
    tags: ["trade union", "union", "30%", "unfair labour", "collective bargaining"],
    lastVerified: "2025-04-01",
  },
];

const qaBank: QAEntry[] = [
  {
    id: "lab-qa-001",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["wrongful termination", "fired without reason", "unfair dismissal", "terminated illegally", "terminate without notice"],
    question: "I was terminated without notice or reason — what are my rights?",
    irac: {
      issue: "A worker is terminated without prior notice or stated reason. The question is whether the termination complies with the Labour Act 2006 and what remedies are available.",
      rule: "Under Section 26 of the Labour Act 2006, an employer may terminate a permanent worker without assigning a cause, but must give 120 days' written notice (monthly-rated) or 60 days' notice (other workers), or pay wages in lieu. Additionally, the worker is entitled to gratuity of 30 days' last wage per completed year of service under Section 27. Failure to comply makes the termination unlawful.",
      application: "If you received no notice and no wages in lieu, and no gratuity was paid, the employer has breached Sections 26 and 27. You can file a complaint with the Labour Court under Section 33 seeking back wages, notice pay, and gratuity. If you are a confirmed (permanent) worker, the court can award compensation.",
      conclusion: "File a written complaint with the Labour Court within the limitation period (typically 2 years). Collect evidence: appointment letter, service record, last pay slip. Claim notice pay (120 days), gratuity, and any unpaid wages. Seek free legal aid from BLAST or BNLSA if needed.",
    },
    escalate: true,
    escalateReason: "Wrongful termination cases involve court proceedings and strict time limits. Consult a labour lawyer immediately.",
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-002",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["gratuity not paid", "gratuity claim", "gratuity calculation", "service benefit", "terminal benefit"],
    question: "My employer is not paying my gratuity after termination — what can I do?",
    irac: {
      issue: "An employer refuses or delays payment of gratuity to a terminated worker. The question is the worker's entitlement and available legal remedies.",
      rule: "Section 27 of the Labour Act 2006 mandates gratuity at 30 days' last wage per completed year for workers with 1+ year of service (45 days if no PF scheme). Gratuity is a statutory right — it cannot be waived by contract. Non-payment is an offence under Section 307 (fine up to BDT 10,000).",
      application: "Calculate gratuity: (Last Basic Salary / 26) × 30 × Years of service. If the employer refuses to pay, the worker can file a complaint with the Labour Court or directly with the Chief Inspector of Labour. The court can order payment with interest.",
      conclusion: "Send a written demand to your employer with calculation. If refused within 30 days, file at the Labour Court. Limitation period: 2 years from the date gratuity became due. Keep appointment letter, salary slips, and service record.",
    },
    escalate: false,
    relatedRules: ["lab-gratuity-001", "lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-003",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["overtime not paid", "extra hours not paid", "overtime payment", "double rate", "working too many hours"],
    question: "My employer is not paying me for overtime work — what are my rights?",
    irac: {
      issue: "An employee works beyond the standard 8-hour day/48-hour week but is not paid the overtime rate. The question is whether the worker has a legal entitlement to overtime pay.",
      rule: "Section 108 of the Labour Act 2006 requires overtime pay at double the ordinary rate for work beyond 8 hours/day or 48 hours/week. Total hours including overtime must not exceed 60 hours/week. Failure to pay overtime is punishable under Section 307 with a fine.",
      application: "Calculate the shortfall: (basic/26) × 2 × overtime hours. For each day worked beyond 8 hours, you are owed the double rate. Maintain a record of your working hours as evidence. Multiple violations can be aggregated in one complaint.",
      conclusion: "First, raise the issue formally with HR/employer in writing. If unresolved within 7 days, file a complaint with the Department of Inspection for Factories and Establishments (DIFE) or the Labour Court. Keep time-attendance records, shift rosters, and bank statements showing salary.",
    },
    escalate: false,
    relatedRules: ["lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-004",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["salary not paid", "unpaid wages", "salary withheld", "employer not paying", "non-payment of wages"],
    question: "My employer has not paid my salary for months — what can I do?",
    irac: {
      issue: "An employer withholds or delays payment of wages. The question is the employee's rights and remedies under the Labour Act.",
      rule: "Sections 120–123 of the Labour Act 2006 require wages to be paid within 7 working days (up to 1,000 workers) or 10 days (over 1,000 workers) from the close of the wage period. Unlawful withholding of wages is an offence. The Wages Board also sets minimum wage floors by sector.",
      application: "Unpaid wages for multiple months constitute a serious statutory violation. You can simultaneously file a complaint with (1) the Labour Court seeking full recovery, (2) DIFE for enforcement, and (3) if the employer goes bankrupt, wages are a first-priority debt under Section 278.",
      conclusion: "Gather evidence: pay slips, appointment letter, bank statements, attendance records. Send demand notice. File labour complaint within 2 years. For amounts under BDT 5 lakh, you can proceed without a lawyer at the Labour Court.",
    },
    escalate: true,
    escalateReason: "Sustained non-payment of wages may indicate insolvency or fraudulent closure. Take legal action immediately before assets are dissipated.",
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-005",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["maternity leave denied", "maternity benefit", "maternity pay", "pregnant fired", "pregnancy dismissed"],
    question: "I was denied maternity leave or dismissed because of pregnancy — what are my rights?",
    irac: {
      issue: "A female worker is denied maternity leave, maternity benefit, or dismissed due to pregnancy. The question is the statutory protection under the Labour Act.",
      rule: "Sections 45–50 of the Labour Act 2006 grant 16 weeks maternity leave (8 weeks pre-delivery, 8 weeks post-delivery) with full wages to workers employed for at least 6 months. Dismissal during maternity leave or for reasons connected to pregnancy is unlawful. Maternity benefit must be paid 8 weeks before expected delivery.",
      application: "Denial of maternity leave, reduction of maternity benefit, or dismissal connected to pregnancy all constitute violations. The worker can seek reinstatement, full back pay including maternity benefit, and compensation through the Labour Court.",
      conclusion: "Document your employment period (6+ months required), pregnancy proof (medical certificate), and any written/verbal dismissal notice. File complaint at Labour Court. Courts take a protective view toward maternity rights. You may also file with the National Women's Development Authority.",
    },
    escalate: true,
    escalateReason: "Dismissal during pregnancy is a serious rights violation. Seek urgent legal assistance.",
    relatedRules: ["lab-maternity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-006",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["resignation", "notice period", "resign without notice", "notice pay", "leaving job"],
    question: "Can I resign without serving my notice period?",
    irac: {
      issue: "A worker wishes to resign and leave without serving the contractual or statutory notice period. The question is the worker's obligation and the employer's remedies.",
      rule: "Under Section 27 of the Labour Act 2006, a permanent worker who resigns must give 30 days' written notice. If no notice is given, the employer may deduct equivalent wages from final settlement. However, gratuity cannot be forfeited merely because the worker did not serve notice — only earned gratuity can be withheld up to the notice pay shortfall.",
      application: "If you leave immediately, the employer can withhold 30 days' wages from your final dues but cannot forfeit your earned gratuity beyond that deduction. Employers who refuse to issue a service certificate (experience letter) after resignation are in breach of Section 35.",
      conclusion: "Give 30 days' written notice where possible. If you must leave immediately, accept the 30-day wage deduction. Ensure your employer issues service certificate and clears all dues within 30 days of your last working day. Gratuity (if earned) must be paid.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-007",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["show cause notice", "misconduct charge", "domestic enquiry", "charge sheet", "disciplinary action"],
    question: "I received a show cause notice for misconduct — what should I do?",
    irac: {
      issue: "A worker receives a show cause or charge sheet for alleged misconduct. The question is how to respond and what procedural safeguards apply.",
      rule: "Section 23 of the Labour Act 2006 requires a mandatory two-stage process before dismissal for misconduct: (1) issue of written charge sheet, (2) domestic enquiry by an enquiry officer where the worker may defend themselves. Dismissal without this procedure is void even if misconduct is proven.",
      application: "You must respond to the show cause within the specified deadline (usually 7–14 days) clearly denying or explaining the allegations. Request the enquiry details, right to be represented, and copies of all evidence. If the employer proceeds to dismissal without a proper enquiry, the dismissal can be challenged at the Labour Court.",
      conclusion: "Respond in writing within the deadline. Deny false allegations with evidence. Request domestic enquiry. Document all communications. If dismissed without fair enquiry, file at Labour Court within 30 days — courts regularly reinstate workers where procedural requirements were not followed.",
    },
    escalate: false,
    relatedRules: ["lab-dismissal-001"],
    lastVerified: "2025-04-01",
  },
];

const labourModule: KnowledgeModule = {
  area: "labour",
  label: "Labour Law",
  description: "Employment rights, termination, wages, gratuity, maternity, overtime under the Labour Act 2006",
  rules,
  qaBank,
};

export default labourModule;
