//  JesAI Labour Law Knowledge Module 
// NLC validated  Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: Labour Act 2006, Bangladesh Labour Rules 2015,
// EPZ Labour Act 2019, Minimum Wage Board Orders
// Audience: Employees, employers, HR professionals, law students
// Last verified: 2025-04-01

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "lab-termination-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Termination of Permanent Worker  Section 26, Labour Act 2006",
    rule: "An employer may terminate a permanent worker without cause by giving 120 days' notice (or pay in lieu) for a monthly-rated worker, or 60 days' notice for others. The worker is entitled to gratuity at the rate of 30 days' wages for every completed year of service.",
    source: "Labour Act 2006, Section 26",
    certainty: "confirmed",
    tags: ["termination", "notice", "120 days", "gratuity", "permanent worker", "dismissed"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-gratuity-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Gratuity Entitlement  Section 27, Labour Act 2006",
    rule: "A worker who has completed at least 1 year of continuous service is entitled to gratuity on termination, retrenchment or voluntary retirement. Rate: 30 days' last wage per completed year of service (or 45 days if employer has no provident fund scheme).",
    source: "Labour Act 2006, Section 27",
    certainty: "confirmed",
    tags: ["gratuity", "30 days", "1 year", "retirement", "termination", "provident fund"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-retrenchment-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Retrenchment  Section 20, Labour Act 2006",
    rule: "An employer may retrench workers due to redundancy. LIFO principle applies (last in, first out). Worker must get 30 days' notice or wages in lieu, plus gratuity (30 days per year of service). Notice to Chief Inspector required if 15+ workers retrenched.",
    source: "Labour Act 2006, Section 20",
    certainty: "confirmed",
    tags: ["retrenchment", "redundancy", "LIFO", "30 days", "layoff"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-leave-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Annual Leave & Festival Leave  Sections 117118, Labour Act 2006",
    rule: "Workers in industrial establishments earn 1 day's annual leave for every 18 days worked (adult workers). Workers in shops/commercial establishments earn 1 day for every 22 days. In addition, workers are entitled to 11 days' festival leave per year with full wages.",
    source: "Labour Act 2006, Sections 117118",
    certainty: "confirmed",
    tags: ["annual leave", "festival leave", "sick leave", "leave", "holiday"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-overtime-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Overtime  Section 108, Labour Act 2006",
    rule: "Normal working hours are 8 hours per day and 48 hours per week. Overtime must be paid at double the ordinary rate. Total working hours including overtime must not exceed 60 hours per week or 10 hours per day. Overtime must be voluntary (except in emergency).",
    source: "Labour Act 2006, Section 108",
    certainty: "confirmed",
    tags: ["overtime", "double rate", "8 hours", "48 hours", "60 hours", "working hours"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-maternity-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Maternity Benefit  Sections 4550, Labour Act 2006",
    rule: "Female workers are entitled to 16 weeks maternity leave (8 weeks before, 8 weeks after delivery) with full wages, provided the worker has been employed for at least 6 months. Maternity benefit is denied for a third or subsequent child.",
    source: "Labour Act 2006, Sections 4550",
    certainty: "confirmed",
    tags: ["maternity", "maternity leave", "16 weeks", "pregnant", "female worker", "child birth"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-dismissal-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Dismissal for Misconduct  Section 23, Labour Act 2006",
    rule: "An employer may dismiss a worker without notice for proven misconduct. Misconduct includes theft, fraud, dishonesty, habitual absence, damage to property, conviction for a criminal offence, and fighting. Mandatory show-cause notice and domestic enquiry required before dismissal. Worker receives no gratuity if dismissed for misconduct.",
    source: "Labour Act 2006, Section 23",
    certainty: "confirmed",
    tags: ["dismissal", "misconduct", "show cause", "domestic enquiry", "fired", "no gratuity"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-wages-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Wages Payment  Sections 120123, Labour Act 2006",
    rule: "Wages must be paid within 7 days of the end of the wage period (if fewer than 1,000 workers) or within 10 days (if 1,000 or more workers). Deductions from wages are only permitted for specific reasons such as absence, damage, fine, housing, advance repayment, provident fund and income tax.",
    source: "Labour Act 2006, Sections 120123",
    certainty: "confirmed",
    tags: ["wages", "salary", "unpaid salary", "7 days", "deductions", "non-payment"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-pf-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Provident Fund  Labour Act 2006 & EPF Ordinance 1961",
    rule: "Where a provident fund scheme exists, both employer and employee typically contribute equally (commonly 810% each). Employer contribution vests progressively: 50% after 3 years, 75% after 5 years, 100% after 10 years. On termination without cause after 10 years, the worker gets 100% of employer's contribution.",
    source: "Labour Act 2006 & Employees Provident Fund Ordinance 1961",
    certainty: "confirmed",
    tags: ["provident fund", "PF", "contribution", "employer contribution", "vesting"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-trade-union-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Trade Union Rights  Section 176, Labour Act 2006",
    rule: "Every worker has the right to form and join a trade union. At least 30% of total workers in an establishment must be members for registration. Unfair labour practices by employers (e.g., dismissing union members for union activity) are prohibited and actionable.",
    source: "Labour Act 2006, Section 176",
    certainty: "confirmed",
    tags: ["trade union", "union", "30%", "unfair labour", "collective bargaining"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-probation-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Probationary Workers  Section 22, Labour Act 2006",
    rule: "A worker may be appointed on probation for a maximum of 6 months (can be extended by another 3 months, totaling 9 months). During probation, either party may terminate by giving 60 days' notice or pay in lieu. If not confirmed or terminated within the probation period, they are deemed permanently employed.",
    source: "Labour Act 2006, Section 22",
    certainty: "confirmed",
    tags: ["probation", "probationary period", "6 months", "confirmation", "temporary"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-child-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Child Labour Prohibition  Sections 3438, Labour Act 2006",
    rule: "Children under 14 years cannot be employed. Adolescents (1418 years) can be employed in safe work only, subject to daily/weekly hour limits (max 5 hours/day, 30 hours/week) and night restrictions (cannot work between 7 PM and 7 AM). Employing children is a criminal offence.",
    source: "Labour Act 2006, Sections 3438",
    certainty: "confirmed",
    tags: ["child labour", "adolescent", "minor", "14 years", "night shift", "underage"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-compensation-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Workplace Injury Compensation  Workmen's Compensation Act 1923",
    rule: "If a worker dies or suffers injury from an accident arising out of and in the course of employment, the employer must pay compensation under the Workmen's Compensation Act 1923. Compensation depends on monthly wages and the nature of injury (partial/permanent disablement or death). No fault of the employer needs to be proven.",
    source: "Workmen's Compensation Act 1923",
    certainty: "confirmed",
    tags: ["injury", "accident", "compensation", "death", "workmen's compensation", "disablement"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-court-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Labour Court Jurisdiction  Section 33, Labour Act 2006",
    rule: "Labour Courts have exclusive jurisdiction to adjudicate disputes under the Labour Act (except some criminal matters). A complaint must be filed within 2 years of the cause of action. No court fee is required for filing. The court can order reinstatement, back wages, compensation, or gratuity.",
    source: "Labour Act 2006, Section 33",
    certainty: "confirmed",
    tags: ["labour court", "file case", "2 years", "jurisdiction", "no court fee"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-strike-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Strike and Lockout  Sections 211215, Labour Act 2006",
    rule: "Workers in an essential service cannot strike. In non-essential services, a strike requires a 14-day notice to the employer and a 30% secret ballot vote in favor. Illegal strikes result in loss of wages and potential termination. Employers cannot declare a lockout without following similar conciliation procedures.",
    source: "Labour Act 2006, Sections 211215",
    certainty: "confirmed",
    tags: ["strike", "lockout", "essential service", "secret ballot", "14 days notice"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-casual-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Casual, Badli & Temporary Workers  Section 2, Labour Act 2006",
    rule: "A casual worker is engaged for work that is not of a permanent nature. A badli worker substitutes a permanent worker on leave. A temporary worker is employed for a specific project/period. None have automatic right to permanency unless continuously employed for 3 months (badli) or the temporary period exceeds the statutory limit, at which point they may claim permanent status.",
    source: "Labour Act 2006, Section 2; Bangladesh Labour Rules 2015",
    certainty: "confirmed",
    tags: ["casual worker", "badli", "temporary worker", "daily wage", "contractor"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-harassment-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Workplace Sexual Harassment  High Court Guidelines 2009",
    rule: "The Bangladesh High Court (2009) directed all workplaces to form a Complaints Committee (headed by a woman, 50% women members) to address sexual harassment. Employers must display guidelines and treat sexual harassment as a disciplinary offence. No specific statutory act yet, but High Court guidelines have the force of law.",
    source: "High Court Guidelines on Sexual Harassment, 2009",
    certainty: "confirmed",
    tags: ["sexual harassment", "complaints committee", "hostile workplace", "female safety"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-service-cert-001",
    area: "labour",
    jurisdiction: "BD",
    title: "Service Certificate  Section 35, Labour Act 2006",
    rule: "An employer must issue a service certificate (experience letter) to a worker within 3 days of the worker's application, regardless of whether the worker resigned, was terminated, or retrenched. Refusal or delay is a punishable offence. The certificate should state the nature of work and duration of service.",
    source: "Labour Act 2006, Section 35",
    certainty: "confirmed",
    tags: ["service certificate", "experience letter", "resignation", "employer obligation"],
    lastVerified: "2025-04-01",
  },
];

const qaBank: QAEntry[] = [
  {
    id: "lab-qa-001",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["wrongful termination", "fired without reason", "unfair dismissal", "terminated illegally", "terminate without notice"],
    question: "I was terminated without notice or reason  what are my rights?",
    irac: {
      issue: "A worker is terminated without prior notice or stated reason. The question is whether the termination complies with the Labour Act 2006 and what remedies are available.",
      rule: "Under Section 26 of the Labour Act 2006, an employer may terminate a permanent worker without assigning a cause, but must give 120 days' written notice (monthly-rated) or 60 days' notice (other workers), or pay wages in lieu. Additionally, the worker is entitled to gratuity of 30 days' last wage per completed year of service under Section 27. Failure to comply makes the termination unlawful.",
      application: "If you received no notice and no wages in lieu, and no gratuity was paid, the employer has breached Sections 26 and 27. You can file a complaint with the Labour Court under Section 33 seeking back wages, notice pay, and gratuity. If you are a confirmed (permanent) worker, the court can award compensation.",
      conclusion: "File a written complaint with the Labour Court within the limitation period (2 years). Collect evidence: appointment letter, service record, last pay slip. Claim notice pay (120 days), gratuity, and any unpaid wages. Seek free legal aid from BLAST or BNLSA if needed.",
    },
    escalate: true,
    escalateReason: "Wrongful termination cases involve court proceedings and strict time limits. Consult a labour lawyer immediately.",
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-002",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["gratuity not paid", "gratuity claim", "gratuity calculation", "service benefit", "terminal benefit"],
    question: "My employer is not paying my gratuity after termination  what can I do?",
    irac: {
      issue: "An employer refuses or delays payment of gratuity to a terminated worker. The question is the worker's entitlement and available legal remedies.",
      rule: "Section 27 of the Labour Act 2006 mandates gratuity at 30 days' last wage per completed year for workers with 1+ year of service (45 days if no PF scheme). Gratuity is a statutory right  it cannot be waived by contract. Non-payment is an offence under Section 307 (fine up to BDT 10,000).",
      application: "Calculate gratuity: (Last Basic Salary / 26)  30  Years of service. If the employer refuses to pay, the worker can file a complaint with the Labour Court or directly with the Chief Inspector of Labour. The court can order payment with interest.",
      conclusion: "Send a written demand to your employer with calculation. If refused within 30 days, file at the Labour Court. Limitation period: 2 years from the date gratuity became due. Keep appointment letter, salary slips, and service record.",
    },
    escalate: false,
    relatedRules: ["lab-gratuity-001", "lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-003",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["overtime not paid", "extra hours not paid", "overtime payment", "double rate", "working too many hours"],
    question: "My employer is not paying me for overtime work  what are my rights?",
    irac: {
      issue: "An employee works beyond the standard 8-hour day/48-hour week but is not paid the overtime rate. The question is whether the worker has a legal entitlement to overtime pay.",
      rule: "Section 108 of the Labour Act 2006 requires overtime pay at double the ordinary rate for work beyond 8 hours/day or 48 hours/week. Total hours including overtime must not exceed 60 hours/week. Failure to pay overtime is punishable under Section 307 with a fine.",
      application: "Calculate the shortfall: (basic/26)  2  overtime hours. For each day worked beyond 8 hours, you are owed the double rate. Maintain a record of your working hours as evidence. Multiple violations can be aggregated in one complaint.",
      conclusion: "First, raise the issue formally with HR/employer in writing. If unresolved within 7 days, file a complaint with the Department of Inspection for Factories and Establishments (DIFE) or the Labour Court. Keep time-attendance records, shift rosters, and bank statements showing salary.",
    },
    escalate: false,
    relatedRules: ["lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-004",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["salary not paid", "unpaid wages", "salary withheld", "employer not paying", "non-payment of wages"],
    question: "My employer has not paid my salary for months  what can I do?",
    irac: {
      issue: "An employer withholds or delays payment of wages. The question is the employee's rights and remedies under the Labour Act.",
      rule: "Sections 120123 of the Labour Act 2006 require wages to be paid within 7 working days (up to 1,000 workers) or 10 days (over 1,000 workers) from the close of the wage period. Unlawful withholding of wages is an offence. The Wages Board also sets minimum wage floors by sector.",
      application: "Unpaid wages for multiple months constitute a serious statutory violation. You can simultaneously file a complaint with (1) the Labour Court seeking full recovery, (2) DIFE for enforcement, and (3) if the employer goes bankrupt, wages are a first-priority debt under Section 278.",
      conclusion: "Gather evidence: pay slips, appointment letter, bank statements, attendance records. Send demand notice. File labour complaint within 2 years. For amounts under BDT 5 lakh, you can proceed without a lawyer at the Labour Court.",
    },
    escalate: true,
    escalateReason: "Sustained non-payment of wages may indicate insolvency or fraudulent closure. Take legal action immediately before assets are dissipated.",
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-005",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["maternity leave denied", "maternity benefit", "maternity pay", "pregnant fired", "pregnancy dismissed"],
    question: "I was denied maternity leave or dismissed because of pregnancy  what are my rights?",
    irac: {
      issue: "A female worker is denied maternity leave, maternity benefit, or dismissed due to pregnancy. The question is the statutory protection under the Labour Act.",
      rule: "Sections 4550 of the Labour Act 2006 grant 16 weeks maternity leave (8 weeks pre-delivery, 8 weeks post-delivery) with full wages to workers employed for at least 6 months. Dismissal during maternity leave or for reasons connected to pregnancy is unlawful. Maternity benefit must be paid 8 weeks before expected delivery.",
      application: "Denial of maternity leave, reduction of maternity benefit, or dismissal connected to pregnancy all constitute violations. The worker can seek reinstatement, full back pay including maternity benefit, and compensation through the Labour Court.",
      conclusion: "Document your employment period (6+ months required), pregnancy proof (medical certificate), and any written/verbal dismissal notice. File complaint at Labour Court. Courts take a protective view toward maternity rights. You may also file with the National Women's Development Authority.",
    },
    escalate: true,
    escalateReason: "Dismissal during pregnancy is a serious rights violation. Seek urgent legal assistance.",
    relatedRules: ["lab-maternity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-006",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["resignation", "notice period", "resign without notice", "notice pay", "leaving job"],
    question: "Can I resign without serving my notice period?",
    irac: {
      issue: "A worker wishes to resign and leave without serving the contractual or statutory notice period. The question is the worker's obligation and the employer's remedies.",
      rule: "Under Section 27 of the Labour Act 2006, a permanent worker who resigns must give 30 days' written notice. If no notice is given, the employer may deduct equivalent wages from final settlement. However, gratuity cannot be forfeited merely because the worker did not serve notice  only earned gratuity can be withheld up to the notice pay shortfall.",
      application: "If you leave immediately, the employer can withhold 30 days' wages from your final dues but cannot forfeit your earned gratuity beyond that deduction. Employers who refuse to issue a service certificate (experience letter) after resignation are in breach of Section 35.",
      conclusion: "Give 30 days' written notice where possible. If you must leave immediately, accept the 30-day wage deduction. Ensure your employer issues service certificate and clears all dues within 30 days of your last working day. Gratuity (if earned) must be paid.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-007",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["show cause notice", "misconduct charge", "domestic enquiry", "charge sheet", "disciplinary action"],
    question: "I received a show cause notice for misconduct  what should I do?",
    irac: {
      issue: "A worker receives a show cause or charge sheet for alleged misconduct. The question is how to respond and what procedural safeguards apply.",
      rule: "Section 23 of the Labour Act 2006 requires a mandatory two-stage process before dismissal for misconduct: (1) issue of written charge sheet, (2) domestic enquiry by an enquiry officer where the worker may defend themselves. Dismissal without this procedure is void even if misconduct is proven.",
      application: "You must respond to the show cause within the specified deadline (usually 714 days) clearly denying or explaining the allegations. Request the enquiry details, right to be represented, and copies of all evidence. If the employer proceeds to dismissal without a proper enquiry, the dismissal can be challenged at the Labour Court.",
      conclusion: "Respond in writing within the deadline. Deny false allegations with evidence. Request domestic enquiry. Document all communications. If dismissed without fair enquiry, file at Labour Court within 30 days  courts regularly reinstate workers where procedural requirements were not followed.",
    },
    escalate: false,
    relatedRules: ["lab-dismissal-001"],
    lastVerified: "2025-04-01",
  },
  //  ENRICHED SECTION: QA 008-050 
  {
    id: "lab-qa-008",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["probation period", "fired during probation", "", "probationary worker rights", "probation notice period"],
    question: "Can my employer fire me without any reason while I am on probation?",
    irac: {
      issue: "Whether an employer can terminate a probationary worker without assigning any cause or following formal dismissal procedures.",
      rule: "Under Section 22 of the Labour Act 2006, a worker on probation can be terminated by either party by giving 60 days' notice or pay in lieu. Unlike permanent workers dismissed for misconduct (S.23), a probationary worker does NOT need to be charged with misconduct or face a domestic enquiry to be terminated during or at the end of the probation period.",
      application: "If you are 3 months into a 6-month probation and the employer decides you are not a good fit, they can simply give you 60 days' notice (or 60 days' pay) and terminate you. They do not need to prove poor performance or misconduct. However, if they fire you on the spot without 60 days' notice/pay, that is illegal.",
      conclusion: "Yes, an employer can terminate you without assigning a reason during probation, BUT they must give 60 days' notice or 60 days' wages in lieu. If they force you out immediately without pay, file a Labour Court case for illegal termination and notice pay. Tip: Always get your probation terms in writing.",
    },
    escalate: false,
    relatedRules: ["lab-probation-001", "lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-009",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["sick leave", "medical leave", " ", "sick leave entitlement", "medical certificate"],
    question: "How many sick days am I legally entitled to, and can my employer demand a doctor's note?",
    irac: {
      issue: "Determining the statutory entitlement for sick leave and the employer's right to request medical documentation.",
      rule: "Under Section 119 of the Labour Act 2006, a worker who has worked for at least 6 months is entitled to 14 days' sick leave with full wages per year. The employer is legally permitted to request a medical certificate from a registered physician if the sick leave exceeds 3 consecutive days, as per the Bangladesh Labour Rules 2015.",
      application: "If you are sick for 2 days, you can take sick leave without a doctor's note. If you are sick for 4 consecutive days, the employer can legally ask for a medical certificate. If you fail to provide it, they may treat those days as unauthorized absence, which could lead to deductions or disciplinary action.",
      conclusion: "You get 14 days of paid sick leave per year (after 6 months of service). For 1-3 days: usually no doctor's note needed. For 4+ consecutive days: employer can legally demand a registered doctor's certificate. Unused sick leave usually cannot be carried forward or encashed (unless company policy says otherwise).",
    },
    escalate: false,
    relatedRules: ["lab-leave-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-010",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["casual leave", " ", "casual leave rules", "how many casual leave"],
    question: "How many casual leave days do I get per year?",
    irac: {
      issue: "Entitlement and rules regarding casual leave under Bangladesh labour law.",
      rule: "Under the Bangladesh Labour Rules 2015, every worker is entitled to 10 days of casual leave with full wages per calendar year. Casual leave cannot be accumulated or carried forward to the next year. It is intended for sudden personal needs, not planned vacations.",
      application: "You need a day off for a family emergency. You apply for 1 day of casual leave. Your employer cannot deny casual leave if applied for properly, but it cannot be combined with festival leave or annual leave to extend a holiday. If you don't use the 10 days by December 31, they expire.",
      conclusion: "You are entitled to 10 days of casual leave per year with full pay. Rules: (1) Cannot be accumulated/carried forward, (2) Usually requires 1-day prior application (unless emergency), (3) Cannot be prefixed or suffixed to other leaves. It expires at the end of the year.",
    },
    escalate: false,
    relatedRules: ["lab-leave-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-011",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["working on friday", "weekly holiday", " ", "friday work compensation", "forced to work friday"],
    question: "Can my employer force me to work on Friday (the weekly holiday)?",
    irac: {
      issue: "Whether an employer can compel a worker to work on their designated weekly holiday and what the compensation should be.",
      rule: "Under Section 103 of the Labour Act 2006, every worker is entitled to one weekly holiday (usually Friday). A worker cannot be compelled to work on a weekly holiday. If a worker *voluntarily* agrees to work, they must be compensated with a substitute holiday within the same week OR double the ordinary wages for that day.",
      application: "Your factory has an urgent shipment and the supervisor tells you to work on Friday. You can refuse. If you agree to work, you must either get Saturday off (substitute holiday) OR be paid double your daily wage for Friday. If they force you without extra pay, it is a violation.",
      conclusion: "No, your employer CANNOT force you to work on Friday. If you voluntarily agree to work, you must get: (Option A) A substitute day off in the same week, OR (Option B) Double wages for that day. If forced without compensation, file a complaint with DIFE or the Labour Court.",
    },
    escalate: false,
    relatedRules: ["lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-012",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["child labour", "14 year old job", " ", "underage worker", "can a teenager work"],
    question: "Can a 14-year-old be legally employed in a factory or shop in Bangladesh?",
    irac: {
      issue: "The legality of employing children and adolescents under Bangladesh labour law.",
      rule: "Under Sections 34-38 of the Labour Act 2006, a 'child' (under 14 years) CANNOT be employed in any factory, workshop, or establishment. An 'adolescent' (14-18 years) CAN be employed, but ONLY in safe work. They cannot work more than 5 hours a day (30 hours/week) and CANNOT work between 7 PM and 7 AM. They must also get 1 hour of rest after 2 hours of work.",
      application: "A garment factory employs a 13-year-old. This is strictly illegal and a criminal offence. The factory owner can be imprisoned. A 16-year-old can be employed, but only in non-hazardous tasks, for max 5 hours a day, strictly during daytime, with mandatory rest breaks.",
      conclusion: "Under 14: ABSOLUTELY ILLEGAL. Employment is a criminal offence. 14 to 18 years (Adolescent): Legal BUT with heavy restrictions (max 5 hours/day, no night work, no hazardous work, mandatory rest). If you know of child labour, report it to DIFE or call the national hotline (999).",
    },
    escalate: true,
    escalateReason: "Child labour is a criminal offence. Immediate reporting to DIFE or law enforcement may be required.",
    relatedRules: ["lab-child-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-013",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["female night shift", "women night work", "  ", "can women work at night"],
    question: "Is it legal for female workers to work night shifts in Bangladesh?",
    irac: {
      issue: "Whether female workers are legally permitted to work during night hours (typically 7 PM to 7 AM).",
      rule: "Under Section 109 of the Labour Act 2006, women are generally prohibited from working between 7 PM and 7 AM. However, there is an exception: women CAN work night shifts in (1) Export Processing Zones (EPZ) under the EPZ Labour Act 2019, and (2) Garments and Textile industries (specifically allowed by amendment), provided adequate transport and safety measures are provided by the employer.",
      application: "A female worker in a BPO/IT company is asked to work from 10 PM to 6 AM. Unless it falls under a specific exempted sector (like garments or EPZ), this is illegal. If she works in an EPZ IT firm, it is legal as long as the employer provides secure transport home.",
      conclusion: "Generally NO  women cannot work between 7 PM and 7 AM. Exceptions where it IS legal: (1) Ready-Made Garments (RMG) sector, (2) Export Processing Zones (EPZs). In these exceptions, employers MUST provide safe transport, resting rooms, and maternity protection. Other sectors must seek special exemptions.",
    },
    escalate: false,
    relatedRules: ["lab-maternity-001", "lab-child-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-014",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["workplace injury", "accident in factory", " ", "machine injury compensation", "hurt at work"],
    question: "I was injured at work due to a machine malfunction  can I claim compensation?",
    irac: {
      issue: "A worker suffers physical injury due to an accident arising out of and in the course of employment. The question is the right to compensation.",
      rule: "Under the Workmen's Compensation Act 1923, if a worker sustains an injury from an accident 'arising out of and in the course of employment', the employer must pay compensation. The amount depends on the nature of injury (temporary/partial/permanent disablement) and the worker's average monthly wages. Fault of the employer does NOT need to be proven.",
      application: "Your hand gets caught in an unguarded machine. This is a clear workplace accident. You are entitled to free medical treatment, wages during the period of hospitalization (under S.91 of Labour Act), and compensation under the Workmen's Compensation Act based on the percentage of permanent loss of earning capacity.",
      conclusion: "Yes. Steps: (1) Get immediate medical treatment and keep ALL records/reports, (2) Report the accident to your supervisor IN WRITING immediately, (3) Apply for compensation under the Workmen's Compensation Act through the Labour Court or Commissioner. You do not need to prove the employer was negligentjust that the accident happened at work.",
    },
    escalate: true,
    escalateReason: "Workmen's compensation claims require precise medical assessment of disability percentage and legal filing.",
    relatedRules: ["lab-compensation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-015",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["worker died at factory", "death compensation", " ", "family compensation death"],
    question: "If a worker dies in a workplace accident, how much compensation does the family get?",
    irac: {
      issue: "Compensation payable to the dependents of a worker who dies from a workplace injury.",
      rule: "Under Section 4 of the Workmen's Compensation Act 1923, if a worker dies from an injury arising out of employment, the employer must pay 50% of the worker's monthly wages multiplied by the relevant factor (based on the worker's age at death, ranging from 140 to 200) or BDT 2,00,000, whichever is more.",
      application: "A 30-year-old worker earning BDT 8,000/month dies in a factory fire. Factor for age 30 is ~198. Compensation = (50% of 8,000)  198 = BDT 792,000. Since this is more than BDT 2,00,000, the family gets BDT 792,000.",
      conclusion: "Family gets: 50% of monthly wages  Age Factor (or BDT 2,00,000, whichever is higher). The employer must also pay BDT 5,000 for funeral expenses. File a claim before the Labour Commissioner within 2 years of death. Dependents include spouse, children, or dependent parents.",
    },
    escalate: true,
    escalateReason: "Death compensation claims require legal representation to calculate the multiplier and establish dependency.",
    relatedRules: ["lab-compensation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-016",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["labour court case", "how to file case", " ", "file complaint labour", "labour case procedure"],
    question: "How do I file a case in the Labour Court?",
    irac: {
      issue: "The procedure, cost, and limitation period for filing a dispute in the Labour Court.",
      rule: "Under Section 33 of the Labour Act 2006, a complaint can be filed directly in the Labour Court. There is NO COURT FEE required. The limitation period is strictly 2 years from the date the cause of action arose (e.g., date of termination, date wages were due). The court follows a summary procedure, and parties can appear without a lawyer if they wish.",
      application: "You were terminated on January 1, 2023. You have until January 1, 2025, to file. You draft a simple petition stating the facts, your claims, and attach copies of your appointment letter and termination letter. Submit it to the Labour Court Registrar. The court will issue a summons to the employer.",
      conclusion: "Steps: (1) Draft a written complaint (petition), (2) Attach evidence (appointment letter, pay slips, termination notice), (3) Submit to Labour Court RegistrarNO FEE needed, (4) Attend hearings. Limitation: 2 YEARS (strictly enforced). You can represent yourself, but a lawyer is recommended for complex cases.",
    },
    escalate: false,
    relatedRules: ["lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-017",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["go on strike", "strike rules", "", "legal strike procedure", "workers protest"],
    question: "What is the legal process for workers to go on strike?",
    irac: {
      issue: "The legal requirements workers must fulfill before going on strike to ensure it is not deemed illegal.",
      rule: "Under Sections 211-215 of the Labour Act 2006, workers in essential services (hospitals, utilities, fire brigade) CANNOT strike. For non-essential services, a strike requires: (1) A 14-day written notice to the employer specifying the reason, (2) A secret ballot where at least 30% of all workers in the establishment vote in favor.",
      application: "Factory workers want to strike for a wage increase. They cannot just stop working. They must give 14 days' notice to management. Then, hold a secret ballot. If 500 out of 1000 workers vote, and 400 vote 'yes', that is 40% of total workerswhich meets the 30% threshold. The strike is legal.",
      conclusion: "To strike legally: (1) Give 14 days' written notice, (2) Hold a secret ballot, (3) Must get 'Yes' from at least 30% of ALL workers (not just those voting). An illegal strike results in loss of wages for the strike period, and participants can be fired. Essential service workers cannot strike at all.",
    },
    escalate: true,
    escalateReason: "Organizing a strike involves complex procedural compliance. Mistakes lead to illegal strike status and termination.",
    relatedRules: ["lab-strike-001", "lab-trade-union-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-018",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["casual worker rights", "daily wage gratuity", " ", "temporary worker benefits", "contract worker rights"],
    question: "I am a daily-wage/casual worker  am I entitled to gratuity or notice pay?",
    irac: {
      issue: "Whether casual, temporary, or daily-rated workers are entitled to statutory benefits like gratuity and notice period.",
      rule: "Under the Labour Act 2006, the definition of a 'worker' includes temporary, casual, and badli workers. Therefore, if a casual worker has completed 1 year of continuous service, they ARE entitled to gratuity under Section 27. However, notice pay under Section 26 applies differentlydaily-rated workers are generally entitled to 60 days' notice or pay in lieu, depending on their specific engagement terms.",
      application: "You have worked as a daily-wage laborer at a factory for 2 years, working 26 days a month. You are terminated. Even though you are 'daily-wage', you have continuous service. You are entitled to 30 days' wages per year of service as gratuity (calculated on average daily wage  26  30  2 years).",
      conclusion: "YES. Being a 'casual' or 'daily-wage' worker does NOT strip you of statutory rights. If you have 1+ year of continuous service: (1) You get Gratuity, (2) You get notice pay (usually 60 days for non-monthly rated). 'Continuous service' includes authorized leave, weekly holidays, and lay-off days.",
    },
    escalate: false,
    relatedRules: ["lab-casual-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-019",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["employee vs worker", "labour act applicability", "  ", "officer labour law", "manager rights"],
    question: "Does the Labour Act apply to managers, officers, and administrative staff?",
    irac: {
      issue: "Determining whether high-level administrative, managerial, or supervisory staff fall under the definition of 'worker' in the Labour Act.",
      rule: "Section 2(65) of the Labour Act 2006 defines a 'worker' broadly but EXCLUDES persons employed mainly in a managerial or administrative capacity. If an employee's primary duty is managerial (e.g., HR Manager, Finance Director), they are an 'Employee' under the standing orders/service rules, not a 'Worker' under the Labour Act. They cannot file cases in the Labour Court.",
      application: "A factory accountant who mostly does data entry and bill processing is likely a 'worker'. An HR Head who hires, fires, and makes policy is 'administrative/managerial' and is NOT covered by the Labour Act. Their disputes must go to the Civil Court.",
      conclusion: "If your main role is managerial/administrative (hiring, firing, policy-making, strategic decisions), the Labour Act does NOT apply to you. You are governed by your employment contract/service rules. Your remedy for wrongful termination is the Civil Court, not the Labour Court. This is a heavily litigated areacourts look at the *nature of daily work*, not just the job title.",
    },
    escalate: true,
    escalateReason: "Determining worker vs. employee status is complex and dictates which court has jurisdiction. Legal advice is crucial.",
    relatedRules: ["lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-020",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["sexual harassment", "harassment at work", " ", "complaints committee", "boss harassment"],
    question: "I am facing sexual harassment at my workplace  what legal protections do I have?",
    irac: {
      issue: "Legal remedies and institutional mechanisms for a worker facing sexual harassment.",
      rule: "Following the 2009 High Court Guidelines (BNWLA v. Government of Bangladesh), every workplace with 20+ employees MUST have a 'Complaints Committee' (majority women, headed by a woman) to handle sexual harassment. The employer must treat it as a disciplinary offence. If the employer fails to form the committee or acts on the complaint, the victim can sue the employer in the Labour Court or under the tort of negligence.",
      application: "Your manager makes inappropriate comments. You report it to HR. If there is no Complaints Committee, the company is already in violation of the High Court order. You can file a complaint with the committee (if it exists), or go directly to the Labour Court / Women & Children Repression Prevention Court depending on the severity of the harassment.",
      conclusion: "Steps: (1) Document everything (texts, emails, witnesses, dates), (2) File a written complaint with the workplace Complaints Committee, (3) If no committee exists or they ignore it, file a case. You can claim damages, transfer, or reinstatement if forced out. Severe cases fall under the Penal Code (Women & Children Repression Prevention Act).",
    },
    escalate: true,
    escalateReason: "Sexual harassment cases require sensitivity, immediate safety planning, and strategic legal action.",
    relatedRules: ["lab-harassment-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-021",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["salary deduction", "illegal deduction", " ", "fine from salary", "damage deduction"],
    question: "Can my employer deduct money from my salary for mistakes or fines?",
    irac: {
      issue: "The legal limits on an employer's power to make deductions from a worker's wages.",
      rule: "Section 123 of the Labour Act 2006 strictly limits deductions to specific categories: absence, damage to goods, house accommodation, provident fund, income tax, and fines. For absence/damage, the deduction cannot exceed the actual loss or wages for the period of absence. Total deductions in any wage period cannot exceed 50% of the worker's wages. Fines cannot exceed 10% of wages in a month.",
      application: "You made a clerical error costing the company BDT 5,000. Your salary is BDT 15,000. The employer wants to deduct BDT 10,000 this month. This is ILLEGAL. They can only deduct the actual loss (BDT 5,000), and even then, total deductions cannot cross 50% of your wage (BDT 7,500).",
      conclusion: "Employers CANNOT arbitrarily deduct salary. Legal deductions: PF, Tax, absence, proven damage, authorized fines. Limits: (1) Total deductions max 50% of wages per month, (2) Fines max 10% of wages per month. Deductions for 'poor performance' or 'late coming' (beyond proportionate absence) are illegal. File a complaint with DIFE if illegally deducted.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-022",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["experience letter", "service certificate", " ", "employer refusing letter", "no experience letter"],
    question: "My employer is refusing to give me my experience/service letter. What can I do?",
    irac: {
      issue: "An employer's obligation to issue a service certificate upon termination or resignation.",
      rule: "Under Section 35 of the Labour Act 2006, an employer MUST issue a service certificate to a worker within 3 working days of receiving a written application. The certificate must state the nature of work and duration of service. Unreasonable refusal or delay is a punishable offence under Section 307 (fine up to BDT 5,000).",
      application: "You resigned and applied for an experience letter. HR ignores you for a month. You file a criminal complaint under Section 307 or a petition in the Labour Court. The court will compel the employer to issue it immediately and may fine them.",
      conclusion: "Apply in writing (keep a copy/receipt). Employer MUST give it within 3 working days. If they refuse: (1) Send a legal notice, (2) File a complaint with the Labour Court or file a criminal case under S.307 for withholding the certificate. Courts take this very seriously as it affects your future employment.",
    },
    escalate: false,
    relatedRules: ["lab-service-cert-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-023",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["forced retirement", "retirement age", " ", "mandatory retirement", "retired against will"],
    question: "Can an employer force me to retire at a certain age?",
    irac: {
      issue: "Whether there is a statutory retirement age in Bangladesh that allows an employer to forcibly retire a worker.",
      rule: "The Bangladesh Labour Act 2006 does NOT specify a mandatory retirement age for private sector workers. Retirement age is determined by the company's Service Rules, Standing Orders, or the individual employment contract. If the service rules specify 60 years, the employer can legally retire the worker at 60 without termination notice pay (though gratuity applies). If no rules exist, forced 'retirement' may be treated as illegal termination.",
      application: "Your company's service rules say retirement age is 57. You turn 57. The employer asks you to leave. This is legal. If your company has NO written service rules, and they try to force you out at 60 claiming 'retirement', you can challenge it in the Labour Court and claim termination benefits (120 days notice).",
      conclusion: "There is NO universal statutory retirement age in BD private sector. It depends on your company's Service Rules. If rules exist and specify an age, they can enforce it. If no rules exist, forced retirement is illegal termination. Check your appointment letter and company policy handbook.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-024",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["minimum wage", "  ", "minimum salary bd", "below minimum wage"],
    question: "What is the minimum wage in Bangladesh?",
    irac: {
      issue: "Determining the applicable minimum wage for a worker.",
      rule: "Bangladesh does not have a single universal minimum wage. Minimum wages are set by sector-specific Minimum Wage Boards under the Labour Act. For example, the RMG sector has a declared minimum wage (last revised significantly in 2023). Agricultural and unorganized sectors often lack formal minimum wage floors. Paying below the sector-specific declared minimum wage is a criminal offence.",
      application: "You work in a garment factory. The government declared the minimum wage for Grade 7 (entry level) as BDT 12,500 (example based on recent board declarations). If your employer pays you BDT 10,000, they are committing a criminal offence under the Labour Act.",
      conclusion: "There is no single minimum wageit varies by SECTOR (RMG, Jute, Leather, etc.). You must check the latest Minimum Wage Board Gazette Notification for your specific industry. If paid below this: (1) It is a crime, (2) You can file a complaint with DIFE or the Labour Court claiming the difference plus compensation.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-025",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["epz labour law", "export processing zone rules", "  ", "epz worker rights", "bepza"],
    question: "Are labour laws different inside the Export Processing Zones (EPZ)?",
    irac: {
      issue: "Whether the standard Bangladesh Labour Act 2006 applies to workers inside EPZs.",
      rule: "No. EPZs are governed by the BEPZA Act 1980 and the EPZ Labour Act 2019, NOT the mainstream Labour Act 2006. While protections like wages, overtime, and leave exist, dispute resolution goes to the EPZ Labour Tribunal/Authority, not the mainstream Labour Court. Trade union rights are heavily restricted; workers form 'Workers' Welfare Associations' instead, which have limited collective bargaining rights.",
      application: "You work in an EPZ garment factory and have a dispute. You cannot go to the regular Labour Court. You must file your complaint with the BEPZA Labour Department or the EPZ Labour Tribunal. You cannot form a standard trade union.",
      conclusion: "YES, laws are different in EPZs. (1) Governed by EPZ Labour Act 2019, not Labour Act 2006. (2) No standard Trade Unionsonly Workers' Welfare Associations. (3) Disputes go to EPZ tribunals. (4) Women CAN work night shifts in EPZs. If you work in an EPZ, ensure your lawyer is familiar with BEPZA laws.",
    },
    escalate: true,
    escalateReason: "EPZ labour disputes require specialized knowledge of the BEPZA framework, which operates parallel to the mainstream system.",
    relatedRules: ["lab-strike-001", "lab-trade-union-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-026",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["rest interval", "break time", " ", "tea break law", "lunch break hours"],
    question: "Am I legally entitled to break times or a lunch break during my 8-hour shift?",
    irac: {
      issue: "Statutory requirements for rest intervals during a working day.",
      rule: "Under Section 107 of the Labour Act 2006, no worker shall be required to work for more than 5 hours without a rest interval of at least 1 hour. This rest interval is usually not counted as working hours (unless the company policy explicitly states otherwise). For adolescent workers (14-18), a 1-hour rest is mandatory after every 2 hours of work.",
      application: "Your shift is 9 AM to 5 PM (8 hours). The employer must give you at least 1 hour off (e.g., 1 PM to 2 PM for lunch). If they force you to work 9 AM to 5 PM continuously without a break, they are violating Section 107.",
      conclusion: "Yes. You MUST get at least a 1-hour break after 5 hours of continuous work. For adults: 1 hour rest after 5 hours. For adolescents (14-18): 1 hour rest after every 2 hours. If your employer denies breaks, file a complaint with DIFE.",
    },
    escalate: false,
    relatedRules: ["lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-027",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["factory closing down", "employer bankrupt", " ", "company shutdown workers", "unpaid wages bankruptcy"],
    question: "My factory is closing down suddenly  how do I get my unpaid wages and dues?",
    irac: {
      issue: "Worker rights and priority of claims when an employer shuts down operations, becomes insolvent, or absconds.",
      rule: "Under Section 278 of the Labour Act 2006, in the event of the closure of an establishment, workers' wages, arrears, and compensation have FIRST PRIORITY over all other debts (even bank loans and government taxes). The employer must give 90 days' notice before closure (unless exempted). If they close illegally, workers can file a class action in the Labour Court.",
      application: "The factory owner locks the gates and flees. You and 200 other workers are owed 3 months' salary. You form a group and file a petition in the Labour Court. The court can attach the factory's machinery, land, and bank accounts to pay the workers FIRST before any bank or supplier gets a single taka.",
      conclusion: "You have FIRST PRIORITY over all other creditors. Steps: (1) Organize affected workers, (2) File a joint petition in the Labour Court immediately, (3) Request the court to attach/seal the factory assets (machinery, inventory) so the owner cannot sell them off, (4) The court will liquidate assets to pay your unpaid wages, notice pay, and gratuity.",
    },
    escalate: true,
    escalateReason: "Factory closures require immediate injunctions to attach assets before they are looted or hidden. Urgent legal action is critical.",
    relatedRules: ["lab-wages-001", "lab-gratuity-001", "lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-028",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["intern rights", "apprentice", "", "unpaid internship", "stipend law"],
    question: "Does the Labour Act apply to interns or apprentices?",
    irac: {
      issue: "Whether interns or apprentices are classified as 'workers' under the Labour Act 2006.",
      rule: "Under the Labour Act, an apprentice is governed separately (often under the Apprenticeship Ordinance 1962) and is primarily there for training, not employment. True interns (students getting practical experience as part of their curriculum) are not 'workers'. However, if an 'intern' is doing regular productive work for the company without being enrolled in an academic program, Bangladesh courts may reclassify them as workers, entitling them to minimum wage and other protections.",
      application: "A university student interns for 3 months as part of their BBA requirement. They get a small stipend. They are likely NOT a worker. A person finishes university and is hired as an 'unpaid intern' for 6 months doing data entry. This is likely a sham internship to avoid paying minimum wage, and a Labour Court may rule they are a worker.",
      conclusion: "True academic interns: Not fully covered. Sham internships (doing real work, not linked to active studies): Likely ILLEGAL. Employers cannot avoid minimum wage by calling someone an 'intern'. If you are doing actual work, you should be paid at least the minimum wage. File a complaint if exploited.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001", "lab-casual-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-029",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["form trade union", "register union", " ", "union formation steps", "employer anti union"],
    question: "How do we legally form and register a trade union?",
    irac: {
      issue: "The statutory process for workers to form and register a trade union.",
      rule: "Under Section 176 of the Labour Act 2006, at least 30% of the total workers in the establishment must be members to apply for registration. The application, along with the union's constitution and list of office bearers, must be submitted to the Registrar of Trade Unions. The Registrar must decide within 60 days. Employers cannot interfere, restrain, or coerce workers trying to form a union (Unfair Labour Practice).",
      application: "A factory has 1,000 workers. You need at least 300 workers to sign up as members. You draft a constitution, hold an election for leaders, and submit the papers to the Registrar. If the employer threatens to fire the leaders, that is an unfair labour practice punishable under the Act.",
      conclusion: "Steps: (1) Gather 30% of workers as members, (2) Draft a Union Constitution, (3) Hold elections for office bearers, (4) Submit application to the Registrar of Trade Unions (under the Ministry of Labour). Employer retaliation (firing, threatening, transferring union leaders) is strictly illegalreport it to DIFE or the Labour Court immediately.",
    },
    escalate: false,
    relatedRules: ["lab-trade-union-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-030",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["leave encashment", "cash out leave", " ", "unused annual leave", "leave balance payment"],
    question: "Can I get paid for my unused annual leave when I leave the company?",
    irac: {
      issue: "Whether a worker is entitled to monetary compensation for earned but unused annual leave upon termination or resignation.",
      rule: "The Bangladesh Labour Act 2006 is SILENT on the encashment (cashing out) of unused annual leave. However, the Bangladesh Labour Rules 2015 and standard judicial interpretation dictate that if the worker is terminated, retrenched, or the employer closes down, the worker is entitled to encashment of earned but unavailed leave at their current daily wage rate.",
      application: "You have 15 days of unused annual leave. You are terminated. You can claim 15 days' wages as leave encashment in your final settlement. However, if you simply resign and the company policy says 'leave lapses on resignation', you might have to fight for it in the Labour Court (where courts often favor the worker).",
      conclusion: "If terminated/retrenched/factory closed: YES, you are legally entitled to be paid for unused annual leave. If you resign: It depends on company policy, but Labour Courts frequently order employers to pay it anyway. Calculate: (Monthly Salary / 26)  Number of unused leave days. Include this in your final settlement demand.",
    },
    escalate: false,
    relatedRules: ["lab-leave-001", "lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-031",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["suspended pending enquiry", "", "suspension pay", "suspended without pay"],
    question: "My employer suspended me pending a domestic enquiry  do I get paid during suspension?",
    irac: {
      issue: "Whether a worker is entitled to wages during a period of suspension pending a domestic enquiry.",
      rule: "Under the Bangladesh Labour Rules 2015 (Rule 24), if a worker is suspended pending an enquiry, they are entitled to receive a subsistence allowance equal to 50% of their basic wages during the first 90 days of suspension. If the enquiry is prolonged beyond 90 days through no fault of the worker, the allowance may increase to 75% or 100% at the employer's discretion or court's order.",
      application: "You are suspended on January 1 for an alleged theft. You must be paid 50% of your basic salary for the first 90 days. If the enquiry drags on until May without you causing delays, you can apply to the Labour Court to increase the allowance to 100%.",
      conclusion: "Yes, but only HALF pay (50% of basic) for the first 90 days. If the employer takes longer than 90 days due to their own delays, you can petition the Labour Court to force them to pay 75% or full pay. Being suspended does NOT mean you are fired.",
    },
    escalate: false,
    relatedRules: ["lab-dismissal-001", "lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-032",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["final settlement", "full and final", " ", "last dues clearance", "final pay"],
    question: "How long does my employer have to clear my final settlement after I leave?",
    irac: {
      issue: "The statutory time limit for an employer to pay a separating worker's final dues (wages, gratuity, leave encashment).",
      rule: "While the Labour Act specifies wage payment periods (7-10 days), the standard judicial interpretation and Bangladesh Labour Rules require that full and final settlement (including gratuity, notice pay, and leave encashment) must be cleared within 30 working days of the worker's last working day. Unreasonable delay allows the worker to claim interest and file for recovery.",
      application: "Your last day is March 1. You should receive your final settlement by April 10 (roughly 30 working days). If June arrives and you still haven't been paid, you can file a case in the Labour Court claiming the dues plus interest for the delayed period.",
      conclusion: "The standard timeline is 30 working days from your last working day. This includes: Unpaid salary, Notice pay (if applicable), Gratuity, Leave encashment, PF withdrawal (if applicable). If delayed: Send a legal notice. If still not paid, file a Labour Court case claiming the principal amount + interest for the delay.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-033",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["piece rate worker", " ", "piece rated wage calculation", "paid per piece"],
    question: "I am paid per piece produced  how does overtime and minimum wage apply to me?",
    irac: {
      issue: "Applying minimum wage and overtime rules to piece-rated workers.",
      rule: "Under the Labour Act, a piece-rated worker must earn at least the minimum wage for the hours worked. To calculate overtime for a piece-rated worker, their daily average earnings over the last 3 months are taken as the 'ordinary rate of wages'. Overtime must be paid at double this calculated ordinary rate.",
      application: "You sew garments and are paid BDT 5 per piece. You work 10 hours (2 hours overtime). Your average daily earning over 3 months is BDT 500. Your ordinary hourly rate is 500/8 = BDT 62.50. Overtime rate = 62.50  2 = BDT 125 per hour. You must be paid BDT 500 (for 8 hrs) + BDT 250 (for 2 hrs OT) = BDT 750 for that day.",
      conclusion: "Even if paid per piece, you are protected by minimum wage laws. If your piece-rate earnings fall below the minimum wage for standard hours, the employer MUST top it up. Overtime is calculated based on your 3-month average daily earnings, and MUST be paid at double that average rate for hours beyond 8/day.",
    },
    escalate: false,
    relatedRules: ["lab-overtime-001", "lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-034",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["equal pay gender", "women paid less", " ", "same work different pay"],
    question: "Is it legal for my employer to pay me less than a male colleague for the same work?",
    irac: {
      issue: "The legal stance on gender-based wage discrimination in the private sector in Bangladesh.",
      rule: "While the Bangladesh Labour Act 2006 does not contain an explicit 'Equal Pay for Equal Work' clause for the private sector, the Constitution of Bangladesh (Article 27 & 29) guarantees equality before the law and non-discrimination based on sex. Furthermore, international conventions (ILO C100) ratified by Bangladesh support equal pay. Courts have ruled that arbitrary gender-based pay differences for identical work are unconstitutional.",
      application: "You and a male colleague were hired on the same day, with the same qualifications, doing the exact same job. He gets BDT 20,000, you get BDT 15,000. If the only reason is your gender, this is discriminatory. You can file a constitutional writ in the High Court or a discrimination claim.",
      conclusion: "Explicit statutory protection in the Labour Act is weak, but the Constitution of Bangladesh PROHIBITS gender discrimination. If you are paid less purely because of gender for the exact same work: (1) Gather evidence of job roles and pay slips, (2) Send an internal complaint, (3) Consult a lawyer to file a writ petition in the High Court Division.",
    },
    escalate: true,
    escalateReason: "Gender discrimination claims require constitutional writs which need specialized high-court litigation.",
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-035",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["provident fund withdrawal", "pf transfer", "  ", "provident fund resign", "pf balance"],
    question: "Can I withdraw my full Provident Fund when I resign?",
    irac: {
      issue: "The rules regarding withdrawal of the employee's own contribution and the employer's contribution to the PF upon resignation.",
      rule: "Under the EPF Ordinance 1961, the worker's OWN contribution can always be withdrawn upon leaving the job. The EMPLOYER'S contribution is subject to 'vesting' rules. Vesting depends on years of service: generally 50% vests after 3 years, 75% after 5 years, and 100% after 10 years. If you resign before 3 years, you may forfeit the employer's contribution.",
      application: "You resign after 2 years. You get 100% of your own contributions back. But because you haven't completed 3 years, you might not get the employer's contribution. If you resign after 5 years, you get your full contribution + 75% of the employer's contribution.",
      conclusion: "Your own money: ALWAYS refundable. Employer's money: Depends on vesting (Years of service required). Check your specific PF Trust rules. Apply for withdrawal immediately after your last day. The PF authority must settle the claim within a specific timeframe (usually 30-60 days). If they delay, file a Labour Court case.",
    },
    escalate: false,
    relatedRules: ["lab-pf-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-036",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["salary cut", "salary reduced", " ", "pay cut company", "reduced salary without consent"],
    question: "Can my employer reduce my salary without my written consent?",
    irac: {
      issue: "Whether an employer has the unilateral power to cut an existing worker's salary.",
      rule: "Under Section 123 of the Labour Act 2006, deductions are heavily restricted. A unilateral pay cut is NOT a permitted deduction. Under contract law, salary is a core term of the employment contract. An employer CANNOT unilaterally reduce it without the worker's written consent, unless the worker's designation and duties are also formally reduced (demotion with consent).",
      application: "The company faces losses and sends an email saying 'All salaries are cut by 20% starting next month.' Without your signed consent, this is illegal. You can refuse the cut, continue working, and claim the full amount. If they force it, it amounts to unlawful deduction of wages.",
      conclusion: "NO. An employer CANNOT cut your salary unilaterally. It requires your WRITTEN CONSENT. If they do it without consent: (1) Send a written objection immediately, (2) Keep working (don't abandon the job), (3) File a claim in the Labour Court for the deducted amount. A company facing financial trouble must negotiate, not dictate.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-037",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["work from home", "remote work", "  ", "wfh rights", "telecommuting bd"],
    question: "Do standard labour rights apply if I am working from home (WFH)?",
    irac: {
      issue: "The applicability of the Labour Act 2006 to remote work/telecommuting arrangements.",
      rule: "The Bangladesh Labour Act 2006 was drafted with traditional factories and offices in mind and does not explicitly mention 'work from home'. However, legal jurisprudence dictates that if the worker is under the control, supervision, and direction of the employer (the 'control test'), they are still a 'worker' under the Act, regardless of physical location.",
      application: "Your IT company asks you to work from home permanently. Your hours are tracked via software, you report to a manager, and you are paid a monthly salary. You are still a worker. If they fire you via email without 120 days' notice, it is still illegal termination under S.26.",
      conclusion: "YES, labour rights apply to WFH. The 'Control Test' determines your status. If the company controls your hours, tasks, and output, you are an employee/worker. You are entitled to overtime (if hours are tracked), leave, and notice period. However, practical issues like workplace safety (S.51-61) do not apply to your home.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-038",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["government holiday work", " ", "working on public holiday", "bangla noboborsho work"],
    question: "If I work on a government-declared public holiday (like 26 March or 21 Feb), what am I owed?",
    irac: {
      issue: "Compensation for working on a declared public/national holiday.",
      rule: "Under Section 103 of the Labour Act 2006, workers are entitled to 11 days of festival leave with full pay, which typically aligns with national holidays. If an employer compels a worker to work on a public holiday, the worker must be paid at double the ordinary rate of wages for that day, AND given a compensatory substitute holiday within the same month.",
      application: "You are forced to work on Independence Day (March 26). You must be paid 2x your daily wage for that day, AND you must be given another day off later that month to compensate for the holiday you missed.",
      conclusion: "Working on a National/Public Holiday: You get (1) DOUBLE WAGES for that day, AND (2) A Compensatory Holiday on another day. If your employer gives you neither, keep attendance proof and file a DIFE complaint or Labour Court case for the double wages owed.",
    },
    escalate: false,
    relatedRules: ["lab-leave-001", "lab-overtime-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-039",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["foreign worker rights", "expat labour law", " ", "foreign employee bd"],
    question: "Do foreign nationals working in Bangladesh have the same labour rights?",
    irac: {
      issue: "Whether the Bangladesh Labour Act 2006 applies to expatriate/foreign workers.",
      rule: "Yes. The Labour Act 2006 defines a 'worker' based on the nature of the work and the employment relationship, NOT on nationality. Therefore, foreign workers employed in Bangladesh are entitled to the same statutory protections (notice period, gratuity, leave) as local workers. However, foreign workers must also comply with immigration laws (work permit from DIFE/Ministry of Labour).",
      application: "A British national works as an operations manager at a BD company. If the company terminates him without 120 days' notice, he has the exact same right to file a Labour Court case as a Bangladeshi citizen. His nationality does not strip him of statutory labour rights.",
      conclusion: "YES. Foreign workers have the EXACT SAME rights under the Labour Act as Bangladeshi workers (notice, gratuity, leave, protection from unfair dismissal). However, foreign workers must ensure their Employment Visa and Work Permit are legally validif they are working illegally (without a permit), they cannot claim statutory benefits in court.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-gratuity-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-040",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["workplace bullying", "harassed by boss", " ", "toxic workplace", "verbal abuse"],
    question: "I am being severely bullied and verbally abused by my manager  is there legal recourse?",
    irac: {
      issue: "Whether non-sexual workplace bullying, mental harassment, or verbal abuse is actionable under Bangladesh labour law.",
      rule: "The Bangladesh Labour Act 2006 does not explicitly define or penalize 'workplace bullying' or 'mental harassment' unless it crosses into sexual harassment or physical assault. However, if the bullying forces a worker to resign, it can be argued as 'constructive dismissal' (forced resignation due to hostile environment). If the abuse is physical, Penal Code charges (assault) apply.",
      application: "Your manager screams at you daily, insults your intelligence, and isolates you from meetings. You cannot take it anymore and resign. You can file a Labour Court case arguing 'constructive dismissal'claiming the employer made the environment so hostile that a reasonable person would be forced to resign, thereby entitling you to termination benefits (120 days notice, gratuity).",
      conclusion: "There is no direct 'anti-bullying' law. Your options: (1) If it's sexual harassment  High Court guidelines apply, (2) If it's physical assault  File criminal case under Penal Code, (3) If it's mental abuse forcing you to quit  Claim 'Constructive Dismissal' in Labour Court to get your termination benefits. Document everything (texts, audio, witnesses).",
    },
    escalate: false,
    relatedRules: ["lab-dismissal-001", "lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-041",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["change job role", "demotion", "  ", "transferred without consent", "forced transfer"],
    question: "Can my employer transfer me to a different city or demote me without my consent?",
    irac: {
      issue: "The employer's power to unilaterally transfer or demote a worker.",
      rule: "The Labour Act 2006 is silent on transfers and demotions. These are governed by the company's Standing Orders or Service Rules. However, courts have established that transfers/demotions must be made in good faith (for business needs) and not as a punitive measure or victimization. A transfer that causes extreme hardship (e.g., moving a family from Dhaka to Teknaf overnight without notice) can be challenged as unreasonable.",
      application: "You are a senior accountant. The boss demotes you to clerk because you reported corruption. This is punitive demotionyou can challenge it in the Labour Court. If the company transfers you to a different branch for a valid business rotation with 30 days' notice, it is generally legal.",
      conclusion: "Employers CAN transfer/demote IF: (1) The company's Service Rules allow it, (2) It is done in good faith (business need), (3) It is not punitive. You can challenge it in the Labour Court IF: (1) It is victimization (punishment for complaining), (2) It causes undue hardship, (3) The service rules don't permit it. Demotion usually requires a show-cause notice.",
    },
    escalate: false,
    relatedRules: ["lab-dismissal-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-042",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["outsourced worker", "subcontractor employee", " ", "third party payroll", "who is real employer"],
    question: "I work in a factory but I am on a contractor's payroll  who is my legal employer?",
    irac: {
      issue: "Determining the real employer when a worker is supplied by a third-party contractor or outsourcing agency.",
      rule: "Under Section 2(65) and jurisprudence, if a worker is employed by a contractor but works under the direct supervision and control of the principal employer (the factory), the principal employer can be held jointly liable for statutory obligations (wages, safety, compensation). The Contract Labour (Regulation and Abolition) Act 1970 also mandates principal employers to ensure contractors pay minimum wages.",
      application: "You are on 'ABC Manpower Agency' payroll but work daily at 'XYZ Garments'. ABC doesn't pay you on time. You can file a case against BOTH ABC Manpower AND XYZ Garments. The law prevents companies from escaping liability by hiding behind third-party contractors.",
      conclusion: "You can hold BOTH the contractor AND the principal employer (the factory/company where you actually work) legally liable. If the contractor fails to pay minimum wage or gratuity, the principal employer is responsible for ensuring compliance. File your Labour Court case naming both parties.",
    },
    escalate: false,
    relatedRules: ["lab-wages-001", "lab-casual-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-043",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["refusing to accept resignation", "forced to stay", "   ", "employer not accepting resign"],
    question: "My employer is refusing to accept my resignation letter  am I still bound to work?",
    irac: {
      issue: "Whether an employer's refusal to accept a resignation letter prevents the worker from legally leaving.",
      rule: "Under Section 27 of the Labour Act 2006, a permanent worker can resign by giving 30 days' written notice. Resignation is a unilateral rightit does NOT require the employer's 'acceptance' or 'approval'. If you give 30 days' notice, the employment automatically terminates on the 30th day, regardless of whether the employer signs or accepts it.",
      application: "You hand in your resignation on January 1st. The boss throws it in the bin and says 'I don't accept it.' You continue working until January 30th. On January 31st, you stop going to work. You are legally resigned. The employer cannot claim you absconded.",
      conclusion: "Your resignation does NOT need employer approval. It only needs proper NOTICE (30 days for permanent workers). Send the resignation via email AND registered post so you have proof of delivery. Work your 30 days, hand over your duties, and leave. If they refuse your final settlement, file a Labour Court case.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-044",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["notice period buyout", "pay instead of notice", "  ", "short notice"],
    question: "Can I pay money instead of working my notice period?",
    irac: {
      issue: "Whether a worker can buy out their notice period by paying the employer.",
      rule: "Section 27 of the Labour Act 2006 states that if a worker resigns without giving the required notice (30 days), the employer may deduct an amount equal to the notice period's wages from the worker's final dues. The law frames this as a right of the EMPLOYER to deduct, not a right of the WORKER to pay. However, practically, if you offer to pay the 30 days' wages, employers usually accept it to let you leave early.",
      application: "You get a better job offer and want to leave in 5 days. You tell your employer 'I will pay you 25 days' salary instead of working the notice.' The employer can accept this, but legally, they are not forced to accept itthey could insist you work the full 30 days or face deduction of 30 days' pay from your PF/gratuity later.",
      conclusion: "You cannot FORCE the employer to let you buy out the notice period. It is an employer's right to deduct pay for short notice, not a worker's right to buy out. However, most modern companies accept 'notice buyouts' if you negotiate professionally. Get any buyout agreement IN WRITING to avoid future disputes over absconding.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-045",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["labour court order not followed", "employer ignored verdict", "  ", "execute labour court order"],
    question: "I won my case in the Labour Court, but the employer is still not paying  what do I do?",
    irac: {
      issue: "The remedy available to a worker when an employer defies or ignores a Labour Court judgment.",
      rule: "Under Section 35 of the Labour Act 2006 (read with the Code of Civil Procedure 1908), a Labour Court decree is executable like a Civil Court decree. The winning party must file an Execution Petition. The court can then attach and sell the employer's property, arrest the employer for civil detention, or appoint a receiver to recover the money.",
      application: "The court ordered your company to pay you BDT 5 lakh in 60 days. 6 months pass, no payment. You file an Execution Petition. The court sends bailiffs to seal the factory's bank accounts or machinery, forcing the employer to pay.",
      conclusion: "Do not sit idle. File an Execution Petition immediately after the deadline for payment passes. The court has strong powers: (1) Attach bank accounts, (2) Seize and auction machinery/property, (3) Arrest the employer/directors (civil prison). Execution is a separate legal stepyou must actively file for it.",
    },
    escalate: true,
    escalateReason: "Execution of court decrees requires filing specific procedural petitions and tracking enforcement actions.",
    relatedRules: ["lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-046",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["probation notice period", "quit during probation", " ", "probation termination notice"],
    question: "How much notice do I have to give if I want to quit during my probation period?",
    irac: {
      issue: "The statutory notice requirement for a worker resigning while on probation.",
      rule: "Under Section 22 of the Labour Act 2006, either party (employer or worker) can terminate the employment during probation by giving 60 days' notice or paying 60 days' wages in lieu. This applies equally to the worker resigning.",
      application: "You are 2 months into a 6-month probation and want to leave immediately. You must either work 60 more days, or the employer can deduct 60 days' wages from your final settlement.",
      conclusion: "You must give 60 DAYS' notice during probation (same as the employer). If you leave without it, the employer will deduct 60 days' pay from your dues. Note: Your appointment letter might specify a shorter notice period (e.g., 14 days). If the contract says 14 days, courts often uphold the contractual term over the statutory default for probationers.",
    },
    escalate: false,
    relatedRules: ["lab-probation-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-047",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["whistleblower", "reported corruption", " ", "fired for reporting", "retaliation reporting"],
    question: "I was fired because I reported illegal activities (corruption/pollution) in my company  am I protected?",
    irac: {
      issue: "Legal protections for workers who face retaliation for whistleblowing.",
      rule: "Bangladesh does not have a comprehensive 'Whistleblower Protection Act' for the private sector. However, if you report criminal offenses (like tax evasion, massive fraud, environmental violations) to the authorities, and the employer fires you for it, you can frame your Labour Court case as 'wrongful termination' and 'victimization/unfair labour practice'. If the report was to an anti-corruption body, some limited protections under the ACC Act may apply.",
      application: "You report your factory to the Department of Environment for dumping toxic waste. The factory finds out and fires you. You file a Labour Court case stating you were terminated for performing a lawful civic duty, not for misconduct. The court will view the termination as punitive, illegal, and malicious.",
      conclusion: "There is no specific whistleblower law, but courts WILL protect you. If fired for reporting illegal acts: (1) Ensure you reported to a formal authority (not just office gossip), (2) Keep proof of your report, (3) File a Labour Court case claiming punitive termination. Courts often award maximum compensation for such malicious dismissals.",
    },
    escalate: true,
    escalateReason: "Whistleblower retaliation cases require careful legal framing to maximize compensation and ensure safety.",
    relatedRules: ["lab-dismissal-001", "lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-048",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["bank employee rights", "financial institution labour act", " ", "banker termination"],
    question: "Does the Labour Act apply to bank employees?",
    irac: {
      issue: "Whether employees of commercial banks fall under the Bangladesh Labour Act 2006.",
      rule: "No. Bank employees in Bangladesh are generally governed by the Bank Company Act 1991 and their respective internal Service Rules (e.g., Janata Bank Service Rules, Standard Chartered HR Policy), NOT the Labour Act 2006. They cannot file cases in the Labour Court. Their disputes must be resolved through internal arbitration or the Civil Court.",
      application: "A bank officer is terminated. They cannot go to the Labour Court under Section 33. They must go to the Civil Court or follow the specific arbitration clause in their bank's service rules.",
      conclusion: "NO. The Labour Act does NOT apply to bank employees. You are governed by your Bank's Service Rules. Disputes go to Civil Court or internal arbitration. However, banks must still comply with minimum wage (if applicable), maternity rules (per Bangladesh Bank circulars), and tax laws. Always read your bank's specific 'Service Rules' bookletit is your constitution.",
    },
    escalate: false,
    relatedRules: ["lab-court-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-049",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["grievance committee", "participatory committee", " ", "internal dispute resolution"],
    question: "My company has a Grievance Committee  do I have to use it before going to court?",
    irac: {
      issue: "Whether approaching the internal grievance/participatory committee is a mandatory pre-condition for filing a case in the Labour Court.",
      rule: "Under Section 205 of the Labour Act 2006, establishments with 50+ workers must have a Participatory Committee to resolve internal disputes. However, using this committee is NOT a mandatory legal prerequisite for filing a case in the Labour Court. A worker can bypass the internal committee and go directly to the Labour Court if they choose.",
      application: "You have a wage dispute. HR says you must first present it to the Participatory Committee and wait 30 days. You are not legally bound to do this. If you want immediate legal action, you can directly file in the Labour Court.",
      conclusion: "NO, it is NOT mandatory to use the internal committee first. You can go straight to the Labour Court. However, as a practical matter, trying the internal committee first can save time and money if the issue is simple. But if the employer is acting in bad faith, do not waste timego directly to court before the 2-year limitation expires.",
    },
    escalate: false,
    relatedRules: ["lab-court-001", "lab-trade-union-001"],
    lastVerified: "2025-04-01",
  },
  {
    id: "lab-qa-050",
    area: "labour",
    jurisdiction: "BD",
    triggerKeywords: ["no appointment letter", "verbal job", " ", "working without letter", "prove employment"],
    question: "I have been working for 2 years but never received an appointment letter  am I still a legal worker?",
    irac: {
      issue: "Whether the absence of a formal appointment letter invalidates a worker's statutory rights under the Labour Act.",
      rule: "Under Section 8 of the Labour Act 2006, it is mandatory for the employer to issue an appointment letter. However, the ABSENCE of an appointment letter does NOT mean the employment relationship doesn't exist. If you can prove you work for the employer (attendance records, salary bank transfers, ID card, emails), the law recognizes you as a worker, and the employer's failure to issue a letter is actually a separate offence under Section 307.",
      application: "You work at a restaurant for 2 years, paid in cash, no letter. The owner fires you without notice. You use your bKash transfer records, WhatsApp messages with the boss, and witness testimonies from coworkers to prove employment. The Labour Court will accept this evidence and punish the employer for not issuing an appointment letter.",
      conclusion: "YES, you are absolutely a legal worker. The law looks at the REALITY of the relationship, not just a piece of paper. Prove your employment with: (1) Bank/bKash salary transfers, (2) Workplace ID card, (3) Official WhatsApp/Email groups, (4) Attendance registers/CCTV, (5) Coworker witnesses. The employer will be fined for not issuing the letter, AND ordered to pay your full dues.",
    },
    escalate: false,
    relatedRules: ["lab-termination-001", "lab-wages-001"],
    lastVerified: "2025-04-01",
  },
];

const labourModule: KnowledgeModule = {
  area: "labour",
  label: "Labour Law",
  description: "Knowledge module for labour law in Bangladesh.",
  rules,
  qaBank,
};

export default labourModule;