// ─── JesAI NRB Investment Law Knowledge Module ───────────────
// NLC validated — Nazmul, Advocate, Supreme Court of Bangladesh
// Covers: BIDA, Bangladesh Bank FX, WHT, DTAA, Remittance,
//         Foreign Investment, NRB rights, Repatriation
// Last verified: 2025-03-09

import type { KnowledgeModule, LegalRule, QAEntry } from "./types";

const rules: LegalRule[] = [
  {
    id: "nrb-bida-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "BIDA Registration — Foreign Investment",
    rule: "All foreign investment in Bangladesh requires registration with the Bangladesh Investment Development Authority (BIDA). BIDA OSS (One Stop Service) processes registration. 100% foreign ownership permitted in most sectors. Minimum capital requirement: USD 50,000 for foreign companies.",
    source: "Bangladesh Investment Development Authority Act 2016",
    certainty: "confirmed",
    tags: ["bida", "foreign investment", "registration", "100% ownership", "oss"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-repatriate-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "Profit Repatriation — Foreign Investors",
    rule: "Foreign investors may repatriate post-tax profits, dividends, capital, and royalties freely through authorized dealer banks. Bangladesh Bank approval required for amounts above prescribed limits. All repatriation must be through banking channels.",
    source: "Foreign Exchange Regulation Act 1947; Bangladesh Bank FX Guidelines",
    certainty: "confirmed",
    tags: ["repatriation", "profit", "dividend", "foreign investor", "bangladesh bank"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-wht-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "Withholding Tax on Foreign Payments",
    rule: "Bangladesh imposes WHT on payments to non-residents: Dividends 20%, Interest 20%, Royalties 20%, Technical fees 10%, Management fees 10%. DTAA countries get reduced rates. WHT deducted at source by the paying company.",
    source: "Income Tax Act 2023, Sections 98-101; DTAA Treaties",
    certainty: "confirmed",
    tags: ["wht", "withholding tax", "dividend", "royalty", "non-resident", "dtaa"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-dtaa-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "Double Taxation Avoidance Agreements",
    rule: "Bangladesh has DTAA with 30+ countries including USA, UK, Japan, China, India, Germany, Singapore, Malaysia, UAE, Saudi Arabia, Canada, Australia, South Korea. DTAA reduces or eliminates double taxation on income earned in Bangladesh by residents of treaty countries.",
    source: "Income Tax Act 2023; Individual DTAA Treaties",
    certainty: "confirmed",
    tags: ["dtaa", "double taxation", "treaty", "usa", "uk", "japan", "china"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-remittance-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "Inward Remittance — 2.5% Cash Incentive",
    rule: "Bangladesh government provides 2.5% cash incentive on inward foreign remittance sent through legal banking channels (SWIFT, exchange houses). Incentive paid by Bangladesh Bank. Remittance through hundi/hawala is illegal under Foreign Exchange Regulation Act 1947.",
    source: "Bangladesh Bank Circular; Foreign Exchange Regulation Act 1947",
    certainty: "confirmed",
    tags: ["remittance", "2.5%", "incentive", "inward", "hundi", "hawala", "nrb"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-property-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "NRB Property Rights in Bangladesh",
    rule: "Non-Resident Bangladeshis can purchase, hold, and sell property in Bangladesh. Property can be purchased using foreign remittance or NRB accounts (NFCD/RFCD). No special permission required for NRBs to buy immovable property. Inheritance rights same as resident Bangladeshis.",
    source: "Transfer of Property Act 1882; Bangladesh Bank FX Guidelines",
    certainty: "confirmed",
    tags: ["nrb", "property", "land", "purchase", "nfcd", "rfcd", "inheritance"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-account-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "NRB Bank Accounts — NFCD and RFCD",
    rule: "NRBs can open NFCD (Non-Resident Foreign Currency Deposit) accounts in USD, GBP, EUR, JPY. RFCD (Resident Foreign Currency Deposit) for returnees. Interest on NFCD is tax-free. Funds freely repatriable. Can be operated from abroad. Available at all authorized dealer banks.",
    source: "Bangladesh Bank Foreign Exchange Guidelines",
    certainty: "confirmed",
    tags: ["nfcd", "rfcd", "nrb account", "foreign currency", "tax free", "interest"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-tax-holiday-001",
    area: "nrb",
    jurisdiction: "BD",
    title: "Tax Holiday for Foreign Investors",
    rule: "Foreign investors in priority sectors get tax holidays: EPZ — 10 years full exemption. SEZ — 10 years full exemption. Priority sectors outside EPZ/SEZ — 5-10 years depending on location. Reduced corporate tax rate of 20% for listed companies (standard 27.5%).",
    source: "Income Tax Act 2023; BIDA Act 2016; EPZ Authority Act",
    certainty: "confirmed",
    tags: ["tax holiday", "epz", "sez", "10 years", "foreign investor", "exemption"],
    lastVerified: "2025-03-09",
  },
];

const qaBank: QAEntry[] = [
  {
    id: "nrb-qa-001",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["register company bangladesh", "foreign company bangladesh", "set up business bangladesh", "bida registration", "start business bangladesh"],
    question: "How do I register a foreign company in Bangladesh?",
    irac: {
      issue: "What is the legal process for a foreign national or company to establish a business in Bangladesh?",
      rule: "Bangladesh Investment Development Authority (BIDA) Act 2016: All foreign investment requires BIDA registration. 100% foreign ownership allowed in most sectors. Minimum investment USD 50,000. Companies Act 1994 governs company formation.",
      application: "A foreign investor must: (1) Choose entity type — subsidiary (Pvt Ltd), branch office, or liaison office. (2) Register with BIDA OSS (One Stop Service). (3) Incorporate with RJSC under Companies Act 1994. (4) Register with Bangladesh Bank for FDI reporting. (5) Obtain trade licence, TIN, VAT registration.",
      conclusion: "**How to register a foreign company in Bangladesh:**\n\n**Step 1 — Choose entity:**\n• Subsidiary (Pvt Ltd): Full commercial operations, 100% foreign ownership ✅\n• Branch Office: Extension of foreign parent, limited activities\n• Liaison/Rep Office: Marketing only, no revenue generation\n\n**Step 2 — BIDA Registration:**\n• Apply at bida.gov.bd OSS portal\n• Documents: MOA/AOA, board resolution, audited accounts, passport copies\n• Timeline: 7-15 working days\n\n**Step 3 — Bangladesh Bank FDI Registration:**\n• Report inward FDI within 30 days of fund receipt\n\n**Step 4 — RJSC Incorporation (for subsidiary):**\n• Same as local Pvt Ltd — Name clearance → MOA/AOA → File → Certificate\n\n📄 Full foreign company setup — NLC can assist.\n⚠️ Information only. Consult an advocate.",
    },
    escalate: false,
    relatedRules: ["nrb-bida-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-002",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["send money bangladesh", "remittance bangladesh", "transfer money bangladesh", "hundi", "send remittance"],
    question: "How do I legally send money to Bangladesh from abroad?",
    irac: {
      issue: "What are the legal channels for remitting money to Bangladesh and what incentives exist?",
      rule: "Foreign Exchange Regulation Act 1947: All foreign exchange transactions must go through authorized channels. Bangladesh Bank Circular: 2.5% cash incentive on inward remittance through legal banking channels. Hundi/hawala is illegal.",
      application: "Legal channels: SWIFT bank transfer, authorized exchange houses (Western Union, MoneyGram, bKash international, Nagad), mobile financial services approved by Bangladesh Bank. The 2.5% incentive is automatic — no application needed — credited to recipient's account.",
      conclusion: "**Legal remittance channels:**\n\n✅ Bank-to-bank SWIFT transfer\n✅ Authorized exchange houses (Western Union, MoneyGram)\n✅ bKash international (from select countries)\n✅ Bank's own remittance apps\n\n**2.5% Government Incentive:**\n• Automatic — no application needed\n• Credited by Bangladesh Bank\n• Available on all legal channel remittances\n\n❌ ILLEGAL: Hundi/hawala — criminal offence under FERA 1947\n\n📋 NRB remittance guide — ৳99",
    },
    escalate: false,
    relatedRules: ["nrb-remittance-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-003",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["withholding tax", "wht", "tax on dividend", "tax on royalty", "non-resident tax bangladesh"],
    question: "What is withholding tax (WHT) on payments to foreign companies in Bangladesh?",
    irac: {
      issue: "What withholding tax rates apply when a Bangladesh company pays dividends, royalties, or fees to a non-resident company?",
      rule: "Income Tax Act 2023: WHT on dividends to non-residents 20%. WHT on interest 20%. WHT on royalties 20%. WHT on technical/management fees 10%. DTAA countries get reduced rates under applicable treaties.",
      application: "If a Bangladesh subsidiary pays dividend to its US parent: Standard WHT = 20%. Under Bangladesh-USA DTAA, rate may be reduced to 10-15%. The Bangladesh company deducts WHT before payment and remits to NBR. Parent company can claim credit in home country under DTAA.",
      conclusion: "**WHT Rates — Bangladesh (non-DTAA):**\n\n| Payment Type | WHT Rate |\n|---|---|\n| Dividend | 20% |\n| Interest | 20% |\n| Royalty | 20% |\n| Technical fees | 10% |\n| Management fees | 10% |\n\n**DTAA Countries get reduced rates:**\n• USA, UK, Japan, China, India — check specific treaty\n• DTAA benefit requires tax residency certificate from home country\n\n📄 DTAA analysis for your country — NLC can advise.\n⚠️ Information only. Consult a tax advocate.",
    },
    escalate: false,
    relatedRules: ["nrb-wht-001", "nrb-dtaa-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-004",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["repatriate profit", "send profit abroad", "take money out bangladesh", "profit repatriation", "dividend repatriation"],
    question: "How can a foreign investor take profits out of Bangladesh?",
    irac: {
      issue: "What is the legal process for repatriating profits, dividends, and capital from Bangladesh?",
      rule: "Bangladesh Bank FX Guidelines: Foreign investors may repatriate post-tax profits and dividends freely through authorized dealer banks. No ceiling on repatriation amount. Capital invested (equity) repatriable on winding up after settling all liabilities.",
      application: "Process: Pay corporate income tax → Declare dividend at AGM → Deduct WHT → Apply to authorized dealer bank with audited accounts, board resolution, and tax clearance → Bank remits to foreign account via SWIFT. Bangladesh Bank approval needed above USD 500,000.",
      conclusion: "**Profit Repatriation — Bangladesh:**\n\n✅ Fully allowed — no restrictions on amount\n✅ Through authorized dealer banks only\n✅ After payment of all Bangladesh taxes\n\n**Process:**\n1. Pay corporate income tax\n2. Declare dividend at AGM\n3. Deduct WHT at applicable rate\n4. Apply to AD bank with documents\n5. Bank remits via SWIFT\n\n**Documents needed:**\n• Audited financial statements\n• Board resolution for dividend\n• Tax clearance certificate (NBR)\n• BIDA registration certificate\n\n📄 Full repatriation guide — NLC can assist.",
    },
    escalate: false,
    relatedRules: ["nrb-repatriate-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-005",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["nrb buy land", "nrb property", "buy property bangladesh from abroad", "overseas bangladeshi property", "non-resident buy land"],
    question: "Can an NRB (Non-Resident Bangladeshi) buy land or property in Bangladesh?",
    irac: {
      issue: "What are the rights of Non-Resident Bangladeshis to purchase and hold immovable property in Bangladesh?",
      rule: "Transfer of Property Act 1882: No restriction on NRBs purchasing property. Bangladesh Bank Guidelines: Property can be purchased using inward remittance or NFCD/RFCD account funds. No special government permission required.",
      application: "An NRB in UK can purchase land in Bangladesh by: sending money through legal remittance channel to NFCD account → using that money to pay vendor → executing sale deed at Sub-Registrar office → mutation at Upazila Land Office. The NRB may appoint a Power of Attorney to act on their behalf in Bangladesh.",
      conclusion: "**NRB Property Rights:**\n\n✅ Can buy land and property freely\n✅ No special permission needed\n✅ Same rights as resident Bangladeshis\n✅ Can use Power of Attorney for transactions\n\n**How to buy from abroad:**\n1. Send money via legal remittance to NFCD account\n2. Appoint Power of Attorney in Bangladesh\n3. Conduct due diligence (title search, khatian check)\n4. Execute sale deed at Sub-Registrar\n5. Mutation at Upazila Land Office\n\n**Inheritance:** NRB inherits property under same rules as residents (Muslim/Hindu/Christian personal law).\n\n📄 NRB property purchase checklist — ৳399",
    },
    escalate: false,
    relatedRules: ["nrb-property-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-006",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["nrb bank account", "nfcd account", "rfcd account", "foreign currency account bangladesh", "nrb savings"],
    question: "What bank accounts can an NRB open in Bangladesh?",
    irac: {
      issue: "What types of bank accounts are available to Non-Resident Bangladeshis and what are the benefits?",
      rule: "Bangladesh Bank Guidelines: NRBs can open NFCD (Non-Resident Foreign Currency Deposit) in USD/GBP/EUR/JPY. Interest is tax-free. Funds freely repatriable. RFCD (Resident Foreign Currency Deposit) for returnees who brought forex.",
      application: "An NRB in USA can open NFCD account at any scheduled bank in Bangladesh. Account can be operated from USA via internet banking. Can deposit remittances from USA. Interest earned is completely tax-free. Can use funds for property purchase, investment, or family expenses in Bangladesh.",
      conclusion: "**NRB Bank Accounts:**\n\n**NFCD (Non-Resident Foreign Currency Deposit):**\n✅ Available in USD, GBP, EUR, JPY\n✅ Interest completely TAX-FREE\n✅ Freely repatriable to any country\n✅ Can be operated from abroad\n✅ No permission needed to open\n\n**RFCD (Resident Foreign Currency Deposit):**\n• For returnees who brought forex legally\n• Up to USD 5,000 can be retained on return\n\n**How to open:**\n• Apply at any scheduled bank\n• Documents: Passport, visa, NID, proof of residence abroad\n• Can open via Power of Attorney if not in Bangladesh\n\n📋 NRB banking guide — ৳99",
    },
    escalate: false,
    relatedRules: ["nrb-account-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-007",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["foreign investment sectors", "which sectors foreign", "invest bangladesh", "allowed sectors", "restricted sectors bangladesh"],
    question: "Which sectors are open for foreign investment in Bangladesh?",
    irac: {
      issue: "Which industries and sectors allow foreign investment in Bangladesh and are there any restrictions?",
      rule: "BIDA Act 2016: Bangladesh maintains a negative list of restricted sectors. All other sectors are open to 100% foreign investment. Special incentives in EPZ and SEZ.",
      application: "Most sectors fully open: RMG, textiles, pharmaceuticals, ICT, agro-processing, leather, ceramics, light engineering, shipbuilding, power generation, infrastructure. Restricted: Arms/ammunition, nuclear energy, security printing, forestry in reserved/protected areas, certain media.",
      conclusion: "**Open Sectors (100% Foreign Ownership):**\n\n✅ Ready-Made Garments (RMG)\n✅ Pharmaceuticals\n✅ IT/Software/ITES\n✅ Agro-processing\n✅ Leather & footwear\n✅ Light engineering\n✅ Ship building\n✅ Power & energy\n✅ Infrastructure\n✅ Tourism & hospitality\n✅ Healthcare\n\n**Special Incentive Zones:**\n• EPZ — 10-year tax holiday\n• SEZ — 10-year tax holiday\n• Hi-Tech Park\n\n**Restricted Sectors:**\n❌ Arms & ammunition\n❌ Nuclear energy\n❌ Security printing\n❌ Reserved forest exploitation\n\n📄 Sector-specific investment guide — NLC can advise.",
    },
    escalate: false,
    relatedRules: ["nrb-bida-001", "nrb-tax-holiday-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-008",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["usa partner bangladesh", "american partner", "foreign partner company", "joint venture bangladesh", "foreign shareholder"],
    question: "Can I have a foreign partner or shareholder in my Bangladesh company?",
    irac: {
      issue: "What are the rules for having foreign nationals as shareholders or partners in a Bangladesh company?",
      rule: "Companies Act 1994 + BIDA Act 2016: Foreign nationals can be shareholders in a Bangladesh Pvt Ltd company. No minimum local shareholding requirement in most sectors. Foreign director can be appointed. Work permit required for foreign directors/employees working in Bangladesh.",
      application: "A Bangladesh-USA joint venture: Form Pvt Ltd at RJSC with both as shareholders. Register with BIDA for foreign investment. Shareholder agreement governs profit sharing, exit, decision-making. USD capital brought by US partner reported to Bangladesh Bank as FDI. US partner's income from Bangladesh taxable under Bangladesh-USA DTAA.",
      conclusion: "**Foreign Partner in Bangladesh Company:**\n\n✅ 100% foreign ownership allowed (most sectors)\n✅ Mixed ownership — any percentage split allowed\n✅ Foreign director allowed\n✅ No mandatory local partner requirement\n\n**What you need:**\n• BIDA registration (if >25% foreign shareholding)\n• Bangladesh Bank FDI reporting\n• Work permit for foreign directors working in BD\n• DTAA benefit — tax residency certificate from partner's country\n\n**Shareholder Agreement should cover:**\n• Profit distribution\n• Decision-making rights\n• Exit/buyout provisions\n• Dispute resolution (arbitration recommended)\n\n📄 Joint venture structure — NLC can advise.",
    },
    escalate: false,
    relatedRules: ["nrb-bida-001", "nrb-dtaa-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-009",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["tax holiday bangladesh", "epz tax", "sez investment", "tax exemption bangladesh", "10 year tax"],
    question: "What tax holidays are available for foreign investors in Bangladesh?",
    irac: {
      issue: "What tax exemptions and holidays are available to foreign investors under Bangladesh law?",
      rule: "Income Tax Act 2023 + BIDA Act 2016: EPZ investors — 10-year full tax exemption. SEZ investors — 10-year full tax exemption. Priority sectors outside zones — 5-10 year exemption depending on location. Listed companies pay 20% corporate tax vs 27.5% standard.",
      application: "A foreign company investing USD 2 million in an EPZ in Bangladesh will pay ZERO corporate income tax for 10 years. After 10 years, standard tax applies. Import of capital machinery is duty-free. Dividend repatriation allowed after paying 20% WHT (reduced under DTAA).",
      conclusion: "**Tax Holidays — Bangladesh:**\n\n| Location | Duration | Rate |\n|---|---|---|\n| EPZ | 10 years | 0% |\n| SEZ | 10 years | 0% |\n| Hi-Tech Park | 10 years | 0% |\n| Priority sector | 5 years | 0% |\n| After holiday | Ongoing | 27.5% |\n\n**Additional Incentives:**\n✅ Duty-free import of capital machinery\n✅ Tax exemption on royalties paid to foreign companies\n✅ Tax exemption on interest on foreign loans\n✅ Accelerated depreciation\n\n📄 Investment incentive analysis — NLC can advise.",
    },
    escalate: false,
    relatedRules: ["nrb-tax-holiday-001"],
    lastVerified: "2025-03-09",
  },
  {
    id: "nrb-qa-010",
    area: "nrb",
    jurisdiction: "BD",
    triggerKeywords: ["liaison office bangladesh", "rep office bangladesh", "branch office bangladesh", "representative office", "liaison vs branch"],
    question: "What is the difference between a liaison office, branch office, and subsidiary in Bangladesh?",
    irac: {
      issue: "What are the different types of foreign business presence in Bangladesh and which activities does each allow?",
      rule: "Companies Act 1994 + BIDA Guidelines: Three options for foreign presence. Each has different permitted activities, registration requirements, and tax implications.",
      application: "A Japanese trading company wanting to explore Bangladesh market: Liaison office is cheapest and fastest — just market research, no revenue. If they want to sign contracts and earn revenue — need branch office or subsidiary. Subsidiary (Pvt Ltd) gives most flexibility and local credibility.",
      conclusion: "**Three Types of Foreign Presence:**\n\n**1. Liaison/Representative Office:**\n• Permitted: Market research, promotion, coordination only\n• NOT permitted: Revenue-generating activities, signing contracts\n• Tax: No Bangladesh income tax (no revenue)\n• Registration: BIDA + Bangladesh Bank\n• Funding: Must be funded from parent abroad\n\n**2. Branch Office:**\n• Permitted: Commercial operations within approved scope\n• Can sign contracts, earn revenue\n• Tax: 30% on Bangladesh profits\n• Registration: RJSC + BIDA + Bangladesh Bank\n\n**3. Subsidiary (Pvt Ltd):**\n• Permitted: Full commercial operations ✅\n• Treated as Bangladesh company\n• Tax: 27.5% corporate tax\n• Best for long-term operations\n• Registration: RJSC + BIDA\n\n📄 Entity selection guide — NLC can advise.",
    },
    escalate: false,
    relatedRules: ["nrb-bida-001"],
    lastVerified: "2025-03-09",
  },
];

const nrbModule: KnowledgeModule = {
  area: "nrb",
  label: "NRB Investment & Foreign Investment Law",
  description: "10 Q&A covering BIDA registration, profit repatriation, WHT, DTAA, NRB remittance incentives, property rights, NFCD accounts, tax holidays, and foreign company structures in Bangladesh.",
  rules,
  qaBank,
};

export default nrbModule;
